<link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700|Open+Sans+Condensed:700" rel="stylesheet" type="text/css" />
<?php
/**
 * @version		1.0.0 cam assistant $
 * @package		cam_assistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
 $taxid = JRequest::getVar( 'taxid','' );
// Your custom code here
JHTML::_('behavior.modal'); ?>
<script type="text/javascript">
function addfile(data,taskid,filename){
window.parent.document.getElementById('lineuploads'+taskid).value =data;
window.parent.document.getElementById('delimg'+taskid).style.display ='';
window.parent.document.getElementById('uploadfile'+taskid).innerHTML =filename;
window.parent.document.getElementById( 'sbox-window' ).close();
}

function addmasterfile(data,taskid,filename){
strOut = data + '-' + filename;
window.parent.document.getElementById('lineuploads'+taskid).value =strOut;
window.parent.document.getElementById('delimg'+taskid).style.display ='';
window.parent.document.getElementById('uploadfile'+taskid).innerHTML =filename;
window.parent.document.getElementById( 'sbox-window' ).close();
}

</script>

<?php //echo 'anand'; //echo "<pre>";  print_r($this->pfiles);
$from = JRequest::getVar('from','');
 if($from == 'master')
 $additional = "&from=master";
 else
 $additional = "";
session_start();
$_SESSION['taskid']= $_REQUEST['taskid']; ?>
<?php //print_r($_SESSION['taskid']);?>
<div style="padding:5px;">
<div>
<?php if($from != 'master'){ ?>
<div align="right" style="padding-top:10px; padding-right:10px;"><a href="index2.php?option=com_camassistant&amp;controller=popupdocs&amp;task=opendocs&amp;taskid=<?php echo $_SESSION['taskid'];?>&amp;pid=<?php echo $_REQUEST['pid']; ?>"><img alt="info" src="templates/camassistant_left/images/back.png"/></a></div>
<?php } else { ?>
<div align="right" style="padding-top:10px; padding-right:10px;"><a href="index2.php?option=com_camassistant&amp;controller=popupdocs&amp;task=opendocs&amp;taskid=<?php echo $_SESSION['taskid'];?>&amp;pid=<?php echo $_REQUEST['pid']; ?>&from=master"><img alt="info" src="templates/camassistant_left/images/back.png"/></a></div>
<?php } ?>
<!-- eof dotshead -->
<div id="new_bar">
<div id="new_bar_txt" style="padding:0px;line-height:34px;">
<?php
$db = JFactory::getDBO();
$pid=$_REQUEST['pid'];
$db->setQuery('Select property_name,tax_id FROM #__cam_property where id="'.$pid.'"');
$db->query();
$propert_name = $db->loadObjectList();
?>
<?php //echo "<pre>"; print_r($_SESSION);echo "<pre>";  print_r($this->pfiles);?>
<!--<p style="color:#ffffff; margin-left:20px;"><?php //echo $propert_name[0]->property_name; ?></p>--> <!-- anil_24-08-2011 -->
<span style="color:#ffffff; margin-left:20px; text-transform:uppercase; font-family:ArialBlackRegular; font-weight:bold;"><strong><?php echo str_replace('_',' ',$propert_name[0]->property_name); ?></strong></span>

</div>

<div id="new_icon"></div>
</div>
 <link rel="stylesheet" href="templates/camassistant_inner/css/style.css" type="text/css" />
<!-- sof table pan -->
<br />
<div class="table_pannel">
<div class="table_panneldiv">
<table width="100%" cellpadding="0" cellspacing="4">
  <tr class="newtable_green_row">
    <td width="60" align="center" valign="top">SELECT</td>
    <td width="331" align="left" valign="top">Name</td>
    <td width="191" align="center" valign="top">options</td>
    </tr>

  <?php

  if(count($this->pfiles)){

for ($i=0; $i<count($this->pfiles); $i++){
$pfiles = $this->pfiles[$i];
$ext = explode('.', $pfiles->docTitle);
if(!$ext[1]) {
?>
<tr class="table_blue_rowdots2">
<td align="center" valign="bottom"><a href="index2.php?option=com_camassistant&controller=popupdocs&Itemid=76&taskid=<?php print_r($_SESSION['taskid']); ?>&task=openfiles&pid=<?php print_r($pfiles->property_id); ?>&mid=<?php print_r($pfiles->property_manager_id); ?>&path=<?php print_r($pfiles->docPath); ?>&fileplace=<?php echo $propert_name[0]->property_name."-->".$pfiles->docTitle;?>&taxid=<?php echo $taxid; ?><?php echo $additional; ?>"><img src="images/folder_icon.png"  alt="folder" /></a></td>
    <td align="left" valign="middle"><a href="index2.php?option=com_camassistant&controller=popupdocs&Itemid=76&taskid=<?php print_r($_SESSION['taskid']); ?>&task=openfiles&pid=<?php print_r($pfiles->property_id); ?>&mid=<?php print_r($pfiles->property_manager_id); ?>&path=<?php print_r($pfiles->docPath); ?>&fileplace=<?php echo $propert_name[0]->property_name."-->".$pfiles->docTitle;?>&taxid=<?php echo $taxid; ?><?php echo $additional; ?>"><?php echo str_replace('_',' ',$pfiles->docTitle); ?></a>
</td>
<td align="center" valign="middle">
<a href="index2.php?option=com_camassistant&controller=popupdocs&Itemid=76&task=openfiles&taskid=<?php print_r($_SESSION['taskid']); ?>&pid=<?php print_r($pfiles->property_id); ?>&mid=<?php print_r($pfiles->property_manager_id); ?>&path=<?php print_r($pfiles->docPath); ?>&fileplace=<?php echo $propert_name[0]->property_name."-->".$pfiles->docTitle;?>&taxid=<?php echo $taxid; ?><?php echo $additional; ?>">OPEN</a>
</td>
</tr>

<?php } }

// echo "<pre>"; print_r($pfiles);
for ($i=0; $i<count($this->pfiles); $i++){
$pfiles = $this->pfiles[$i];
$ext = explode('.', $pfiles->docTitle);
if($ext[1]) {
?>
<tr class="table_blue_rowdots2">
<?php $ext = end(explode('.', $pfiles->docTitle)); ?>
<td align="center" valign="bottom"><img src="templates/camassistant_inner/images/images_<?php echo $ext; ?>.png"  alt="folder" /></td>
<td align="left" valign="middle"><?php echo str_replace('_',' ',$pfiles->docTitle); ?>
</td>

<td align="center" valign="middle"><a href="index2.php?option=com_camassistant&controller=popupdocs&task=open&title=<?php print_r($pfiles->docTitle); ?>&path=<?php print_r($pfiles->docPath); ?> ">OPEN</a>
<?php //print_r($_SESSION['taskid']); print_r($_REQUEST['taskid']); ?>
<?php
$db = JFactory::getDBO();
$details = 'select property_name,tax_id FROM #__cam_property where id="'.$pid.'"';
$db->setQuery($details);
$p_details=$db->loadObject();
$default = 'components/com_camassistant/doc/'.$p_details->property_name.'_'.$p_details->tax_id.'/';
$path = str_replace($default,'',$pfiles->docPath);
?>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<?php if($from != 'master'){ ?>
<a href="javascript:void(0);" onclick="addfile('<?php echo $path; ?>','<?php print_r($_SESSION['taskid']); ?>','<?php print_r($pfiles->docTitle); ?>');">ADD TO RFP</a>
<?php } else { ?>
<a href="javascript:void(0);" onclick="addmasterfile('<?php echo $pid; ?>','<?php print_r($_SESSION['taskid']); ?>','<?php print_r($pfiles->docTitle); ?>');">ADD</a>
<?php } ?>

</td>
</tr>
<?php } }
}
 else { ?>
<tr class="table_blue_rowdots2">
    <td align="center" valign="bottom"><img src="images/folder_icon.png"  alt="folder" /></td>
    <td align="left" valign="middle"><?php echo "No files in this folder"; ?></td>
</tr>
<?php } ?>
 <tr class="table_blue_rowdots2">
   <td align="center" valign="bottom">&nbsp;</td>
   <td align="left" valign="top">&nbsp;</td>
   <td align="left" valign="top">&nbsp;</td>
   </tr>

</table>

<?php $val = 'components/com_camassistant/doc/';
if($pfiles->property_id ==''){
$pfiles->property_id = $_REQUEST['pid'];
}
if($pfiles->property_manager_id ==''){
$pfiles->property_manager_id = $_REQUEST['mid'];
}
$property = $propert_name[0]->property_name;
$property = str_replace(' ','_',$property);
$taxid = $propert_name[0]->tax_id;
$path = $val.$property."_".$taxid;
?>
<div class="table_bottomlinks2" style="display:none">
<ul>
<li  style=" background:none;"><a class="modal" id="links1"  title="Add Folder"  href="index2.php?option=com_camassistant&controller=popupdocs&task=addfolder&parentid=0&pid=<?php echo $pfiles->property_id; ?>&mid=<?php echo $pfiles->property_manager_id; ?>&path=<?php echo $path; ?>" rel="{handler: 'iframe', size: {x: 400, y: 200}}" ><img src="images/new_folder.png" alt="add a new folder" width="45" height="39" align="absmiddle" /> </a><a class="modal" id="links1"  title="Add Folder"  href="index.php?option=com_camassistant&controller=popupdocs&task=addfolder&parentid=0&pid=<?php echo $pfiles->property_id; ?>&mid=<?php echo $pfiles->property_manager_id; ?>&path=<?php echo $path; ?>" rel="{handler: 'iframe', size: {x: 400, y: 200}}" >+Add a new Folder  </a></li>

<li><a class="modal" id="links1"  title="Upload File"  href="index2.php?option=com_camassistant&controller=popupdocs&task=addfile&parentid=0&pid=<?php echo $pfiles->property_id; ?>&mid=<?php echo $pfiles->property_manager_id; ?>&path=<?php echo $path."/"; ?>" rel="{handler: 'iframe', size: {x: 420, y: 250}}" > +Upload a file to this folder <img src="images/upload_folder.png" alt="Upload a file to this folder" width="37" height="36" align="middle" /></a></li>
</ul>
</div>
</div></div>
</div><br /></div>
<?php exit; ?>