<link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700|Open+Sans+Condensed:700" rel="stylesheet" type="text/css" />
<?php
$from = JRequest::getVar('from','');
if($from == 'master')
$additional = '&from=master' ;
else
$additional = '';
/**
 * @version		1.0.0 cam assistant $
 * @package		cam_assistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here

//echo "this is shared default-1 file";
JHTML::_('behavior.modal'); ?>
<script>
function addfile(data,taskid,filename){
window.parent.document.getElementById('lineuploads'+taskid).value =data;
window.parent.document.getElementById('delimg'+taskid).style.display ='';
window.parent.document.getElementById('uploadfile'+taskid).innerHTML =filename;
/* if(taskid>20){
window.parent.document.getElementById('requiredoprice'+taskid).style.display ='block';
} */
window.parent.document.getElementById( 'sbox-window' ).close(); 
}

function addsharedfile(type,data,taskid,filename){
strOut = type + '-' + data;
window.parent.document.getElementById('lineuploads'+taskid).value =strOut;
window.parent.document.getElementById('delimg'+taskid).style.display ='';
window.parent.document.getElementById('uploadfile'+taskid).innerHTML =filename;
window.parent.document.getElementById( 'sbox-window' ).close(); 
}

</script>
<link rel="stylesheet" href="templates/camassistant_inner/css/style.css" type="text/css" />
<div style="float:right" ><br/>
</div>
<div class="clear"></div>
<?php 
if(!$_SESSION['taskid'])
$_SESSION['taskid']= $_REQUEST['taskid'];
$_SESSION['pid'] = $_REQUEST['pid'];
$pid = $_SESSION['pid'];
 ?>
<div align="right"><a href="index2.php?option=com_camassistant&controller=popupdocs&task=opendocs&amp;taskid=<?php echo $_SESSION['taskid'];?>&pid=<?php echo $pid;?><?php echo $additional; ?>"><img src="templates/camassistant_left/images/back.png" alt="info" /></a></div>
<div id="new_bar">
<div id="new_bar_txt">
<span>Shared Company Documents</span>
</div>
</div>
<?php //echo "We are working on this functionality"; ?>
<div class="table_pannel">
<div class="table_panneldiv">
<table width="100%" cellpadding="0" cellspacing="4">
  	<tr class="newtable_green_row">
    <td width="62" align="center" valign="top">SELECT</td>
    <td width="456" align="left" valign="top">Name</td>
    <td width="141" align="center" valign="top">options</td>
    </tr>
  <?php 
$user = JFactory::getUser(); 
for ($i=0; $i<count($this->sdocs); $i++){
$sdocs = $this->sdocs[$i]; 
$file = substr($sdocs->sdocTitle,-4,-3);
if($sdocs->sdocTitle){
$type = 'shared';
}
?>
<!--To get the file extension Modified by sateesh on 27-07-11-->
<?php 
$filename = $sdocs->sdocTitle;
$ext = end(explode('.', $filename));
$ext = substr(strrchr($filename, '.'), 1);
$ext = substr($filename, strrpos($filename, '.') + 1);
$ext = preg_replace('/^.*\.([^.]+)$/D', '$1', $filename);
$exts = split("[/\\.]", $filename);
$n = count($exts)-1;
$exts = $exts[$n];

if($exts=='gif' || $exts=='jpg' || $exts=='png' || $exts=='doc' || $exts=='psd' || $exts=='bmp' || $exts=='GIF' || $exts=='doc' || $exts=='docx' || $exts=='pdf' || $exts=='jpeg' || $exts=='rtf' || $exts=='xls' || $exts=='ppt' || $exts=='xlsx' || $exts=='docx' || $exts=='pptx'){
$exts = $exts;
$task = 'open';
if ($user->user_type=='13') { 
$path = 'components/com_camassistant/doc/'.str_replace(' ','_',$this->camfirm[0]->comp_name).'_'.str_replace(' ','_',$this->camfirm[0]->camfirm_license_no).'/'.$sdocs->sdocTitle; 
} else {
$path = 'components/com_camassistant/doc/'.str_replace(' ','_',$this->camfirm[0]->comp_name).'_'.str_replace(' ','_',$this->camfirm[0]->camfirm_license_no).'/'.$user->id.'/'.$sdocs->sdocTitle;  
}
$type='shared';

} else{
$task = 'sopenfiles';
$exts = 'folder';

if ($user->user_type=='13') { 
$path = 'components/com_camassistant/doc/'.str_replace(' ','_',$this->camfirm[0]->comp_name).'_'.str_replace(' ','_',$this->camfirm[0]->camfirm_license_no).'/'.$sdocs->sdocTitle; 
} 
else{
$path = 'components/com_camassistant/doc/'.str_replace(' ','_',$this->camfirm[0]->comp_name).'_'.str_replace(' ','_',$this->camfirm[0]->camfirm_license_no).'/'.$user->id.'/'.$sdocs->sdocTitle; 
}
$fileplace = $sdocs->sdocTitle;
$type='shared';
}

if($sdocs->parent_manager==0){
$path = $path;
}
else{
$companyname = $this->camfirm[0]->comp_name.'_'.$this->camfirm[0]->camfirm_license_no; 
$companyname = str_replace(' ','_',$companyname);
$paths = str_replace($companyname,$companyname.'/'.$sdocs->property_manager_id,$path);
$path = $paths;
}
//echo $path; echo "<br>";
?>
<!--To get the file extension Modified by sateesh on 27-07-11 completed-->
<?php if($sdocs->sdocTitle){ ?>
<tr class="table_blue_rowdots2">
<!--<td><img src="images/doc.png" /></td>-->
<td align="center" valign="bottom"><a href="index2.php?option=com_camassistant&controller=popupdocs&Itemid=<?php echo $_REQUEST['Itemid']; ?>&propertyname=<?php print_r($sdocs->sdocTitle);  ?>&task=<?php echo $task; ?>&fileplace=<?php echo $fileplace; ?>&type=<?php echo $type; ?>&spath=<?php echo $path;?>&spid=<?php echo $sdocs->id; ?>&smid=<?php echo $sdocs->property_manager_id; ?>&pid=<?php echo $pid;?>&taskid=<?php echo $_SESSION['taskid'];?><?php echo $additional; ?>"><img src="templates/camassistant_inner/images/images_<?php echo $exts; ?>.png" /></a></td>

<td align="left" valign="middle"><a href="index2.php?option=com_camassistant&controller=popupdocs&Itemid=<?php echo $_REQUEST['Itemid']; ?>&propertyname=<?php print_r($sdocs->sdocTitle);  ?>&task=<?php echo $task; ?>&fileplace=<?php echo $fileplace; ?>&type=<?php echo $type; ?>&spath=<?php echo $path;?>&spid=<?php echo $sdocs->id; ?>&smid=<?php echo $sdocs->property_manager_id; ?>&pid=<?php echo $pid;?>&taskid=<?php echo $_SESSION['taskid'];?><?php echo $additional; ?>"><?php echo str_replace('_',' ',$sdocs->sdocTitle);  ?></a>
</td>
<td align="center" valign="middle" nowrap="nowrap">
<?php if($file=='.') {
	if($from != 'master'){ ?>
	
<a href="javascript:void(0);" onclick="addfile('<?php echo $path; ?>','<?php print_r($_SESSION['taskid']); ?>','<?php echo str_replace('_',' ',$sdocs->sdocTitle); ?>');">ADD TO RFP</a>
<?php }
else { ?>
<a href="javascript:void(0);" onclick="addsharedfile('shared','<?php echo $path; ?>','<?php print_r($_SESSION['taskid']); ?>','<?php echo str_replace('_',' ',$sdocs->sdocTitle); ?>');">ADD</a>
<?php } 
}
else {?>
<a href="index2.php?option=com_camassistant&controller=popupdocs&Itemid=<?php echo $_REQUEST['Itemid']; ?>&propertyname=<?php print_r($sdocs->sdocTitle);  ?>&task=<?php echo $task; ?>&fileplace=<?php echo $fileplace; ?>&type=<?php echo $type; ?>&spath=<?php echo $path;?>&spid=<?php echo $sdocs->id; ?>&smid=<?php echo $sdocs->property_manager_id; ?>&pid=<?php echo $pid;?>&taskid=<?php echo $_SESSION['taskid'];?><?php echo $additional; ?>">OPEN</a>
<?php } ?>
</td>
</tr>
<?php }  else {?>

<tr class="table_blue_rowdots2">
<!--<td><img src="images/doc.png" /></td>-->
<td align="center" valign="bottom"><a href="index2.php?option=com_camassistant&controller=popupdocs&Itemid=<?php echo $_REQUEST['Itemid']; ?>&propertyname=<?php echo  $sdocs->property_name; ?>&task=sfiles&spid=<?php echo $sdocs->id; ?>&smid=<?php echo $sdocs->property_manager_id; ?>&taxid=<?php echo $sdocs->tax_id; ?>&taskid=<?php echo $_SESSION['taskid'];?><?php echo $additional; ?>"><img src="templates/camassistant_inner/images/images_<?php echo $exts; ?>.png" /></a></td>

<td align="left" valign="middle"><a href="index2.php?option=com_camassistant&controller=popupdocs&Itemid=<?php echo $_REQUEST['Itemid']; ?>&propertyname=<?php echo  $sdocs->property_name; ?>&task=sfiles&spid=<?php echo $sdocs->id; ?>&smid=<?php echo $sdocs->property_manager_id; ?>&taxid=<?php echo $sdocs->tax_id; ?>&taskid=<?php echo $_SESSION['taskid'];?><?php echo $additional; ?>"><?php print_r($sdocs->property_name);  ?></a>
</td>
<td align="center" valign="middle"><a href="index2.php?option=com_camassistant&controller=popupdocs&Itemid=<?php echo $_REQUEST['Itemid']; ?>&propertyname=<?php echo  $sdocs->property_name; ?>&task=sfiles&spid=<?php echo $sdocs->id; ?>&smid=<?php echo $sdocs->property_manager_id; ?>&taxid=<?php echo $sdocs->tax_id; ?>&taskid=<?php echo $_SESSION['taskid'];?><?php echo $additional; ?>">OPEN</a>
</td>
</tr>
<?php }} ?>


<tr class="table_blue_rowdots2">
   <td align="center" valign="bottom">&nbsp;</td>
   <td align="left" valign="top">&nbsp;</td>
   <td align="left" valign="top">&nbsp;</td>
   </tr>
  <tfoot>
		<td colspan="9">
			<?php echo $this->pagination->getPagesLinks(); ?>
            <?php echo $this->pagination->getPagesCounter(); ?>
		</td>
	</tfoot>

</table>
<?php  
if ($user->user_type=='13') { 
$path = 'components/com_camassistant/doc/'.str_replace(' ','_',$this->camfirm[0]->comp_name).'_'.$this->camfirm[0]->camfirm_license_no; 
} else{
$path = 'components/com_camassistant/doc/'.str_replace(' ','_',$this->camfirm[0]->comp_name).'_'.$this->camfirm[0]->camfirm_license_no.'/'.$user->id; 
}



?>
<div class="clear"></div>
<div class="table_bottomlinks2">
<ul>
<li  style=" background:none;"><img src="images/new_folder.png" alt="add a new folder" width="45" height="39" align="absmiddle" /><a class="modal" id="links1"  title="Add Folder"  href="index2.php?option=com_camassistant&controller=popupdocs&task=saddfolder&type=shared&parentid=0&smid=<?php echo $user->id; ?>&spath=<?php echo $path; ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?> " rel="{handler: 'iframe', size: {x: 400, y: 200}}" >Add a folder</a></li>

<li><img src="images/upload_folder.png" alt="Upload a file to this folder" width="37" height="36" align="middle" /><a class="modal" id="links1"  title="Upload File"  href="index2.php?option=com_camassistant&controller=popupdocs&task=saddfile&type=shared&parentid=0&smid=<?php echo $user->id; ?>&spath=<?php echo $path; ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?>" rel="{handler: 'iframe', size: {x: 500, y: 250}}" >Upload a file</a></li> 
</ul>
</div>
 
<!--<div id="pagination" class="pagination_bg">
		<?php //echo $this->pagination->getPagesLinks(); ?>
		<?php //echo $this->pagination->getPagesCounter(); ?>
</div>
-->


</div></div><?php exit; ?>