<script type="text/javascript" src="components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>
<script language="JavaScript" type="text/javascript" src="components/com_camassistant/assets/wysiwyg_terms.js"></script>
<script type="text/javascript">
  //Functio to verify taxid by sateesh on 03-08-11
H = jQuery.noConflict();
var site='<?php echo JURI::root();?>';
var path='<?php echo addslashes(JPATH_SITE);?>';
var countyCount = 0;
	H(document).ready(function(){
	H(".continue_invitation").click(function(){
		var form = document.inviteform;
		var ccemail=H("#email").val();
		var subject = H("#subject").val();
			if(!ccemail)
				{
					alert("Please enter email");
					form.email.focus();
					return false;
				}
		var mail=/\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/;
			if(mail.test(ccemail)==false)
			{
				alert("Please enter a proper email address.");
				form.email.focus();
				return false;
			}
			if(!subject){
				alert("Please enter subject");
				form.subject.focus();
				return false;
			}
		var ccemail = (ccemail).split(';');	
		var s = ccemail;
		var re = /,/g;
//		for( var c = 0; re.exec(s); ++c );
			if(ccemail != '')
				{
					for (var i =0; i < ccemail.length; i++)
						{		
//							
							var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
							if(re.test(trim(ccemail[i]))==false)
							{
								alert("please enter a valid email addresses");
								return false;  
							}
							H.post("index2.php?option=com_camassistant&controller=vinvitations&task=checktoallemails", {mailid: ""+ccemail[i]+""}, function(data){
		if(data == 1){
		alert("Already manager exists with this email");
		return false;
		}
		else
		form.submit();
		});
							
			}
		}	
	
		//form.submit();
		
				
	});
		
H('.cancel_invitation').click(function()
{
window.location = 'index.php?option=com_camassistant&controller=rfpcenter&task=dashboard&Itemid=125';
});	
	

	
H('#editoption').live('click',function(){
		H('#aboutform').show();
		H('.vendorinvitationmailedit').hide();
		H('.mainformbuttons').hide();
		
		N(".termsandconditions").css("height","250px"); 
		});	
});
H('#saveoption').live('click',function(){
      H('#editable').val('');
		H('textarea[rel="editor"]').each(function(){
		var n=H(this).attr('id');
		document.getElementById(n).value = document.getElementById("wysiwyg" + n).contentWindow.document.body.innerHTML;
		notesstrings = document.getElementById(n).value ;
		notesstrings = notesstrings.replace("’", "'");
		notesstrings = notesstrings.replace(/[^\u000A\u0020-\u007E]/g, ' ');
		document.getElementById(n).value = notesstrings ;
		});
		if (notesstrings.indexOf("{winning Bid}") < 0)
		{
			//pricepopupbox();
			//alert("Please don't remove the text {winning Bid} from the notification");
            
			message = H('#ctl00_CPHContent_txtComments').val();
			email_new = H('#email').val();
			subject_new = H('#subject').val();
		H.post("index2.php?option=com_camassistant&controller=vinvitations&task=saveinvitationmail", {mailtext: ""+message+"",email_new: ""+email_new+"",subject_new: ""+subject_new+""}, function(data){
		
	window.location = 'index.php?option=com_camassistant&controller=vinvitations&task=invitation_change&Itemid=216';
		
		});
			//H( "#vendorinvitation" ).submit();
		}
		else{
		H( "#vendorinvitation" ).submit();
		}
	});
	
H('#cancellink').live('click',function(){
location.reload();
});	
	</script>
<script type="text/javascript">
H = jQuery.noConflict();
H(document).ready(function(){
H('#email').keyup(function(){
		if( H(this).val() == '' )
		H( this ).prev().removeClass( 'active' );
		else
		H( this ).prev().addClass( 'active' );
	});
	H('#subject').keyup(function(){
		if( H(this).val() == '' )
		H( this ).prev().removeClass( 'active' );
		else
		H( this ).prev().addClass( 'active' );
	});
	
	});
</script>	
<link href="<?php JPATH_SITE ?>templates/camassistant/css/popup.css" rel="stylesheet" type="text/css"/>
<style>
#semdInvitation:hover{
opacity:0.8
}
</style>
<?php
/**
 * @version		1.0.0 cam assistant $
 * @package		cam_assistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
JHTML::_('behavior.modal');
$usertype = JRequest::getVar('usertype','');
	?>
    <?php 
$user =& JFactory::getUser();
$user_info = $this->userinfo;
//echo '<pre>';print_r($user_info);exit; 
if($user->user_type == 11)
{ ?>
<div align="center" style="color:#0066FF; font-size:15px"> You are not authorized to view this page.</div>
<?php } else { ?>
<div id="bedcrumb" style="display:none">
<ul>
<br/>
<li class="home"><a href="index.php?option=com_camassistant&controller=vendors&task=vendor_dashboard&Itemid=112">Home</a> </li>
<li>Invitations</li>
<!--<li><a href="#">Proposals Under Review</a></li> -->
</ul>
</div>
<p style="height:20px;"></p>
<div style="margin-top:-20px;">
<div id="i_bar">
<div style="width:600px; color:#fff; text-align:center; padding-left:37px; font-size:14px;" id="i_bar_txt"><strong>INVITE A VENDOR</strong>
</div>
<div id="i_icon">
<a href="index2.php?option=com_content&amp;view=article&amp;id=289&amp;Itemid=113" rel="{handler: 'iframe', size: {x: 680, y: 530}}" class="modal" title="Click here" style="text-decoration: none;"><img src="templates/camassistant_left/images/info_icon2.png"> </a>
</div>
</div>
</div>

<form name="inviteform" id="inviteform" method="post" >

<div id="invite-vendor" style="margin-top:42px;>
<div class="newvendor_invitation">
<label class="smallimage"></label>
<div class="invite-newvenodor">
<label><span style="padding-right: 20px;">EMAIL</span></label>
<div class="smallimage">&nbsp;</div>
<input type="text" value="" name="email" id="email">
</div>
<div class="vendormailinfo">
<strong>TIP:</strong> You can invite multiple Vendors at once by separating different email addresses with a semi-colon (;). Each Vendor will be sent a seperate invite and will not see the email addresses associated with other Vendors. 
</div>

<div>
<div class="invite-newvenodor">
<label><span style="padding-left: 10px;">SUBJECT</span></label>
<div class="smallimage">&nbsp;</div>
<input  type="text"  id="subject" name="subject">
</div>
  
</div>
</div>
<div class="vendorinvitationmailedit"><?php  echo html_entity_decode($this->mailbody); ?> 
<p id="topborder_row_awarded"></p>
<table cellpadding="0" cellspacing="0" width="100%" class="awardjob_table">
<tr>
<td align="right">
<a id="editoption" href="javascript:void(0);" class="editoption_award"><strong><img src="templates/camassistant_left/images/EditMini.png" /></strong></a></td>
</tr>

</table>
</div>
<div class="clear"></div>

<div class="mainformbuttons">
<a href="javascript:void(0);" class="cancel_invitation"></a>
<a href="javascript:void(0);" class="continue_invitation"></a>
</div>

</div>
<input type="hidden" value="com_camassistant" name="option">
<input type="hidden" value="vinvitations" name="controller">
<input type="hidden" value="sendinvitation" name="task">
</form>

<div id="aboutform" style="display:none;" >
<form action="" method="post" id="vendorinvitation">
<table cellpadding="0" cellspacing="0">
<tr><td colspan="3">
 <textarea rel="editor" name="mailtext" id="ctl00_CPHContent_txtComments" style="height:250px; margin-left:1px; width:667px;"><?php echo ($this->mailbody); ?></textarea>
 <script language="javascript1.2">
generate_wysiwyg('ctl00_CPHContent_txtComments');

</script>

 </td></tr>
 <tr height="5"></tr>
 <tr>
 <td align="right"><a href="javascript:void(0);" id="cancellink"><img src="templates/camassistant_left/images/CancelMini.png" /></a> <a id="saveoption" href="javascript:void(0);" style="font-weight:bold; color: #7ab800;"><img src="templates/camassistant_left/images/SaveMini.png" /></a></td></tr>
<tr height="10"></tr>
<tr><td style="color: #808080; font-size: 13px; padding-left: 9px; text-align: left;">
<span id="charcount">
</td></tr>
</table>

<input type="hidden" value="com_camassistant" name="option">
<input type="hidden" value="vinvitations" name="controller">
<input type="hidden" value="saveinvitationmail" name="task">
<input type="hidden" value="" id="editable" />
</form>
</div>

	<?php } ?>
	

	<div class="clear"></div>
	<?php
	//echo "<pre>"; print_r($this->vendors);
	?>
	
	