<script type="text/javascript" src="components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>
<script type="text/javascript">
  //Functio to verify taxid by sateesh on 03-08-11
H = jQuery.noConflict();
var site='<?php echo JURI::root();?>';
var path='<?php echo addslashes(JPATH_SITE);?>';
var countyCount = 0;
H(document).ready(function(){
H("#semdInvitation").click(function(){
		var form = document.inviteform;
		var email=H("#email").val();
		var ccemail=H("#ccemail").val();
		var ccemail = (ccemail).split('.com');	
		
		var s = ccemail;
		var re = /,/g;
		for( var c = 0; re.exec(s); ++c );
		var mail=/\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/;
		if(!email){
		alert("Please enter email");
		return false;
		}
		if(mail.test(email)==false)
		 {
		 alert("Please enter a proper email address.");
		 form.email.focus();
		 return false;
		 }
		 
		 if(ccemail != '' && c>1){
			for (var i =1; i < ccemail.length-1; i++)
			 {		
			   if(ccemail[i].charAt(0) != ";"){
				 alert('Please separate the CC Emails with Semi colon(;)');
				 form.ccemail.focus();
				 return false;  
				}
				else{
				form.submit();
				}	
			 }	
			}
		else{
		form.submit();
		}	
				 
	});
	

});

function resendinvitation(emailid,id,managrid){

	H('.resending_'+id).html('<img src="templates/camassistant_left/images/loading_icon.gif" />');
	H.post("index2.php?option=com_camassistant&controller=vinvitations&task=resendinvitation", {email: ""+emailid+"",managerid: ""+managrid+""}, function(data){
		if(data){	
		alert("Your invitation has been sent successfully.");			
		window.location.reload();
		}
	});
}	

function sortmanagers()
{
val = H('#managers_ass').val();
type = H('#usertype').val();
window.location.href = 'index.php?option=com_camassistant&controller=vinvitations&task=specific&Itemid=<?php echo $_REQUEST['Itemid']; ?>&cid='+val+'&type='+type;

}
	</script>

<link href="<?php JPATH_SITE ?>templates/camassistant/css/popup.css" rel="stylesheet" type="text/css"/>
<style>
#semdInvitation:hover{
opacity:0.8
}
</style>
<?php
/**
 * @version		1.0.0 cam assistant $
 * @package		cam_assistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
JHTML::_('behavior.modal');
$usertype = JRequest::getVar('usertype','');

	?>
    <?php 
$user =& JFactory::getUser(); 
if($user->user_type == 11)
{ ?>
<div align="center" style="color:#0066FF; font-size:15px"> You are not authorized to view this page.</div>
<?php } else { ?>
<div id="bedcrumb" style="display:none">
<ul>
<br/>
<li class="home"><a href="index.php?option=com_camassistant&controller=vendors&task=vendor_dashboard&Itemid=112">Home</a> </li>
<li>Invitations</li>
<!--<li><a href="#">Proposals Under Review</a></li> -->
</ul>
</div>
<p style="height:20px;"></p>


	<?php } ?>
	

<div id="add-vendor-new">
<div class="new-searchfilerts" style="margin-bottom:0px;">
<div align="center" class="optional_filters">OPTIONAL FILTERS</div>
<select onchange="javascript:sortmanagers();" style="width:330px;" name="usertype" id="usertype">
<option value="">All Vendors</option>
<option value="uv" <?php if( $_REQUEST['type'] == 'uv' ) echo 'selected="selected"';?> >Unregistered Vendors</option>
<option value="rv" <?php if(  $_REQUEST['type'] == 'rv' ) echo 'selected="selected"';?>>Registered Vendors</option>
</select>


</div>
</div>

<div id="add-vendor-new">
<div class="new-searchfilerts" style="margin-bottom:50px;">
   <?php 

if($user->user_type != 12 && $user->user_type != 16)
{ ?>
<select name="manageridass" style="width:330px;" onchange="javascript:sortmanagers();" id="managers_ass">
<option value="0"> All Managers</option>
  <?php
 
for ($m=0; $m<count($this->managers_all); $m++){
$mans = $this->managers_all[$m];
?>
<option  <?php if($_REQUEST['cid']==$mans->id ) echo "selected";?> value="<?php echo $mans->id; ?>"><?php echo $mans->name.'&nbsp;'.$mans->lastname; ?></option>
<?php } ?>
</select>
<?php } ?>
</div>
</div>
<div class="clear"></div>
	<div id="i_bar_gray">
<div id="i_bar_terms_rfp">
<div id="i_bar_txt_terms_rfp">
<span> <font style="font-weight:bold; color:#FFF; font-size:14px;">INVITED VENDORS </font></span>
</div></div>

    
</div>

	<?php
	$sort = JRequest::getVar('sort','');
	if($sort == 'asc' || $sort == ''){
	$sort = 'desc';
	$id = 'compliant_desc';
	}
	else{
	$sort = 'asc';
	$id = 'compliant_asc';
	}
	?>
	
	<?php
	$sort_date = JRequest::getVar('sort_date','');
	if($sort_date== 'desc1' || $sort_date == ''){
	$sort_date = 'asc1';
	$sort_id = 'compliantdate_desc';
	}
	else{
	$sort_date = 'desc1';
	$sort_id = 'compliantdate_asc';
	}
	
	?>
	
<div class="table_pannel">
<div class="table_panneldiv tablenew">
<table width="100%" cellspacing="0" cellpadding="0" >
  <tbody><tr class="table_green_row" style="text-transform:none;">
<td  valign="middle" align="left">
<a id="<?php echo $id; ?>" href="index.php?option=com_camassistant&controller=vinvitations&task=invitedvendors&Itemid=276&sort=<?php echo $sort ; ?>&usertype=<?php echo $usertype; ?>&cid=<?php echo $_REQUEST['cid'] ?>&type=<?php echo $_REQUEST['type'] ?>">EMAIL ADDRESS</a>
</td>
<td  valign="middle" align="center">SENT BY</td>
<td  valign="middle" align="center"><a id="<?php echo $sort_id; ?>" href="index.php?option=com_camassistant&controller=vinvitations&task=invitedvendors_date&Itemid=276&sort_date=<?php echo $sort_date ; ?>&usertype=<?php echo $usertype; ?>&cid=<?php echo $_REQUEST['cid'] ?>&type=<?php echo $_REQUEST['type'] ?>">LAST SENT</a></td>
<td  valign="middle" align="center" >STATUS</td>
  </tr>

<?php
$vendors = $this->vendors ;
 for($i=0; $i<count($vendors); $i++){ 
 	if(  $_REQUEST['type'] == 'uv' ){
		if( $vendors[$i]->status == 'accepted' )
		$display = 'none';
		else
		$display = '';
	}
	if(  $_REQUEST['type'] == 'rv' ){
		if( $vendors[$i]->status != 'accepted' )
		$display = 'none';
		else
		$display = '';
	}
 
  $db =& JFactory::getDBO();
  $manager_name ="SELECT name,lastname FROM #__users where id=".$vendors[$i]->managerid." ";
  $db->setQuery( $manager_name );
  $manager_name = $db->loadObject(); 
  $manager_name = $manager_name->name.'&nbsp;'.$manager_name->lastname;
 ?>
<tr id="table_blue_rowdots345406" class="table_blue_rowdots" style="height:45px; display:<?php echo $display; ?>">
<td  valign="middle" align="left" ><?php echo $vendors[$i]->vendoremailid; ?></td>
<td  valign="middle" align="center"><?php echo $manager_name; ?>
</td>
<td  valign="middle" align="center" style="padding-left:23px;"><?php 
$date_sent = explode(' ',$vendors[$i]->date);
$expdate = explode('-',$date_sent[0]);
echo $expdate[1].'/'.$expdate[2].'/'.$expdate[0]; ?></td>

<td  valign="middle" align="center" >
<?php 
if($vendors[$i]->status == 'accepted'){ ?>
<a title="Registered"  class="greenemailsdispay"><i class="material-icons">check_circle</i></a>
<?php }
else{ ?>
<a title="Not Registered.  Click to resend invite" id="hidevendor_new" class="resending_<?php echo $vendors[$i]->id; ?>" href="javascript:void(0);" onclick="resendinvitation('<?php echo $vendors[$i]->vendoremailid; ?>',<?php echo $vendors[$i]->id; ?>,<?php echo $vendors[$i]->managerid; ?>);" rel="<?php echo $vendors[$i]->id; ?>-<?php echo $vendors[$i]->vendoremailid; ?>"><i class="material-icons">error</i></a>

<?php }
?>
</td>
</tr>
<?php } 
 if( count($vendors)<=0  )
 { ?>
 <tr>
    <td colspan="5"  align="center" valign="top"><p style="margin-bottom:10px; margin-top:10px;">There are no invited vendors at this time</p></td>
  </tr>
  <?PHP } ?>
</table>
</div>
</div>
	<?php
	//echo "<pre>"; print_r($this->vendors);
	?>
	
	