<?php

/**
 * @version		1.0.0 camsignup $
 * @package		camsignup
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		anand kumar
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

$Itemid = JRequest::getVar('Itemid','');
//echo "<pre>"; print_r($_REQUEST);
// Your custom code here
//$today = date('Y-m-d'); ?>
<script type="text/javascript" language="javascript">

	function tableOrdering( order, dir, task )
	{
		var form = document.RFPbypropertyForm;

		form.filter_order.value 	= order;
		form.filter_order_Dir.value	= dir;
		document.RFPbypropertyForm.submit( task );
	}
G = jQuery.noConflict();
function openpopup(rfpid) {
var total=rfpid;

var el ='index.php?option=com_camassistant&controller=rfpcenter&task=proposalawarding&Itemid=<?php echo $_REQUEST['Itemid']; ?>&rid='+total;

	var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 700, y:550}}"))
SqueezeBox.fromElement(el,options);

}
G = jQuery.noConflict();
function popup_proposal_summary(rfp_id)
{
G.post("index2.php?option=com_camassistant&controller=vendors&task=keypath&tmpl=component", {rfpid: ""+rfp_id+""}, function(data){
if(data.length >0) {
window.location.href='ziptest.php?directtozip='+data+'&rfpid='+rfp_id+'';
}
});
}

function getcompliancestate(rfpid,vendorid,custid){
el='<?php  echo Juri::base(); ?>index.php?option=com_camassistant&controller=rfp&task=getcompliance_active&from=active&rfpid='+rfpid+'&custid='+custid+'&vendorid='+vendorid+'';
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 650, y:700}}"))
SqueezeBox.fromElement(el,options);
}

function cancelrequest(rfpid) {
var el ='index.php?option=com_camassistant&controller=rfpcenter&task=getcloserfp&rfpid='+rfpid;
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 700, y:300}}"))
SqueezeBox.fromElement(el,options);
}
</script>
<?php

$user = JFactory::getUser();
if($user->user_type == 11)
{ ?>
<div align="center" style="color:#0066FF; font-size:15px"> You are not authorized to view this page.</div>
<?php } else { ?>
<div id="vender_right">

<!-- sof bedcrumb -->
<!--<div id="bedcrumb">
<ul>
<li class="home"><a href="index.php">Home  </a></li><li>View RFPs By Property</li>
</ul>
</div>-->
<!-- eof bedcrumb -->
<?php  //print_r($_SESSION['filter_Status']); ?>
<p style="height:10px;"></p>
<form name="RFPbypropertyForm" method="post" action="index.php?option=com_camassistant&controller=sorting&task=sorting_rfps_by_property&Itemid=<?PHP echo $Itemid;  ?>&limitstart=''" />

<?php //print_r($user->user_type); ?>
<!-- sof dotshead -->
<!--<div id="dotshead_blue">VIEW RFPS BY PROPERTY</div>--><div align="center" style="padding-bottom: 5px;">
<table cellpadding="0" cellspacing="0">
<tr><td>
<?PHP echo $this->Managers; ?>
</td>
</tr>
<tr height="15"></tr>
<tr><td>
<?PHP echo $this->Properties; ?>
</td></tr>
<tr height="15"></tr>
<tr><td>
<?PHP echo $this->RFP_status; ?>
</td></tr>
<tr height="15"></tr>
</table>
</div>
<!-- eof dotshead -->
<div id="i_bar">
<div id="i_bar_txt" style="color:#fff; font-weight: bold;">ALL REQUESTS
</div>
<div id="i_icon"><?php
 $user = JFactory::getUser();
if ($user->user_type=='12') { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=70&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" /> </a>
<?php } else { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=81&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" /> </a>
<?php } ?></div>
</div>

<!-- sof table pan -->
<div class="table_pannel">
<div class="table_panneldiv">
<table width="100%" cellpadding="0" cellspacing="4" class="vendortable">
 <tr class="vendorfirsttr">
    <td width="350" align="center" valign="middle">PROJECT NAME</td>
    <td width="104" align="center" valign="middle">STATUS</td>
    <td width="399" align="center" valign="middle">INFO / OPTIONS</td>
    </tr>
  	<?php
	$k = 0;
//	echo count($this->RFP_list_by_Prp);
	foreach ($this->RFP_list_by_Prp as $row) :
		//echo "<pre>"; print_r($row); ?>
		<?php 
	 	if( $row->jobtype == 'yes' ) {
		$jobtype = 'basic';
		}
		else{
		$jobtype = '';		
		}
	 ?>
  <tr class="table_blue_rowdots">
    <td align="center" valign="middle">
	<a class="joblinkhomepage" href="index.php?option=com_camassistant&controller=rfp&task=reviewrfp&rfpid=<?php echo $row->id;  ?>&var=view&job=<?php echo $jobtype; ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?>"><?PHP echo $row->projectName; ?></a></td>
    <td align="center" valign="middle"><?PHP if ($row->rfp_type == 'closed'){
	echo "Closed";
	} else if ($row->rfp_type == 'draft'){
	echo "Drafts";
	}  else if ($row->rfp_type == 'UNAWARDED'){
	echo "Canceled";
	} else if ($row->rfp_type == 'AWARDED'){
	echo "Awarded";
	} else if ($row->rfp_type == 'CLOSED'){
	echo "Closed";
	} else if ($row->rfp_type == 'rfp'){
	echo "Active Bidding";
	} else if($row->rfp_type == 'Unawarded'){
	echo "Canceled";
	} else {
	echo $row->rfp_type;
	 } ?>

     </td>
	 <?php 
	 	if( $row->jobtype == 'yes' ) {
		$jobtype = 'basic';
		}
		else{
		$jobtype = '';		
		}
	 ?>

    <td align="center" valign="center"><?PHP if($row->rfp_type == 'Closed' ||$row->rfp_type == 'closed'){ ?>
    <ul class="divid_list">
<li style=" background:none;" ><a href="index.php?option=com_camassistant&controller=rfp&task=reviewrfp&rfpid=<?php echo $row->id;  ?>&job=<?php echo $jobtype; ?>&var=view&Itemid=<?php echo $_REQUEST['Itemid']; ?>">VIEW</a></li>
    <li> <a href="javascript:popup_proposal_summary(<?php echo $row->id; ?>);">DOWNLOAD</a></li>
   <li><a href="#" onclick="openpopup('<?php echo $row->id; ?>');">AWARD</a></li>
 <!--<li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=awardjob&rid=<?php echo $row->id; ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?>">AWARD</a></li>-->
    <!--<li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=unawardingjob&rid=<?php //echo $row->id; ?>&Itemid=<?php //echo $_REQUEST['Itemid']; ?>">UNAWARD</a></li>-->
    <li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=copydraft&rfpid=<?php echo $row->id; ?>&Itemid=<?php echo $Itemid; ?>">COPY TO DRAFT</a>
    </li></ul>
	<?PHP } else if ($row->rfp_type == 'Draft' ||$row->rfp_type == 'draft') {?>
	<ul class="divid_list"><?php /*?><li style=" background:none;"> Created <?php echo $row->createdDate; ?> </li><?php */?><li style="background:none;" ><a href="index.php?option=com_camassistant&controller=rfp&task=reviewrfp&rfpid=<?php echo $row->id;  ?>&job=<?php echo $jobtype; ?>&var=view&Itemid=<?php echo $_REQUEST['Itemid']; ?>">VIEW</a></li><li><a href="index.php?option=com_camassistant&controller=rfp&task=editrfp&var=draft&rfpid=<?php echo $row->id; ?>&job=<?php echo $jobtype; ?>&Itemid=<?php echo $Itemid; ?>">EDIT</a></li><li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=copydraft&rfpid=<?php echo $row->id; ?>&job=<?php echo $jobtype; ?>&Itemid=<?php echo $Itemid; ?>">COPY TO DRAFT</a></li></ul>
	<?PHP } else if ($row->rfp_type == 'rfp') {?>
	 <ul class="divid_list"><?php /*?><li style=" background:none;"> Created  <?php echo $row->createdDate; ?> </li><?php */?><li style="background:none;" ><a href="index.php?option=com_camassistant&controller=rfp&task=reviewrfp&rfpid=<?php echo $row->id;  ?>&var=view&job=<?php echo $jobtype; ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?>">VIEW</a></li><li><a href="index.php?option=com_camassistant&controller=rfp&task=editrfp&rfpid=<?php echo $row->id; ?>&job=<?php echo $jobtype; ?>&Itemid=<?php echo $Itemid; ?>">MODIFY</a></li><li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=copydraft&rfpid=<?php echo $row->id; ?>&Itemid=<?php echo $Itemid; ?>">COPY TO DRAFT</a></li></ul>
	 <?PHP } else if ($row->rfp_type == 'Awarded') {?>
	 <ul class="divid_list">
      <?php /*?><li style=" background:none;"> <?php echo $row->proposeddate; ?> for <?php echo $row->proposal_total_price; ?></li><?php */?><li style="background:none;" ><a href="index.php?option=com_camassistant&controller=rfp&task=reviewrfp&rfpid=<?php echo $row->id;  ?>&var=view&job=<?php echo $jobtype; ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?>">VIEW</a></li><li><a href="javascript:popup_proposal_summary(<?php echo $row->id; ?>);">DOWNLOAD </a></li>
	  <li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=copydraft&rfpid=<?php echo $row->id; ?>&job=<?php echo $jobtype; ?>&Itemid=<?php echo $Itemid; ?>">COPY TO DRAFT </a></li></ul>
	  <?PHP } else if ($row->rfp_type == 'Unawarded') {?>
	  <ul class="divid_list">  <?php /*?><li style=" background:none;"> Created  <?php echo $row->createdDate; ?></li><?php */?><li style="background:none;" ><a href="index.php?option=com_camassistant&controller=rfp&task=reviewrfp&rfpid=<?php echo $row->id;  ?>&var=view&job=<?php echo $jobtype; ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?>">VIEW</a></li><li><a href="javascript:popup_proposal_summary(<?php echo $row->id; ?>);">DOWNLOAD </a></li>
	  <li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=copydraft&rfpid=<?php echo $row->id; ?>&job=<?php echo $jobtype; ?>&Itemid=<?php echo $Itemid; ?>">COPY TO DRAFT </a></li></ul>
	  <?PHP } else if ($row->rfp_type == 'UNAWARDED') { ?>
	    <ul class="divid_list">  <?php /*?><li style=" background:none;"> Created  <?php echo $row->createdDate; ?></li><?php */?>
		<li style="background:none;" ><a href="index.php?option=com_camassistant&controller=rfp&task=reviewrfp&rfpid=<?php echo $row->id;  ?>&job=<?php echo $jobtype; ?>&var=view&Itemid=<?php echo $_REQUEST['Itemid']; ?>">VIEW</a></li>
		<li><a href="javascript:popup_proposal_summary(<?php echo $row->id; ?>);">DOWNLOAD </a></li>
		<li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=copydraft&rfpid=<?php echo $row->id; ?>&job=<?php echo $jobtype; ?>&Itemid=<?php echo $Itemid; ?>">COPY TO DRAFT </a></li></ul>
		<?php } ?>
    </td>
    </tr>
	<?php
		$k = 1 - $k;
		endforeach;
		if(count($this->RFP_list_by_Prp)==0) {
	?>
	<tr class="table_blue_rowdots">
   <td align="center" valign="middle" style="margin-top:10px; font-weight:bold;" colspan="5">You don't have any requests</td>
 </tr>
 <?PHP } ?>

 <tr class="table_blue_rowdo">
   <td align="left" valign="middle">&nbsp;</td>
   <td align="left" valign="top">&nbsp;</td>
   <td align="left" valign="top"></td>
 </tr>


</table>
<!--
<?php if($_REQUEST['viewall']!='all'){ ?>
<a href="index.php?option=com_camassistant&controller=sorting&task=sorting_rfps_by_property&viewall=all&Itemid=<?php echo $_REQUEST['Itemid'];?>&cid=<?php echo $_REQUEST['cid'];?>" ><img src="templates/camassistant_left/images/view_all.gif" border="0"/></a>
<?php } ?>
<?php if ($_REQUEST['viewall']=='all') { ?>
<a href="index.php?option=com_camassistant&controller=sorting&task=sorting_rfps_by_property&Itemid=<?php echo $_REQUEST['Itemid'];?>&cid=<?php echo $_REQUEST['cid'];?>" ><img src="templates/camassistant_left/images/back1.gif" border="0" /></a>
<?php }
?>
-->

</div>
</div>

<!-- eof table pan -->

</div>
<div style="float:right;">
<?php //echo $this->pagination->getPagesLinks(); ?>
	<?php //echo $this->pagination->getLimitBox(); ?>
	<?php //echo $this->pagination->getResultsCounter(); ?>
	</div>


<input type="hidden" value="" name="filter_order">
<input type="hidden" value="" name="filter_order_Dir">
<input type="hidden" value="0" name="limitstart">
<input type="hidden" value="0" name="viewcache">

</form>
<!--<div id="pagenation">
          <ul>
          <li><a href="#" class="active">1</a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">3</a></li>
          <li><a href="#">4</a></li>
          <li><a href="#">5</a></li>
          </ul>
         <p> Showing 1-15 of 74</p>
          <div class="clear"></div>-->
      </div>

         <?php unset($_SESSION['filter_Status']) ?>
		 <?php } ?>
