<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
// Your custom code here
//echo "<pre>"; print_r($this->details);
$Itemid = JRequest::getVar('Itemid',''); 
$phone = explode('-',$this->details->phone);
$altphone = explode('-',$this->details->cellphone);
$fax = explode('-',$this->details->fax);
$permissions = $this->client_permissions;
$pid = JRequest::getVar('id',''); 
$db =& JFactory::getDBO();
$bid = JRequest::getVar('bid','');
$query = "SELECT property_name from #__cam_property where id ='".$pid."'";
$db->setQuery($query);
$property_name = $db->loadResult();

$position = "SELECT board_position FROM #__cam_board_mem where id ='".$bid."'";
$db->setQuery($position);
$position = $db->loadResult();

?>
<script type="text/javascript" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>

<script type="text/javascript">
G = jQuery.noConflict();
function validate_data2()
{
 G("#VendorForm2").submit();

}
		
function cancel()
{
window.location="index.php?option=com_camassistant&controller=boardmembers&task=listboardmembers&Itemid=151";
}
</script>

<div class="acount_status">
<div class="ttl1">Acount Status</div>
<div class="newtopborder1"></div>
<div class="property_linkask">
<div class="client_linkask">
<label><img src="templates/camassistant_left/images/active_client.png">  </label>
<strong><span>This Client has an account </span></strong>
</div>
<div class="new_linkask">
<label><img src="templates/camassistant_left/images/active_linked.png"> </label>
<strong><span>Your accounts are Linked</span></strong>
</div>
</div>
 </div>
<div id="container_inner">
<div  style="margin-top:20px;">
 <div  class="ttl1">Client Information</div>
  <div class="newtopborder1"></div>
 </div>
<div class="clear"></div>
<?php //echo "<pre>"; print_r($this->details); ?>
<div id="signup-form">

<div class="signup">
<label style="margin-top:-12px;">Property:</label>
<span id="prop_list">
<input name="firstname" type="text" disabled="disabled" value="<?PHP echo str_replace('_',' ',$property_name)?>"/>
</span>
</div>
<div class="signup">
<label>Title:</label>
<select name="board_position"  disabled="disabled">
<option value="<?php echo $position;?>"><?php echo $position;?></option>

</select>
</div>
<div class="signup">
<label>Salutation:</label>
<select name="salutation"  disabled="disabled">
<option <?PHP if($this->details->salutation == 'Mr.'){?> selected="selected" <?PHP } ?>>Mr.</option>
<option <?PHP if($this->details->salutation == 'Mrs.') {?> selected="selected" <?PHP } ?>>Mrs.</option>
<option <?PHP if($this->details->salutation == 'Ms.') { ?> selected="selected" <?PHP } ?>>Ms.</option>
</select>
</div>

<div class="signup col_2">
<div class="state">
<label>First Name: </label>
<input name="firstname" type="text"   disabled="disabled" value="<?PHP echo $this->details->name?>"/>
</div>
<div class="zip">
<label>Last Name:</label>
<input name="lastname"   type="text"  disabled="disabled" value="<?PHP echo $this->details->lastname?>"/>
</div>
</div>
<div class="signup">
<label>Street Address:  </label>
<input name="streeaddress" type="text" disabled="disabled" value="<?PHP echo $this->details->steetaddress?>"/>
</div>
<div class="signup col_2">
<div class="state">
<label>State: </label>
<select name="state" id="stateid" disabled="disabled" onchange="javascript:county();" >
<option value="">Please Select State</option>
  <?php 
for ($i=0; $i<count($this->states); $i++){
$states = $this->states[$i];
?>

<option value="<?php echo $states->state_id?>" <?php if($states->state_id == $this->details->state) echo "selected";?>><?php echo $states->state_name?></option>
<?php } ?>
</select>
</div>
<div class="zip">
<label>Zip Code:</label>
<input name="zipcode" type="text" maxlength="5"  disabled="disabled" value="<?PHP echo $this->details->zipcode?>"/>
</div>
</div>

<div class="signup">
<label>Email: </label>

<input name="email" type="text" id="email"  disabled="disabled" value="<?PHP echo $this->details->email ?>" />

</div>
<div class="signup">
<label>Alt. Email:  </label>

<input name="altemail" type="text" id="altemail" disabled="disabled" value="<?PHP echo $this->details->altemail ?>" />

</div>

<div class="signup">
<div class="cp">
<label>Phone: </label>
<input id="phone_1" class="sm-input" name="phone_1" type="text" disabled="disabled"  value="<?PHP echo $phone[0]; ?>"  />
 <input id="phone_2" name="phone_2" type="text" disabled="disabled" class="sm-input" value="<?PHP echo $phone[1]; ?>" ); "/> - 
 <input id="phone_3" name="phone_3" type="text" disabled="disabled" class="sm-input" value="<?PHP echo $phone[2]; ?>" "/>
</div>

<div class="ext">
<label>Ext:</label>
<input name="extension" type="text" maxlength="4" disabled="disabled" class="sm-input" value="<?PHP echo $this->details->extension ?>"   /></div>
<div class="clear"></div>
</div>																			
<div class="signup">
<div class="cp">
<label>Alt. Phone: </label>
<input id="altphone_1" name="altphone_1" type="text" disabled="disabled" class="sm-input" value="<?PHP echo $altphone[0]; ?>" />
 <input id="altphone_2" name="altphone_2" type="text" disabled="disabled" class="sm-input" value="<?PHP echo $altphone[1]; ?>" "/> - 
 <input id="altphone_3" name="altphone_3" type="text" disabled="disabled" class="sm-input" value="<?PHP echo $altphone[2]; ?>"  "/>
</div>

<div class="ext">
<label>Ext:</label>
<input name="altextension" type="text" maxlength="4" disabled="disabled" class="sm-input" value="<?PHP echo $this->details->altphone_ext ?>"  /></div>
<div class="clear"></div>
</div>																			
<div class="signup">

<label>Fax:</label>
<input id="fax_1" name="fax_1" type="text" disabled="disabled" class="sm-input" value="<?PHP echo $fax[0]; ?>" />
 <input id="fax_2" name="fax_2" type="text" disabled="disabled" class="sm-input" value="<?PHP echo $fax[1]; ?>"  "/> - 
 <input id="fax_3" name="fax_3" type="text" disabled="disabled" class="sm-input" value="<?PHP echo $fax[2]; ?>"  "/>
</div>

<form enctype="multipart/form-data"  method="post" name="VendorForm2" id="VendorForm2">

<div class="clear"></div>
<div class="client_permissions">
<div class="inner_client-heading">
        <div class="ttl1">Client Permissions</div>
		<div class="newtopborderper"></div>
      </div><!-- inner_client-heading -->
  
          <div class="client_permission_block">
            <div><strong>Copied on Vendor proposals?</strong></div>
            <div>When you end a request, your client will receive an automatic email notification with a link to download a copy of the proposal report, which will contain every Vendor's submitted proposal.</div>
            <div>
			<?php if($permissions->proposals_p == '1'){ ?>
			<input type="radio" name="vendor_proposals" checked="checked" value="1"> <label>Yes</label> 
            <input type="radio" name="vendor_proposals"  value="0"> <label>No</label>
			<?php } else { ?>
			<input type="radio" name="vendor_proposals"  value="1"> <label>Yes</label> 
            <input type="radio" name="vendor_proposals" checked="checked" value="0"> <label>No</label>
			<?php }?>
			</div>
          </div><br/><!-- client_permission_block -->
          
          <div class="client_permission_block">
            <div><strong>Access to "My Vendor" list?</strong></div>
            <div>Your client will have "read-only" access to your "My Vendors" list or "Corporate Preferred Vendors" list (Master Account holders only). This allows them the ability to view contact information, compliance statuses, and more.  Note:  They will not be able to remove, add, or edit your list.</div>
            <div>
			<?php if($permissions->vendors_p == '1'){ ?>
			<input type="radio" name="myvendor_list" value="1" checked="checked" > <label>Yes</label> 
            <input type="radio" name="myvendor_list" value="0" > <label>No</label>
			<?php } else { ?>
			<input type="radio" name="myvendor_list" value="1"> <label>Yes</label> 
            <input type="radio" name="myvendor_list" value="0" checked="checked"> <label>No</label>
			
			<?php }?>
			</div><br/>
          </div><!-- client_permission_block -->
          
          <div class="client_permission_block">
            <div><strong>Ability to invite Vendors to requests?</strong></div>
            <div>Your Client will be able to invite Vendors to participate in requests that you submitted for this property only.  Note: They will not be able to uninvite vendors, send reminders, or end bidding.</div>
            <div>
			<?php if($permissions->invite_p == '1'){ ?>
			<input type="radio" name="invite_vendors" value="1" checked="checked"> <label>Yes</label> 
            <input type="radio" name="invite_vendors" value="0" > <label>No</label>
			<?php } else {?>
			<input type="radio" name="invite_vendors" value="1"> <label>Yes</label> 
            <input type="radio" name="invite_vendors" value="0" checked="checked"> <label>No</label>
			<?php }?>
			</div><br/>
          </div><!-- client_permission_block -->
          
          <div class="client_permission_block">
            <div><strong>Requires approval before submitting requests?</strong></div>
            <div>Your Client will be required to approve the submission of a request before it is delivered to Vendors. If a project is not approved, the Client will be able to submit feedback so your request may be revised and then resubmitted for approval.</div>
            <div>
			<?php if($permissions->approval_p == '1'){ ?>
			<input type="radio" name="approval_request" value="1" checked="checked"> <label>Yes</label> 
            <input type="radio" name="approval_request" value="0" > <label>No</label>
			<?php } else { ?>
			<input type="radio" name="approval_request" value="1" > <label>Yes</label> 
            <input type="radio" name="approval_request" value="0" checked="checked"> <label>No</label>
			<?php } ?>
			</div><br/>
          </div><!-- client_permission_block -->
          
          <div class="client_permission_block">
            <div><strong>Requires approval before awarding requests?</strong></div>
            <div>Your Client will be required to approve the awarding of a request to a Vendor before notifications are delivered to all participating Vendors.  If an award is not approved, the Client will be able to submit feedback so the awarding may be revised and then resubmitted for approval.</div>
            <div>
			<?php if($permissions->awarding_p == '1'){ ?>
			<input type="radio" name="approval_awarding" value="1" checked="checked"> <label>Yes</label> 
            <input type="radio" name="approval_awarding" value="0"  > <label>No</label>
			<?php } else {?>
			<input type="radio" name="approval_awarding" value="1"> <label>Yes</label> 
            <input type="radio" name="approval_awarding" value="0" checked="checked" > <label>No</label>
			<?php }?>
			</div><br/>
          </div><!-- client_permission_block -->
  

<div align="right" id="topborder_row1"></div>
<div class="checktextdetails">

<a  href="javascript:void(0)" class="manager_cancel" onclick="cancel()"></a>
<a  href="javascript:void(0)" class="manager_submit" onclick="javascript: return validate_data2();"></a>
 </div>
</div>




<div class="clear"></div>
</div>
<input type="hidden" value="com_camassistant" name="option" />
<input type="hidden" value="vendorscenter" name="controller" />
<input type="hidden" value="save_permissions" name="task" />
<input type="hidden" name="propertyowner_id" value="<?PHP echo $this->details->id; ?>"  />

</form>
</div> 
<div class="clear"></div>
</div>
