<?php
/**
 * @version		1.0.0 cam assistant $
 * @package		cam_assistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport( 'joomla.application.component.view' );

class camassistantViewInviteasinhouse extends Jview
{
	function display($tpl = null){ 
		// global $mainframe;
		$message = $this->get('inhousevendors');
		//echo '<pre>'; print_r($message);
		//$fei = $this->get('fei');
		//$res = str_replace("{XXXXXXXXX}", $fei, $res);
		$this->assignRef( 'tdata',$message);
		
$tags = array("<p>","</p>","<br>","<br />");
$rtags = array("","\n","\n","\n");
$msg = str_replace($tags, $rtags, $message);
//echo '<pre>'; print_r($msg);
		$this->assignRef( 'data',$msg);
		//$this->assignRef( 'fei',$fei);
		
		parent::display($tpl);

	}

}
?>