<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport( 'joomla.application.component.view' );

class vendorsacceptViewvendorsaccept extends Jview
{
	function display($tpl = null){

		// global $mainframe;
		$task = JRequest::getVar("task",'');
		
		if($task == 'vendorsaccept')
		{
			$document = & JFactory::getDocument();
			$document->setTitle( JText::_('Vendor Center') );			
			$model = $this->getModel('vendorsaccept');
			$prevendor	= $this->get('prevendor');
			$this->assignRef('prevendor',$prevendor);
			parent::display($tpl);
		}
		/*else if($task == 'not_authorized')
		{
			$this->setLayout('not_authorized'); 
			parent::display($tpl);
		} */
		else if($task=='vendorscenter_edit') 
		{
			$model  =$this->getModel('vendorscenter');
			$items  =& $this->get('vendor_edit');
			$this->assignRef('items',$items);
			$this->setLayout('vendor_editform'); 
			parent::display($tpl);
		} 

		else if($task=='unusercheck') {
		$model  =$this->getModel('vendorsaccept');
		$this->setLayout('usercheck');
		parent::display($tpl);
		}
		else if($task=='aregister') {
		$model  =$this->getModel('vendorsaccept');
		$this->setLayout('aregister');
		parent::display($tpl);
		}
		
		else //signup process 1
		{
		$model = $this->getModel('vendors');
		//$states = $model->getstates(); 
		$this->assignRef('states',$states);
		//$this->setLayout('company_info_form');
		parent::display($tpl);
		}

	}

}
?>