<link rel="stylesheet" media="all" type="text/css" href="<?php echo Juri::base(); ?>components/com_camassistant/skin1/css/jquery1.css" />		
<script type="text/javascript" src="components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="components/com_camassistant/skin/js/jquery-ui-1.8.6.custom.min.js"></script>
<script type="text/javascript" src="components/com_camassistant/skin/js/jquery-ui-timepicker-addon.js"></script>

<script>
K = jQuery.noConflict();

K(document).ready(function() {	
	var uname,pwd;
	K('#logibtnvendor').click(function(e) {
	 uname = document.login.username.value;
	 pwd = document.login.passwd.value;
	 document.logins.username.value=uname;
	 document.logins.passwd.value=pwd;
	 document.logins.submit();
	});
	
});
</script>

<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here
?>
<div id="container_inner"  style="padding-top: 10px;" >
<div id="">
<div id="dotshead" style="background:none; font-size:16px;" align="center">THANK YOU FOR CONFIRMING YOUR EMAIL ADDRESS!</div>
<div align="right" id="instructionsprint" style="padding:0 0 3px 2px;"></div>
<?php 
$db =& JFactory::getDBO();
$user =& JFactory::getUser();
$useractivation = JRequest::getVar("useractivation",'');
$usertype = "SELECT user_type FROM #__users where activation ='".$useractivation."'";
$db->setQuery($usertype);
$usertype = $db->loadResult();
if($usertype != '16')
{
	$linkmsg = "SELECT introtext  FROM #__content where id=106";
					$db->Setquery($linkmsg);
					$lmessage = $db->loadResult();
					echo $lmessage;
}
		?>			


<div class="clear"></div>
<div class="left-pan login-pan" align="center" style="padding-top:70px;">
<form action="" method="post" name="login" id="form-login">
 <input id="modlgn_username" type="text" name="username" alt="username"  tabindex="1" placeholder="E-Mail" onclick="if(this.placeholder == 'E-Mail') this.placeholder='';" onblur="if(this.placeholder == '') this.placeholder ='E-Mail';" />
<input id="modlgn_passwd" type="password" name="passwd" alt="password"  tabindex="2" placeholder="Password" onclick="if(this.placeholder == 'Password') this.placeholder='';" onblur="if(this.placeholder == '') this.placeholder ='Password';" onfocus="this.placeholder=''"/>
 <div class="clear"></div>
<div class="login"> <button type="submit" id="logibtnvendor" name="submit" tabindex="4"><img src="templates/camassistant/images/login.png" /></button></div>
<div class="or-bg"></div>
	<input type="hidden" name="option" value="com_user" />
	<input type="hidden" name="task" value="login" />
</form>
<div class="or-bg"></div>
</div>
</div>
</div>






