<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright � 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

JHTML::_('behavior.modal');

// Your custom code here
$vendor_GLI_compliance_alert = $this->vendor_GLI_compliance_alert;
$Itemid = JRequest::getVar('Itemid','');
$PLN_needed = $this->PLN_needed;
$Jobs 		= $this->Jobs;
$invitations 		= $this->Invitations;
$openjobs 		= $this->openjobs;
$personal_requests 		= $this->personalrequests;

 //echo '<pre>';print_r($invitations);exit;
$deccount_pre = 0;
	for($de=0; $de<count($invitations); $de++) {
		if($invitations[$de]['not_interested'] == '2') {
			$deccount_pre ++ ;
			//echo $deccount_pre;exit;
		}
	}
$uninvite_pre = 0;
	for($ue=0; $ue<count($invitations); $ue++) {
		if($invitations[$ue]['uninvited'] == 'uninvited') {
			$uninvite_pre ++ ;
			
		}
	}
	$open_pre = 0;
	for($op=0; $op<count($invitations); $op++) {
		if($invitations[$op]['create_rfptype'] == 'open') {
			$open_pre ++ ;
			
		}
	}

if( $invitations > 0  && $_COOKIE['invites_cookie'] != 'invites' && count($invitations) > $deccount_pre && count($invitations)>$uninvite_pre && count($invitations)>$open_pre )
{	?>
	<script type="text/javascript">
	el='<?php  echo Juri::base(); ?>index.php?option=com_camassistant&controller=vendors&task=popupinvitations';
	var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 550, y:300}}"))
	SqueezeBox.fromElement(el,options);
	</script>
	<?php }
?>


<script language="javascript" type="text/javascript">
L = jQuery.noConflict();

function ITB_save(rfpid) {

var formname = document.vendor_proposal_form;
L('body,html').animate({
scrollTop: 250
},800);
		//Cancel the link behavior
		//Get the A tag
		//Get the screen height and width
		var maskHeight = L(document).height();
		var maskWidth = L(window).width();

		//Set heigth and width to mask to fill up the whole screen
		L('#mask1').css({'width':maskWidth,'height':maskHeight});
		//transition effect
		L('#mask1').fadeIn(100);
		L('#mask1').fadeTo("slow",0.8);
		//Get the window height and width
		var winH = L(window).height();
		var winW = L(window).width();
		//Set the popup window to center
		//L("#submit1").css('top',  '250');
		//L("#submit1").css('left', '582');
		L("#submit1").css('top',  winH/2-L("#submit1").height()/2);
		L("#submit1").css('left', winW/2-L("#submit1").width()/2);
		
		L("#submit1").fadeIn(2000);

		L('.window1 #done1').click(function (e) {
		var frm = document.vendor_proposal_form+rfpid;
		
		var con_name= document.getElementById('con_name_this_project').value;
		document.getElementById('contact_name_'+rfpid).value= con_name;
		if(con_name==''){
		alert('Please Enter Contact Name For This Project');
		} else {
		L('#mask1').hide();
		L('.window1').hide();
		e.preventDefault();
		L('#proposal_form_'+rfpid).submit();
		}
		//window.location = "index.php?option=com_camassistant&controller=rfp&task=editrfp&rfpid="+id+"&Itemid=87"
	});
		L('.window1 #close1').click(function (e) {
		//Cancel the link behavior
		e.preventDefault();
		L('#mask1').hide();
		L('.window1').hide();
	});
}

/*L(document).ready(function() {
	//if close button is clicked
	L('.window1 #close1').click(function (e) {
		//Cancel the link behavior
		e.preventDefault();
		L('#mask1').hide();
		L('.window1').hide();
	});
	//if done button is clicked
	L('.window1 #done1').click(function (e) {
		//Cancel the link behavior
		setTimeout("ITB_save()",10);
		e.preventDefault();
		L('#mask1').hide();
		L('.window1').hide();

	});
});*/
//setTimeout("ITB_save()",10);
</script>
 <style>
#mask1 {  position:absolute;  left:0;  top:0;  z-index:9000;  background-color:#000;  display:none;}
#boxes1 .window1 {  position:absolute;  left:0;  top:0;  width:350px;  height:150px;  display:none;  z-index:9999;  padding:20px;}
#boxes1 #submit1 {  width:360px;  height:235px;  padding:10px;  background-color:#ffffff;}
#boxes1 #submit1 a{ text-decoration:none; color:#000000; font-weight:bold; font-size:20px;}
#close1 {border:0 none;cursor:pointer;height:30px;margin:0;padding:0;float:left;width:160px;}
#done1 {border:0 none;cursor:pointer;height:30px;margin:0;padding:0; color:#000000; font-weight:bold; font-size:20px;}
</style>

<script type="text/javascript">
	G = jQuery.noConflict();
	G(document).ready( function(){
<?php 

if( $this->expireddocs > '0' && $_COOKIE['test_cookie'] != 'test' && $_COOKIE['nonc_cookie'] != 'nonc' ) { ?>
		G('#compliancedocs_vendors').after('<span class="warning_compliance"><?php echo "<strong>WARNING: ".$this->expireddocs."</strong> Expired Document(s)"; ?><span class="warning_close"></span></span>');
<?php } else {?>
		//G('.warning_compliance').addClass('hide');
<?php } ?>
<?php 
if( $this->noncompanies > '0' && $_COOKIE['nonc_cookie'] != 'nonc' && $_COOKIE['test_cookie'] != 'test' ) { ?>
		G('#myclients_vendors').after('<span class="warning_nonc"><?php echo "<strong>WARNING</strong>: Non-Compliant with <strong>".$this->noncompanies."</strong> Clients"; ?><span class="warning_close_nonc"></span></span>');
<?php } else {?>
		//G('.warning_nonc').addClass('hide');
<?php } ?>

		L('#declineinvitation').live('click' ,function (){
		rfpid = L('#declineinvitation').attr('rel');
		el='<?php  echo Juri::base(); ?>index.php?option=com_camassistant&controller=proposals&task=reasondecline&rfpid='+rfpid;
		var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 600, y:410}}"))
		SqueezeBox.fromElement(el,options);
	});
	
	});
</script>	

<script type="text/javascript">
G = jQuery.noConflict();
G(document).ready( function(){
	G('.codeinfo_open').click(function(){
		rfpid = G(this).attr('data');
		propertyid = G(this).attr('rel');
		if(!G(this).hasClass("active")){
			getrfpdata(rfpid,propertyid);
			G('.codeinfo_open').removeClass('active');
			G(this).addClass('active');
		}
		else{
			G('#codedetails_'+rfpid).slideUp('slow').html('');
			G('.table_blue_rowdots_submitted').removeClass('active');
			G(this).removeClass('active');
			G('.codeinfo_drafts').removeClass('active');
		}
	});
	
	G('.codeinfo_drafts').click(function(){
		rfpid = G(this).attr('data');
		var res = rfpid.split("_"); 
		rfpid = res[0];
		proposalid = res[1];
		propertyid = G(this).attr('rel');
		if(!G(this).hasClass("active")){
			getrfpdata_drafts(rfpid,propertyid,proposalid,res[2]);
			G('.codeinfo_drafts').removeClass('active');
			G(this).addClass('active');
		}
		else{
			G('#codedetails_'+proposalid).slideUp('slow').html('');
			G('.table_blue_rowdots_submitted').removeClass('active');
			G(this).removeClass('active');
			G('.codeinfo_open').removeClass('active');
		}
	});
	
	G('.warning_close').click(function(){
		G('.warning_compliance').addClass('hide');
		<?php
		setcookie("test_cookie", "test");
		?>
	});
	G('.warning_close_nonc').click(function(){
		G('.warning_nonc').addClass('hide');
		<?php
		setcookie("nonc_cookie", "nonc");
		?>
	});
	
});

function getrfpdata_drafts(rfpid,propertyid,proposalid,type){
	G.post("index2.php?option=com_camassistant&controller=vendors&task=getinvitationdetails", {rfp: ""+rfpid+"", propertyid: ""+propertyid+"", proposalid: ""+proposalid+"", type: ""+type+""}, function(data){
	if(data) {
		G('#codedetails_'+proposalid).removeClass('loader');
		G('.prop_details').slideUp();
		G('.table_blue_rowdots_submitted').removeClass('active');
		G('#table_blue_rowdots'+rfpid).addClass('active');
		G('#codedetails_'+proposalid).html(data).slideDown('slow');
		G('#codedetails_'+proposalid).show();
	}
	else{
		G('#codedetails_'+proposalid).removeClass('loader');
		G('#codedetails_'+proposalid).html("No data for this RFP");
	}
	});
}

function getrfpdata(rfpid,propertyid){
	G.post("index2.php?option=com_camassistant&controller=vendors&task=getinvitationdetails", {rfp: ""+rfpid+"", propertyid: ""+propertyid+""}, function(data){
	if(data) {
		G('#codedetails_'+rfpid).removeClass('loader');
		G('.prop_details').slideUp();
		G('.table_blue_rowdots_submitted').removeClass('active');
		G('#table_blue_rowdots'+rfpid).addClass('active');
		G('#codedetails_'+rfpid).html(data).slideDown('slow');
		G('#codedetails_'+rfpid).show();
	}
	else{
		G('#codedetails_'+rfpid).removeClass('loader');
		G('#codedetails_'+rfpid).html("No data for this RFP");
	}
	});
}
</script>


<?php
$user =& JFactory::getUser();
if($user->user_type != 11)
{ ?>
<div align="center" style="color:#0066FF; font-size:15px"> You must be logged in to view this page.  Please log in to check available jobs.</div>
<?php } else { ?>
<!-- sof bedcrumb -->
<div id="bedcrumb" style="display:none;" >
<ul>
<li class="home"><a href="#">Home</a> </li>
<li><a href="#">My Dashboard</a> </li>

</ul>
</div>
  <!-- eof bedcrumb -->
<?php 
$db = JFactory::getDBO();


if(!$user->id){
echo "<span class='blueheads'>You need to login to access this page</span>";
}
else {
 	$name = $user->get('name');
	$lname = $user->get('lastname');
	$username = $name.'&nbsp;'.$lname;
}
?>
  <p class="blueheads"><?php //echo $username; ?> </p>
  <br />
<br />
<!-- sof dotshead -->
<!-- sof table pan -->
<div class="clear"></div>  <br />


<?PHP
	$deccount_pre = 0;
	for($de=0; $de<count($invitations); $de++) {
		if($invitations[$de]['not_interested'] == '2') {
			$deccount_pre ++ ;
		}
	}
?>
<div id="i_bar" style="background:#77b800;">
<div id="i_bar_txt">
<span><strong> NEW PROJECTS: Personally Invited </strong></span>
</div>
<div id="i_icon001"><a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=109&amp;Itemid=113"><img style="margin-top:6px;" src="templates/camassistant_left/images/info_icon2.png"> </a></div>
</div>

<div class="table_pannel">
<div class="table_panneldiv">
<table width="100%" cellpadding="0" cellspacing="4" class="vendortable">
<?PHP if(count($invitations)>0 && count($invitations) > $deccount_pre ) { ?>
    <tr class="vendorfirsttr">
	<td></td>
	<td width="30%" align="center" valign="middle">PROPERTY</td>
    <td width="33%" align="center" valign="middle">PROJECT NAME</td>
    <td width="15%" align="center" valign="middle">COUNTY</td>
    <td width="25%" align="center" valign="middle">REQUESTED DUE DATE</td>
   <!-- <td width="16%" align="center" valign="middle">TIME LEFT</td>-->
    <?php /*?><td width="19%" align="center" valign="middle">OPTIONS</td><?php */?>
  </tr>
  <?php //echo "<pre>"; print_r($invitations); echo "</pre>"; ?>
  
  <?PHP 
  if($personal_requests)
	{ 
		for($p=0; $p<count($personal_requests); $p++) {
		$all_vendors[] = $personal_requests[$p]->rfpid;
	  }
	}
	else
	$all_vendors[] = '';
 
  
  	$deccount = 0;
  for($d=0; $d<count($invitations); $d++) {
  
  $previous_date = $invitations[$d]['pro_date'];
  $previous_date = explode('-',$previous_date); 
  $previous_date = $previous_date[2].'-'.$previous_date[0].'-'.$previous_date[1];
	
  
	
	if(in_array( $invitations[$d]['rfp_id'],$all_vendors) || $previous_date < date('Y-m-d') )	{	
  			if($invitations[$d]['not_interested'] != '2' && $invitations[$d]['create_rfptype'] != 'open') {
  		$subject = $Jobs[$d]['time_left'];
		$pattern = '|-|';
		preg_match($pattern, substr($subject,0), $matches, PREG_OFFSET_CAPTURE);
		$cnt = count($matches);
   if($invitations[$d]['not_interested'] == '1') {?>
  <tr class="table_blue_rowdots_submitted" style="color:#808080;" color="#808080">
  <?php } else { ?>
   <tr class="table_blue_rowdots_submitted">
  <?php } ?>
  <td align="center" valign="middle" width="15">
	<a id="getcodeinfo_<?php echo $invitations[$d]['rfp_id']; ?>" class="codeinfo_open" data="<?php echo $invitations[$d]['rfp_id']; ?>" rel="<?php echo $invitations[$d]['property_id']; ?>" href="javascript:void(0);"></a>
	</td>
	<td width="30%" align="center" valign="middle"><?PHP echo str_replace('_',' ',$invitations[$d]['Propertyname']);  ?></td>
    <td width="33%" align="center" valign="middle"><?PHP  echo $invitations[$d]['projectName']; //echo $Drafts[$d]->Prperty_id;  ?></td>
    <td width="15%" align="center" valign="middle">
	<?PHP if($invitations[$d]['County']) echo $invitations[$d]['County'];
		  else echo $invitations[$d]['City'];
		  	
	  ?>
	</td>
	 <?php $main = $invitations[$d]['proposalDueDate'];
  if($main != '0000-00-00'){
    $main = explode('-',$main);
	$date = $main[0].'-'.$main[1].'-'.$main[2];
	}
	else{
	$date = '00-00-0000';
	}

   ?>
    <td width="25%" align="center" valign="middle"><?PHP echo $date;  ?></td>

    <?php /*?><td width="19%" align="center" valign="middle"><strong><?php
	if( $invitations[$d]['uninvited'] != 'uninvited' ){
	 if($invitations[$d]['not_interested'] == '2') { echo "DECLINED<br />"; ?></strong>
	<a href="index.php?option=com_camassistant&controller=proposals&task=vendor_proposal_form&view=proposals&Prp_id=<?PHP echo $invitations[$d]['prp_id'];  ?>&rfp_id=<?PHP echo $invitations[$d]['rfp_id'];  ?>&not_interested=<?PHP echo $invitations[$d]['not_interested'];  ?>&type=invitation&id=<?PHP echo $invitations[$d]['id']; ?>&type=invitation&jobtype=<?php echo $invitations[$d]['jobtype']?>&Itemid=<?PHP echo $Itemid; ?>">Respond to Invite</a>
	<?php } else {?>
	<a href="index.php?option=com_camassistant&controller=proposals&task=vendor_proposal_form&view=proposals&Prp_id=<?PHP echo $invitations[$d]['prp_id'];  ?>&rfp_id=<?PHP echo $invitations[$d]['rfp_id'];  ?>&not_interested=<?PHP echo $invitations[$d]['not_interested'];  ?>&type=invitation&id=<?PHP echo $invitations[$d]['id']; ?>&type=invitation&jobtype=<?php echo $invitations[$d]['jobtype']?>&Itemid=<?PHP echo $Itemid; ?>">Respond to Invite</a>
	<?php } } else { 
	echo '<a class="uninitetext_vendor" href="javascript:void(0);" onclick="getshowmessage('.$invitations[$d]['rfp_id'].');">UNINVITED</a>';
	
	}
	?>
	
	</td><?php */?>
  </tr>
  <tr><td colspan="5"><div id="codedetails_<?php echo $invitations[$d]['rfp_id']; ?>" class="prop_details" ></div></td></tr>
  <?PHP 
  		 }
		 else {
		 	$deccount ++;
		 }
		  }
		
		  }
		  	}
  if(count($invitations)<=0 || count($invitations) == $deccount_pre )
 { ?>
 <tr>
    <td colspan="5"  align="center" valign="top"><p style="margin-bottom:10px; margin-top:10px;">You have not received any project invitations</p></td>
  </tr>
  <?PHP } ?>
 </table>
<div class="clear"></div>
</div>
</div>
<BR  />



<?PHP
	$deccount_pre_open = 0;
	for($oj=0; $oj<count($openjobs); $oj++) {
		if($openjobs[$oj]['not_interested'] == '2') {
			$deccount_pre_open ++ ;
		}
	}
?>
<div id="i_bar" style="background:#77b800;">
<div id="i_bar_txt">
<span><strong>NEW PROJECTS: Open Invite</strong></span>
</div>
<div id="i_icon001"><a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=109&amp;Itemid=113"><img style="margin-top:6px;" src="templates/camassistant_left/images/info_icon2.png"> </a></div>
</div>
<div class="table_pannel">
<div class="table_panneldiv">
<table width="100%" cellpadding="0" cellspacing="4" class="vendortable">
<?PHP
//echo '<pre>';print_r($openjobs);exit;
 if(count($openjobs)>0 && count($openjobs) > $deccount_pre_open ) { ?>
    <tr class="vendorfirsttr">
	<td></td>
	<td width="30%" align="center" valign="middle">PROPERTY</td>
    <td width="33%" align="center" valign="middle">PROJECT NAME</td>
    <td width="15%" align="center" valign="middle">COUNTY</td>
    <td width="25%" align="center" valign="middle">REQUESTED DUE DATE</td>
   <!-- <td width="16%" align="center" valign="middle">TIME LEFT</td>-->
    <?php /*?><td width="19%" align="center" valign="middle">OPTIONS</td><?php */?>
  </tr>
  <?php //echo "<pre>"; print_r($openjobs); echo "</pre>"; ?>
  
  <?PHP 
	if($personal_requests)
	{ 
		for($p=0; $p<count($personal_requests); $p++) {
		$all_vendors[] = $personal_requests[$p]->rfpid;
	  }
	}
	else
	$all_vendors[] = '';
	$deccount = 0;
  for($d=0; $d<count($openjobs); $d++) {
   $previous_date = $openjobs[$d]['pro_date'];
  $previous_date = explode('-',$previous_date); 
  $previous_date = $previous_date[2].'-'.$previous_date[0].'-'.$previous_date[1];
  	
  
  
  	if(!in_array( $openjobs[$d]['rfp_id'],$all_vendors) || $previous_date < date('Y-m-d') )	{	
  			
  			if($openjobs[$d]['not_interested'] != '2') {
  		$subject = $Jobs[$d]['time_left'];
		$pattern = '|-|';
		preg_match($pattern, substr($subject,0), $matches, PREG_OFFSET_CAPTURE);
		$cnt = count($matches);
   if($openjobs[$d]['not_interested'] == '1') {?>
  <tr class="table_blue_rowdots_submitted" style="color:#808080;" color="#808080">
  <?php } else { ?>
   <tr class="table_blue_rowdots_submitted">
  <?php } ?>
  <td align="center" valign="middle" width="15">
	<a id="getcodeinfo_<?php echo $openjobs[$d]['rfp_id']; ?>" class="codeinfo_open" data="<?php echo $openjobs[$d]['rfp_id']; ?>" rel="<?php echo $openjobs[$d]['property_id']; ?>" href="javascript:void(0);"></a>
	</td>
	<?php  
	if ( $openjobs[$d]['block_status'] == 'blockvendor' ) {
	$propertyname = '<a href= "javascript:void(0);" onclick="getblockmessage('.$openjobs[$d]['block_unv'].','.$openjobs[$d]['block_comp'].');"> Blocked</a>';
	$projectname = '<a href= "javascript:void(0);" onclick="getblockmessage('.$openjobs[$d]['block_unv'].','.$openjobs[$d]['block_comp'].');"> Blocked</a>';
	}
	else
	{
	$propertyname = str_replace('_',' ',$openjobs[$d]['Propertyname']);
	$projectname = $openjobs[$d]['projectName'];
	}
	 ?>
	<td width="30%" align="center" valign="middle"><?PHP echo $propertyname;  ?></td>
    <td width="33%" align="center" valign="middle"><?PHP  echo $projectname; //echo $Drafts[$d]->Prperty_id;  ?></td>
    <td width="15%" align="center" valign="middle">
	<?PHP if($openjobs[$d]['County']) echo $openjobs[$d]['County'];
		  else echo $openjobs[$d]['City'];
		  	
	  ?>
	</td>
	 <?php $main = $openjobs[$d]['proposalDueDate'];
  if($main != '0000-00-00'){
    $main = explode('-',$main);
	$date = $main[0].'-'.$main[1].'-'.$main[2];
	}
	else{
	$date = '00-00-0000';
	}

   ?>
    <td width="25%" align="center" valign="middle"><?PHP echo $date;  ?></td>
  </tr>
  <tr><td colspan="5"><div id="codedetails_<?php echo $openjobs[$d]['rfp_id']; ?>" class="prop_details" ></div></td></tr>
  <?PHP 
  		 }
		 else {
		 	$deccount ++;
		 }
		  } 
		  }
		 
		  	}
  if(count($openjobs)<=0 || count($openjobs) == $deccount_pre_open )
 { ?>
 <tr>
    <td colspan="5"  align="center" valign="top"><p style="margin-bottom:10px; margin-top:10px;">There are no open projects at this time</p></td>
  </tr>
  <?PHP } ?>
 </table>
<div class="clear"></div>
</div>
</div>
<br />
<!-- Completed -->
<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
$Itemid = JRequest::getVar('Itemid','');
$Drafts 		= $this->prp_Draft_summary;
$Submits 		= $this->prp_Submitted_summary;
JHTML::_('behavior.modal');
//echo "<pre>"; print_r($Submits);
// Your custom code here
?>
<script type="text/javascript">
G = jQuery.noConflict();
function getshowmessage(rfpid){
	el='<?php  echo Juri::base(); ?>index.php?option=com_camassistant&controller=vendors&task=showuninitedmsg&rfpid='+rfpid;
	var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 672, y:250}}"))
	SqueezeBox.fromElement(el,options);
}
function getblockmessage(un,noncom){

if(un == 1 && noncom != 1 )
 onlyunverifiedblock();
else if(un !=1 && noncom == 1)
onlycomplianceblock();
else 
bothcomplianceblock();
}



function onlyunverifiedblock()
{
 var maskHeight = G(document).height();
		var maskWidth = G(window).width();
		G('#maskexu').css({'width':maskWidth,'height':maskHeight});
		G('#maskexu').fadeIn(100);
		G('#maskexu').fadeTo("slow",0.8);
		var winH = G(window).height();
		var winW = G(window).width();
		G("#submitexu").css('top',  winH/2-G("#submitexu").height()/2);
		G("#submitexu").css('left', winW/2-G("#submitexu").width()/2);
		G("#submitexu").fadeIn(2000);
		
		G('.windowexu #cancelexu').click(function (e) {
		e.preventDefault();
		G('#maskexu').hide();
		G('.windowexu').hide();
		});
} 

function onlycomplianceblock()
{
 var maskHeight = G(document).height();
		var maskWidth = G(window).width();
		G('#maskexc').css({'width':maskWidth,'height':maskHeight});
		G('#maskexc').fadeIn(100);
		G('#maskexc').fadeTo("slow",0.8);
		var winH = G(window).height();
		var winW = G(window).width();
		G("#submitexc").css('top',  winH/2-G("#submitexc").height()/2);
		G("#submitexc").css('left', winW/2-G("#submitexc").width()/2);
		G("#submitexc").fadeIn(2000);
		
		G('.windowexc #cancelexc').click(function (e) {
		e.preventDefault();
		G('#maskexc').hide();
		G('.windowexc').hide();
		});
}   
function bothcomplianceblock()
{
 var maskHeight = G(document).height();
		var maskWidth = G(window).width();
		G('#maskex').css({'width':maskWidth,'height':maskHeight});
		G('#maskex').fadeIn(100);
		G('#maskex').fadeTo("slow",0.8);
		var winH = G(window).height();
		var winW = G(window).width();
		G("#submitex").css('top',  winH/2-G("#submitex").height()/2);
		G("#submitex").css('left', winW/2-G("#submitex").width()/2);
		G("#submitex").fadeIn(2000);
		
		G('.windowex #cancelex').click(function (e) {
		e.preventDefault();
		G('#maskex').hide();
		G('.windowex').hide();
		});
}     

function deleteproposal(rfpid,proposalid,altbid){
		G('.rfpid').val(rfpid);
		G('.proposalid').val(proposalid);
		G('.altbid').val(altbid);
		
		var maskHeight = G(document).height();
		var maskWidth = G(window).width();
		G('#maskdp').css({'width':maskWidth,'height':maskHeight});
		G('#maskdp').fadeIn(100);
		G('#maskdp').fadeTo("slow",0.8);
		var winH = G(window).height();
		var winW = G(window).width();
		G("#submitdp").css('top',  winH/2-G("#submitdp").height()/2);
		G("#submitdp").css('left', winW/2-G("#submitdp").width()/2);
		G("#submitdp").fadeIn(2000);
		G('.windowdp #donedp').click(function (e) {
		G('#deleteproposalform').submit();
		e.preventDefault();
		G('#maskdp').hide();
		G('.windowdp').hide();
		});
		G('.windowdp #canceldp').click(function (e) {
		e.preventDefault();
		G('#maskdp').hide();
		G('.windowdp').hide();
		});
		
	
}
</script>
<style>
#maskdp { position:absolute;  left:0;  top:0;  z-index:9000;  background-color:#000;  display:none;}
#boxesdp .windowdp {  position:absolute;  left:0;  top:0;  width:350px;  height:150px;  display:none;  z-index:9999;  padding:20px;}
#boxesdp #submitdp {  width:580px;  height:270px;  padding:10px;  background-color:#ffffff;}
#boxesdp #submitdp a{ text-decoration:none; color:#000000; font-weight:bold; font-size:20px;}
#donedp {border:0 none;cursor:pointer;padding:0; color:#000000; font-weight:bold; font-size:20px; margin:0 auto; margin-top:6px;}
#closedp {border:0 none;cursor:pointer;height:30px;margin-left:59px;padding:0;float:left;}

#maskex { position:absolute;  left:0;  top:0;  z-index:9000;  background-color:#000;  display:none;}
#boxesex .windowex {  position:absolute;  left:0;  top:0;  width:350px;  height:150px;  display:none;  z-index:9999;  padding:20px;}
#boxesex #submitex {  width:508px;  height:244px;  padding:10px;  background-color:#ffffff;}
#boxesex #submitex a{ text-decoration:none; color:#000000; font-weight:bold; font-size:20px;}
#doneex {border:0 none;cursor:pointer;padding:0; color:#000000; font-weight:bold; font-size:20px; margin:0 auto; margin-top:6px;}
#closeex {border:0 none;cursor:pointer;height:30px;margin-left:59px;padding:0;float:left;}

#maskexu { position:absolute;  left:0;  top:0;  z-index:9000;  background-color:#000;  display:none;}
#boxesexu .windowexu {  position:absolute;  left:0;  top:0;  width:350px;  height:150px;  display:none;  z-index:9999;  padding:20px;}
#boxesexu #submitexu {  width:508px;  height:244px;  padding:10px;  background-color:#ffffff;}
#boxesexu #submitexu a{ text-decoration:none; color:#000000; font-weight:bold; font-size:20px;}
#doneexu {border:0 none;cursor:pointer;padding:0; color:#000000; font-weight:bold; font-size:20px; margin:0 auto; margin-top:6px;}
#closeexu {border:0 none;cursor:pointer;height:30px;margin-left:59px;padding:0;float:left;}

#maskexc { position:absolute;  left:0;  top:0;  z-index:9000;  background-color:#000;  display:none;}
#boxesexc .windowexc {  position:absolute;  left:0;  top:0;  width:350px;  height:150px;  display:none;  z-index:9999;  padding:20px;}
#boxesexc #submitexc {  width:508px;  height:244px;  padding:10px;  background-color:#ffffff;}
#boxesexc #submitexc a{ text-decoration:none; color:#000000; font-weight:bold; font-size:20px;}
#doneexc {border:0 none;cursor:pointer;padding:0; color:#000000; font-weight:bold; font-size:20px; margin:0 auto; margin-top:6px;}
#closeexc {border:0 none;cursor:pointer;height:30px;margin-left:59px;padding:0;float:left;}
</style>
<?php
$user =& JFactory::getUser();
if($user->user_type != 11)
{ ?>
<div align="center" style="color:#0066FF; font-size:15px"> You are not authorized to view this page.</div>
<?php } else { ?>
<?PHP
$act = JRequest::getVar('act','');
$rfp_id = JRequest::getVar('rfp_id','');
$Proposal_id = JRequest::getVar('Proposal_id','');
if($act == 'ITB' && $rfp_id !='' &&  $Proposal_id != '') {
 ?>

<script type="text/javascript" src="components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>


<!--<body onload="javascript: ITB_save();"></body>-->

 
<?PHP } ?>

<!-- sof bedcrumb -->

<!-- eof bedcrumb -->

<!-- sof dotshead -->

<!-- eof dotshead -->

<!-- sof table pan -->
<?php //echo '<pre>'; print_r($Drafts); echo "</pre>";?>
<br>
<div id="i_bar">
<div id="i_bar_txt"><span><strong>UNSUBMITTED PROPOSALS</strong></span></div>
<div id="i_icon"><a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=86&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png"> </a></div>
</div>
<div class="table_pannel">
<div class="table_panneldiv">
<table width="100%" cellpadding="0" cellspacing="4" class="vendortable">
	<?PHP if(count($Drafts)>0) { ?>
    <tr class="vendorfirsttr">
	<td></td>
    <td width="30%" align="center" valign="middle">PROPERTY</td>
    <td width="33%" align="center" valign="middle">PROJECT NAME</td>
    <td width="15%" align="center" valign="middle">COUNTY</td>
    <td width="25%" align="center" valign="middle">REQUESTED DUE DATE</td>
  </tr>
  <?PHP for($d=0; $d<count($Drafts); $d++) {
    $subject = $Drafts[$d]->time_left;
	$pattern = '|-|';
	preg_match($pattern, substr($subject,0), $matches, PREG_OFFSET_CAPTURE);
	$cnt = count($matches); ?>
    <?php //echo '<pre>'; print_r($Drafts[$d]); ?>
      <?php  if($Drafts[$d]->publish=='2') { ?>
  <tr class="table_blue_rowdots" style="color:red;">
 <td  width="8%" align="center" valign="top" ><?PHP //echo sprintf('%06d', $Drafts[$d]->rfp_id); //echo $Drafts[$d]->rfp_id; ?></td>
 <td width="33%" align="center" valign="top" ><?PHP  echo $Drafts[$d]->projectName; if($Drafts[$d]->Alt_bid == 'yes') echo '-ALT';  //echo $Drafts[$d]->Prperty_id;?></td>
 		<?php
		$sql = "SELECT County FROM #__cam_counties WHERE id = ".$Drafts[$d]->divcounty;
		$db->Setquery($sql);
		$county = $db->loadResult();
		?>
    <td width="15%" align="center" valign="top" ><?PHP echo $Drafts[$d]->city;  ?></td>
     <?php $main = $Drafts[$d]->proposalDueDate;
     $main1 = explode('-',$main);
     $maindate= $main1[2].'-'.$main1[0].'-'.$main1[1];
     $today=date('Y-m-d');
  if($main != '0000-00-00'){
    $main = explode('-',$main);
	$date = $main[0].'-'.$main[1].'-'.$main[2];
	/*$main = explode('-',$main);
	$date = $main[2].'-'.$main[0].'-'.$main[1];
	$newdate = strtotime ( '-1 day' , strtotime ( $date ) ) ;
	$date = date ( 'm-d-Y' , $newdate );*/
	}
	else{
	$date = '00-00-0000';
	}

   ?>
    <td width="25%" align="center" valign="middle" >
	<?PHP if($maindate < $today && $Drafts[$d]->rfp_type!= 'closed' && $Drafts[$d]->rfp_type!= 'Unawarded' && $Drafts[$d]->rfp_type!= 'Awarded') { ?><span style="color:orange; font-weight:bold;">OVERDUE</span><br/><?php } ?>
	<?PHP if($Drafts[$d]->rfp_type== 'closed' || $Drafts[$d]->rfp_type== 'Unawarded' || $Drafts[$d]->rfp_type== 'Awarded') { ?><span style="color:red;font-weight:bold;">CLOSED</span><br/><?php } ?>
	<?PHP echo $date;  ?></td>
	<?php if($Drafts[$d]->proposaltype != 'uninvited' ){ ?>
    <td align="center" valign="middle" width="19%" >
	<a href="index.php?option=com_camassistant&controller=proposals&task=vendor_proposal_preview&Alt_Prp=<?PHP echo $Drafts[$d]->Alt_bid; ?>&Proposal_id=<?PHP echo $Drafts[$d]->id;?>&vendor_id=<?PHP echo $Drafts[$d]->proposedvendorid;?>&rfp_id=<?PHP echo $Drafts[$d]->rfp_id;?>&jobtype=<?PHP echo $Drafts[$d]->jobtype; ?>&pagefrom=draftstatus&action=view&Itemid=107">VIEW</a>
	<img src="templates/camassistant_left/images/links_devider.gif" alt="liks devider" hspace="8" />
	<?PHP if($Drafts[$d]->rfp_type!= 'closed' && $Drafts[$d]->rfp_type!= 'Unawarded' && $Drafts[$d]->rfp_type!= 'Awarded') { ?><a href="index.php?option=com_camassistant&controller=proposals&Alt_Prp=<?PHP echo $Drafts[$d]->Alt_bid;?>&task=Proposal_edit&Proposal_id=<?PHP echo $Drafts[$d]->id;?>&vendor_id=<?PHP echo $Drafts[$d]->proposedvendorid;?>&rfp_id=<?PHP echo $Drafts[$d]->rfp_id;?>&act=Draft&reject=<?PHP echo $Drafts[$d]->publish; ?>&jobtype=<?PHP echo $Drafts[$d]->jobtype; ?>&Itemid=107">EDIT</a><?PHP }   ?>  </td>
	<?php } else { ?>
	<td align="center" valign="middle" width="19%" >
	<a class="uninitetext_vendor" href="javascript:void(0);" onclick="getshowmessage(<?php echo $Drafts[$d]->rfp_id ; ?>);">UNINVITED</a>
	</td>
	<?php } ?>
	
  </tr>
  <tr style="color:red;"><td colspan="5">Returned to DRAFT status by CAMassistant Review Process. Please call 561-246-3830 for assistance.</td></tr>
  <?php } else { ?>
  <tr class="table_blue_rowdots_submitted">
  <td align="center" valign="middle" width="15">
	<a id="getcodeinfo_<?php echo $Drafts[$d]->rfp_id; ?>" class="codeinfo_drafts" data="<?php echo $Drafts[$d]->rfp_id; ?>_<?php echo $Drafts[$d]->id; ?>_drafts" rel="<?php echo $Drafts[$d]->property_id; ?>" href="javascript:void(0);"></a>
	</td>
 <td width="30%" align="center" valign="middle" ><?PHP echo str_replace('_',' ',$Drafts[$d]->property_name); //echo $Drafts[$d]->rfp_id; ?></td>
 <td width="33%" align="center" valign="middle" ><?PHP echo $Drafts[$d]->projectName; if($Drafts[$d]->Alt_bid == 'yes') echo '-ALT';  //echo $Drafts[$d]->Prperty_id;?></td>
 		<?php
		$sql = "SELECT County FROM #__cam_counties WHERE id = ".$Drafts[$d]->divcounty;
		$db->Setquery($sql);
		$county = $db->loadResult();
		?>
    <td align="center" valign="middle" width="15%" ><?PHP echo $county;  ?></td>
     <?php $main = $Drafts[$d]->proposalDueDate;
       $main1 = explode('-',$main);
     $maindate= $main1[2].'-'.$main1[0].'-'.$main1[1];
     $today=date('Y-m-d');
  if($main != '0000-00-00'){
    $main = explode('-',$main);
	$date = $main[0].'-'.$main[1].'-'.$main[2];
	/*$main = explode('-',$main);
	$date = $main[2].'-'.$main[0].'-'.$main[1];
	$newdate = strtotime ( '-1 day' , strtotime ( $date ) ) ;
	$date = date ( 'm-d-Y' , $newdate );*/
	}
	else{
	$date = '00-00-0000';
	}

 //echo '<pre>'; print_r($Drafts[$d]); echo $maindate; echo '</br>'; echo $today; ?>
    <td width="25%" align="center" valign="middle" >
	
	<?PHP if($maindate < $today && $Drafts[$d]->rfp_type!= 'closed' && $Drafts[$d]->rfp_type!= 'Unawarded' && $Drafts[$d]->rfp_type!= 'Awarded') { ?><span style="color:orange; font-weight:bold;">OVERDUE</span><?php } ?>
	<?PHP if($Drafts[$d]->rfp_type== 'closed' || $Drafts[$d]->rfp_type== 'Unawarded' || $Drafts[$d]->rfp_type== 'Awarded') { ?><span style="color:red;font-weight:bold;">CLOSED</span><br/><?php } ?>
	<?PHP if($Drafts[$d]->rfp_type != 'closed' && $Drafts[$d]->rfp_type!= 'Unawarded' && $Drafts[$d]->rfp_type!= 'Awarded' ){ ?><span style="color:#7AB800; font-weight:bold;"></span><br/><?php } ?>
	
	<?PHP echo $date;  ?></td>
  </tr>
  <tr><td colspan="6"><div id="codedetails_<?php echo $Drafts[$d]->id; ?>" class="prop_details" ></div></td></tr>
  <?PHP } } ?>
<!-- <tr class="table_blue_rowdots">
    <td align="center" valign="top">&nbsp;</td>
    <td align="center" valign="top">&nbsp;</td>
    <td align="left" valign="top">&nbsp;</td>
    <td align="center" valign="top">&nbsp;</td>
    <td align="center" valign="middle"><a href="index.php?option=com_camassistant&controller=vendors&Prp_type=Draft&task=viewall_proposals&Itemid=107"><img src="templates/camassistant_left/images/view_all.gif" alt="view all" width="95" height="25" vspace="10" /></a></td>
  </tr>-->
  <?PHP } else { ?>
  <tr height="20"><td colspan="5" align="center">You have no proposals in this category</td></tr>
  <?php } ?>
</table>
<div class="clear"></div>
</div>
</div>

<!-- eof table pan -->


<!-- sof table pan -->
<br /><br />
<div class="table_pannel">
<div id="i_bar">
<div id="i_bar_txt"><span><strong>SUBMITTED PROPOSALS</strong></span>   <span></span></div>
<div id="i_icon"><a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=87&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" > </a></div>

</div>
<div class="table_panneldiv">
<?PHP if(count($Submits)>0) { ?>
<table width="100%" cellpadding="0" cellspacing="4" class="vendortable">
    <tr class="vendorfirsttr">
	<td></td>
	<td width="30%" align="center" valign="middle">PROPERTY</td>
    <td width="33%" align="center" valign="middle">PROJECT NAME</td>
    <td width="15%" align="center" valign="middle">COUNTY</td>
    <td width="25%" align="center" valign="middle">AMOUNT</td>
  </tr>
   <?PHP 
   //echo "<pre>"; print_r($Submits); echo "</pre>";
   for($d=0; $d<count($Submits); $d++) {
  
   $subject = $Submits[$d]->time_left;
	$pattern = '|-|';
	preg_match($pattern, substr($subject,0), $matches, PREG_OFFSET_CAPTURE);
	$cnt = count($matches); //echo '<pre>'; print_r($Submits[$d]); ?>
   <tr class="table_blue_rowdots_submitted">
   <td width="15" valign="middle" align="center">
   <a id="getcodeinfo_<?php echo $Submits[$d]->rfp_id; ?>" class="codeinfo_drafts" data="<?php echo $Submits[$d]->rfp_id; ?>_<?php echo $Submits[$d]->id; ?>_submitted" rel="<?php echo $Submits[$d]->Prperty_id; ?>" href="javascript:void(0);"></a>
   </td>
    <td width="30%" align="center" valign="middle"><?PHP echo str_replace('_',' ',$Submits[$d]->property_name); //echo $Submits[$d]->rfp_id;  ?></td>
    <td width="33%" align="center" valign="middle"><?PHP echo $Submits[$d]->projectName; if($Submits[$d]->Alt_bid == 'yes') echo '-ALT';  //echo $Submits[$d]->Prperty_id;  ?></td>
      	<?php //echo '<pre>'; print_r($Submits[$d]);
		$sql = "SELECT County FROM #__cam_counties WHERE id = ".$Submits[$d]->divcounty;
		$db->Setquery($sql);
		$County = $db->loadResult();
		?>
    <td width="15%" align="center" valign="middle"><?PHP echo $County;  ?></td>
    <td width="25%" align="center" valign="middle"><span class="price_color"><?php echo "$".number_format($Submits[$d]->proposal_total_price,2); ?></span></td>
  </tr>
  <tr><td colspan="6"><div id="codedetails_<?php echo $Submits[$d]->id; ?>" class="prop_details" ></div></td></tr>
  <?php } ?>
 
</table>
<div class="clear"></div>
</div>
</div>
<?PHP //} ?>
<!-- eof table pan -->


<!-- sof table pan -->
<?PHP
$Alt_bid = JRequest::getVar('Alt_bid','');
$rfp_id = JRequest::getVar('rfp_id','');
//$Prp_id = JRequest::getVar('Prp_id','');
$RFP_bids = $this->Prp_bids;
$Proposal_id = JRequest::getVar('Proposal_id','');
$Itemid = JRequest::getVar('Itemid','');
if($Alt_bid == '0' && $RFP_bids != '0')
{
 ?>
<script type="text/javascript" src="components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>
<script language="javascript" type="text/javascript">
M = jQuery.noConflict();

function Alt_proposal() {
				//Cancel the link behavior
		//Get the A tag
		//Get the screen height and width
		var maskHeight = M(document).height();
		var maskWidth = M(window).width();
		//Set heigth and width to mask to fill up the whole screen
		M('#mask2').css({'width':maskWidth,'height':maskHeight});
		//transition effect
		M('#mask2').fadeIn(100);
		M('#mask2').fadeTo("slow",0.8);
		//Get the window height and width
		var winH = M(window).height();
		var winW = M(window).width();
		//Set the popup window to center
		M("#submit2").css('top',  '300');
		M("#submit2").css('left', '582');
		M("#submit2").fadeIn(2000);

		M('.window2 #done2').click(function (e) {
		//Cancel the link behavior
		e.preventDefault();
		M('#mask2').hide();
		M('.window2').hide();
		 var rfp_id = <?PHP echo $rfp_id; ?> ;
		 var Itemid = <?PHP echo $Itemid; ?>;
		  var Proposal_id = <?PHP echo $Proposal_id; ?>;
		window.location = 'index.php?option=com_camassistant&controller=proposals&rebid=s&task=Proposal_edit&Alt_bid=yes&Proposal_id=' + Proposal_id + '&rfp_id=' + rfp_id + '&Itemid=107' ;
	});
}

M(document).ready(function() {
	//if close button is clicked
	M('.window2 #close2').click(function (e) {
		//Cancel the link behavior
		e.preventDefault();
		M('#mask2').hide();
		M('.window2').hide();
	});
	//if done button is clicked
	M('.window2 #done2').click(function (e) {
		//Cancel the link behavior
		e.preventDefault();
		M('#mask2').hide();
		M('.window2').hide();

	});
});
setTimeout("Alt_proposal()",10);
</script>
<style>
#mask2 {
  position:absolute;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}

#boxes2 .window2 {
  position:absolute;
  left:0;
  top:0;
  width:350px;
  height:150px;
  display:none;
  z-index:9999;
  padding:20px;
}


#boxes2 #submit2 {
  width:326px;
  height:109px;
  padding:10px;
  background-color:#ffffff;
}
#boxes2 #submit2 a{
 text-decoration:none;
 color:#000000;
 font-weight:bold;
 font-size:20px;
}
#done2 {
border:0 none;
cursor:pointer;
height:30px;
margin:0;
padding-left:88px;
float:left;
width:160px;
/*background:url(templates/camassistant/images/yes.gif) no-repeat;
*/
}
#close2 {
border:0 none;
cursor:pointer;
height:30px;
margin:0;
padding:0;
 color:#000000;
 font-weight:bold;
 font-size:20px;
}

</style>
<!--<body onload="javascript: ITB_save();"></body>-->

 <div id="boxes2" style="top:576px; left:582px;">
<div id="submit2" class="window2" style="top:300px; left:582px;">
<!--<div class="head_greenbg2"></div><br/>-->
<div style="padding-top:10px; text-align:center"><font color="#0000ce">Would you like to submit an alternative proposal to this primary proposal as well?</font>
</div>
<div style="padding-top:20px; text-align:center;">
<form name="edit" id="edit" method="post">
<div id="done2" style="width:50px" name="done2" value="Ok"><img src="templates/camassistant_left/images/yes.gif" /></div>
<div id="close2"  name="close2" value="Cancel"><img src="templates/camassistant_left/images/no.gif" /></div></div>
</form>
</div>
  <div id="mask2"></div>
</div>
<?PHP
}
?>
<?php } 
else{
	echo "<p align='center'>You have no proposals in this category</p>";
	echo "</div></div>";
}
?>
<!-- eof table pan -->

<?php }  }  ?>


<br /><br />
<div id="i_bar">
<div id="i_bar_txt">
<span><strong>AWARDED PROPOSALS</strong></span>
</div>
<div id="i_icon001"><a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=109&amp;Itemid=113"><img style="margin-top:6px;" src="templates/camassistant_left/images/info_icon2.png"> </a></div>
</div>
<div class="table_pannel">
<div class="table_panneldiv">
<table width="100%" cellpadding="0" cellspacing="4" class="vendortable">
	<?php if( count( $this->viewall_proposals ) > 0 ){ ?>
  <tr class="vendorfirsttr">
    <td></td>
    <td width="30%" align="center" valign="middle">PROPERTY</td>
    <td width="33%" align="center" valign="middle">PROJECT NAME</td>
    <td width="15%" align="center" valign="middle">AWARDED DATE</td>	
	<td width="25%" align="center" valign="middle">AMOUNT</td>
  </tr>
  <?php
  $All_roposals = $this->viewall_proposals;
 // print_r( $All_roposals);exit;
  $k = 0;
		foreach ($All_roposals as $row) :
		$subject = $row->time_left;
		$pattern = '|-|';
		preg_match($pattern, substr($subject,0), $matches, PREG_OFFSET_CAPTURE);
		$cnt = count($matches);
		$main = $row->proposalDueDate;
		$main = explode('-',$main);
		$maindate= $main[2].'-'.$main[0].'-'.$main[1];
		$today=date('Y-m-d');
  ?>
  <tr class="table_blue_rowdots_submitted">
	 		<td width="15" valign="middle" align="center">
   <a id="getcodeinfo_<?php echo $row->rfp_id; ?>" class="codeinfo_drafts" data="<?php echo $row->rfp_id; ?>_<?php echo $row->id; ?>_awarded" rel="<?php echo $row->Prperty_id; ?>" href="javascript:void(0);"></a>
   </td>
			<td width="30%" align="center" valign="middle" ><?php echo str_replace('_',' ',$row->property_name); ?></td>
	   		<td width="33%" align="center" valign="middle" ><?php echo $row->projectName; if($Prp_type_name != 'Review' && $Prp_type_name != 'Unawarded' && $Prp_type_name != 'Awarded'){ if($row->Alt_bid == 'yes') echo '-ALT'; } ?></td>
			<td width="15%" align="center" valign="middle"><?php echo $row->awardeddate; ?></td>
			<td width="25%" align="center" valign="middle"><span class="price_color"><?PHP if($row->proposal_total_price) { echo '$'.number_format($row->proposal_total_price,2); }  ?></span></td>
			</tr>
			<tr><td colspan="6"><div id="codedetails_<?php echo $row->id; ?>" class="prop_details" ></div></td></tr>
			<?php
			$k = 1 - $k;
			endforeach;
		?>
	<?php } else { ?>	
	<tr height="20"><td colspan="5" align="center">You have no proposals in this category</td></tr>
	<?php } ?>
 </table>
 </div>
 </div>
<?php //echo "<pre>"; print_r($this->viewall_proposals); echo "</pre>"; ?>

<br /><br />
<?PHP

	$deccount_pre = 0;
	for($ide=0; $ide<count($invitations); $ide++) {
		if($invitations[$ide]['not_interested'] != '2') {
			$deccount_pre ++ ;
		}
	}
?>

<div id="i_bar">
<div id="i_bar_txt">
<span><strong> DECLINED PROJECTS</strong></span>
</div>
<div id="i_icon001"><a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=109&amp;Itemid=113"><img style="margin-top:6px;" src="templates/camassistant_left/images/info_icon2.png"> </a></div>
</div>
<div class="table_pannel">
<div class="table_panneldiv">
<table width="100%" cellpadding="0" cellspacing="4" class="vendortable">
<?PHP if(count($invitations)>0 && count($invitations) > $deccount_pre ) { ?>
    <tr class="vendorfirsttr">
	<td></td>
	<td width="30%" align="center" valign="middle">PROPERTY</td>
    <td width="33%" align="center" valign="middle">PROJECT NAME</td>
    <td width="15%" align="center" valign="middle">COUNTY</td>
    <td width="25%" align="center" valign="middle">REQUESTED DUE DATE</td>
  </tr>
  <?php //echo "<pre>"; print_r($invitations); echo "</pre>"; ?>
  
  <?PHP for($d=0; $d<count($invitations); $d++) {
  			if($invitations[$d]['not_interested'] == '2') {
  		$subject = $Jobs[$d]['time_left'];
		$pattern = '|-|';
		preg_match($pattern, substr($subject,0), $matches, PREG_OFFSET_CAPTURE);
		$cnt = count($matches);
   if($invitations[$d]['not_interested'] == '1') {?>
  <tr class="table_blue_rowdots_submitted" style="color:#808080;" color="#808080">
  <?php } else { ?>
   <tr class="table_blue_rowdots_submitted">
  <?php } ?>
    <td width="15" valign="middle" align="center">
   <a id="getcodeinfo_<?php echo $invitations[$d]['rfp_id']; ?>" class="codeinfo_drafts" data="<?php echo $invitations[$d]['rfp_id']; ?>_<?php echo $invitations[$d]['id']; ?>_declined" rel="<?php echo $invitations[$d]['property_id']; ?>" href="javascript:void(0);"></a>
   </td>
   	<td width="30%" align="center" valign="middle"><?PHP  echo str_replace('_',' ',$invitations[$d]['Propertyname']); ?></td>
    <td width="33%" align="center" valign="middle"><?PHP  echo $invitations[$d]['projectName']; //echo $Drafts[$d]->Prperty_id;  ?></td>
    <td width="15%" align="center" valign="middle"><?PHP echo $invitations[$d]['County'];  ?></td>
	<?php $main = $invitations[$d]['proposalDueDate'];
	if($main != '0000-00-00'){
    $main = explode('-',$main);
	$date = $main[0].'-'.$main[1].'-'.$main[2];
	}
	else{
	$date = '00-00-0000';
	}
	?>
    <td width="25%" align="center" valign="middle"><?PHP echo $date;  ?></td>
  
  </tr>
  <tr><td colspan="6"><div id="codedetails_<?php echo $invitations[$d]['id']; ?>" class="prop_details" ></div></td></tr>
  <?PHP 
  		 } 
		 	}
		  } 
  if(count($invitations)<=0 ||  count($invitations) == $deccount_pre )
 { ?>
 <tr>
    <td colspan="5"  align="center" valign="top"><p style="margin-bottom:10px;">You have not declined any projects</p></td>
  </tr>
  <?PHP } ?>
 </table>
<div class="clear"></div>
</div>
</div>


</div>


<div id="boxesdp" style="top:576px; left:582px;">
<div id="submitdp" class="windowdp" style="top:300px; left:582px; border:6px solid red; position:fixed">
<div float="right" class="closeicon_delete" id="canceldp"><img src="media/system/images/closebox.png"></div>
<div id="i_bar_terms" style="background:none repeat scroll 0 0 red; margin:8px 5px 5px;">
<div id="i_bar_txt_terms" style="padding-top:8px; font-size:14px;">
<span style="font-size:14px;"> <font style="font-weight:bold; color:#FFF;">DELETE PROPOSAL</font></span>
</div></div>
<div style="text-align:justify">
<p class="heading_delete">Are you sure you want to DELETE your proposal?</p>
<p class="bordertopclass_delete">Note: Once your proposal is deleted, it will no longer be visible to the Manager. If you're deleting your primary proposal, your alternate proposal(Alt) will then become your primary.</p>
</div>
<div style="padding-top:20px; text-align:center;">
<div style="padding-top:20px; text-align:center; width:250px; margin:0 auto;">
<div id="canceldp" name="closedp" value="Cancel" class="propos_delete"></div>
<div id="donedp" name="donedp" value="Ok" class="yesawardjob"></div>
</div>
<form name="deleteproposalform" id="deleteproposalform" method="post">
<input type="hidden" value="com_camassistant" name="option" />
<input type="hidden" value="vendors" name="controller" />
<input type="hidden" value="delete_proposal" name="task" />
<input type="hidden" value="" class="rfpid" name="rfpid" />
<input type="hidden" value="" class="proposalid" name="pid" />
<input type="hidden" value="" class="altbid" name="alt" />
</form>
</div>
</div>
  <div id="maskdp"></div>
</div>


<div id="boxes1">
<div id="submit1" class="window1" style="top:250px; left:582px;border:4px solid #8FD800; position:fixed;">
<div id="i_bar_terms">
<div id="i_bar_txt_terms">
<span> <font style="font-weight:bold; color:#FFF;">INVITATION ACCEPTANCE</font></span>
</div></div>
<div style="text-align:center"><font color="gray">Please confirm you would like to provide a proposal for this request by providing a contact name and clicking on SUBMIT</font><br/><br />
<strong><img src="templates/camassistant_left/images/RequiredArrow.png" />&nbsp;Contact Name for this Project:</strong><br /><br />
<input type="text" name="con_name_this_project" id="con_name_this_project" value="">
</div>
<br />
<div style="padding-top:10px; text-align:center;">
<form name="edit" id="edit" method="post">
<div id="close1" style="width:158px; margin-left:21px;" name="close1" value="Cancel"><img src="templates/camassistant_left/images/cancel.png" /></div></div>
<div id="done1" style="width:380px;" name="done1" value="Ok"><img src="templates/camassistant_left/images/submit.png" /></div>
</form>
</div>
  <div id="mask1"></div>
</div>

<div id="boxesexu" style="top:576px; left:582px;">
<div id="submitexu" class="windowexu" style="top:300px; left:582px; border:6px solid red; position:fixed">
<div id="i_bar_terms" style="background:none repeat scroll 0 0 red; margin-top: 7px;">
<div id="i_bar_txt_terms" style="padding-top:8px; font-size:14px;">
<span style="font-size:14px;"> <font style="font-weight:bold; color:#FFF;">BLOCKED</font></span>
</div></div>
<div style="text-align:justify"><p class="block_unvers">We're sorry, but <strong>UNVERIFIED</strong> Vendors have been BLOCKED from participating in this project.</p>
</div>
<div id="topborder_row_endbidding"></div>
<div style="text-align:justify"><p class="block_unvers">NOTE: If you make the necessary changes to your account in order to qualify for this project, you will then be able to VIEW and ACCEPT participation.</p>
</div>

<div style="padding-top:25px;" align="center">
<div id="cancelex" name="doneex" value="Ok" class="blockunveriifed_vendor"></div>
</div>
</div>
  <div id="maskexu"></div>
</div>

<div id="boxesexc" style="top:576px; left:582px;">
<div id="submitexc" class="windowexc" style="top:300px; left:582px; border:6px solid red; position:fixed">
<div id="i_bar_terms" style="background:none repeat scroll 0 0 red; margin-top: 7px;">
<div id="i_bar_txt_terms" style="padding-top:8px; font-size:14px;">
<span style="font-size:14px;"> <font style="font-weight:bold; color:#FFF;">BLOCKED</font></span>
</div></div>
<div style="text-align:justify"><p class="block_unvers">We're sorry, but <strong>NON-COMPLIANT</strong> Vendors have been BLOCKED from participating in this project.</p>
</div>
<div id="topborder_row_endbidding"></div>
<div style="text-align:justify"><p class="block_unvers">NOTE: If you make the necessary changes to your account in order to qualify for this project, you will then be able to VIEW and ACCEPT participation.</p>
</div>

<div style="padding-top:25px;" align="center">
<div id="cancelex" name="doneex" value="Ok" class="blockunveriifed_vendor"></div>
</div>
</div>
  <div id="maskexc"></div>
</div>
<div id="boxesex" style="top:576px; left:582px;">
<div id="submitex" class="windowex" style="top:300px; left:582px; border:6px solid red; position:fixed">
<div id="i_bar_terms" style="background:none repeat scroll 0 0 red; margin-top: 7px;">
<div id="i_bar_txt_terms" style="padding-top:8px; font-size:14px;">
<span style="font-size:14px;"> <font style="font-weight:bold; color:#FFF;">BLOCKED</font></span>
</div></div>
<div style="text-align:justify"><p class="block_unvers">We're sorry, but <strong>UNVERIFIED</strong> and <strong>NON-COMPLIANT</strong> Vendors have been BLOCKED from participating in this project.</p>
</div>
<div id="topborder_row_endbidding"></div>
<div style="text-align:justify"><p class="block_unvers">NOTE: If you make the necessary changes to your account in order to qualify for this project, you will then be able to VIEW and ACCEPT participation.</p>
</div>

<div style="padding-top:25px;" align="center">
<div id="cancelex" name="doneex" value="Ok" class="blockunveriifed_vendor"></div>
</div>
</div>
  <div id="maskex"></div>
</div>