<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport('joomla.application.component.controller');

class documentsController extends JController
{

	function __construct()
	{
		parent::__construct();
	}
	function display()
	{
	parent::display();

	}
	function pdocs(){

	$model = $this->getModel('documents');
	$result = $model->getpdocs();
	parent::display();
}

	function sdocs(){

	$model = $this->getModel('documents');
	$sdocs = $model->get('Data');
	parent::display();

	}
	
	function pfiles(){
//print_r($_REQUEST['pid']); exit;
	$model = $this->getModel('documents');
	$pfiles = $model->getpfiles();
	parent::display();
	}
	
	function documents(){
	JRequest::getVar( 'view','documents');
	$model = $this->getModel('documents');
	parent::display();
	}
	
	function addfolder(){
	JRequest::getVar( 'view','documents');
	$model = $this->getModel('documents');
	$categoriess = $model->getcategories();
	parent::display();
	}
	function savefolder(){
	$post = JRequest::get('post');
	$cat_id = JRequest::getVar( 'cat_id','' );
	$docTitle = JRequest::getVar( 'docTitle','' );	
	//print_r($_REQUEST['path']);  echo "<br><br>";
	if($_REQUEST['path']=='components/com_camassistant/doc/'){
//	echo "In if"; 
	$path1 = "components/com_camassistant/doc/".$docFoldername;
	$path = "components/com_camassistant/doc/".$docFoldername.$docTitle;
	}
	else {
	$path1 = $_REQUEST['path'];
	$path = $_REQUEST['path']."/".$docTitle;
	}
	if(!is_dir($path1))
	mkdir($path1,0777);
	if(is_dir($path))
	{
	$post['docPath'] = $path1;
	echo "This folder name is already existing please try again";
	}
	else {
	mkdir($path,0777);
	$post['docPath'] = $path;
	$user = JFactory::getUser();
	if(isset($_REQUEST['mid']) && $_REQUEST['mid'] != '')
	$post['property_manager_id'] = $_REQUEST['mid'];
	else
	$post['property_manager_id'] = $user->id;
	$post['property_id'] = $_REQUEST['pid'];
	$post['parent'] = $_REQUEST['parentid'];
	$model = $this->getModel('documents');
	$success = $model->store($post);
	$db =& JFactory::getDBO();
	$query = "SELECT property_name FROM #__cam_property where id =".$cat_id;
	$db->setQuery($query);
    $catname=$db->loadResult();
	$post['cat_name'] = $catname; 
	$success = $model->store1($post);
	if($success){
	echo "New folder created successfully";
	}
	else{
	echo "The folder is not created please try again";
	}

}
exit;
	}
	
	function openfiles(){
	
	JRequest::getVar('view','documents');
	parent::display();

	}
	function addfile(){
	JRequest::getVar( 'view','documents');
 	parent::display();
	}
	
	function savefile(){
	$post = JRequest::get('post');
	$dest = JRequest::getVar( 'path','');
	jimport('joomla.filesystem.file');
////For checking file extension/////////////
	$model = $this->getModel('documents');
	$check = $model->getcheck();
////For checking file extension/////////////	
	$dest = $dest."/";
	$copied = copy($_FILES["file"]["tmp_name"],$dest.$_FILES['file']['name']);
	if($copied){
 	$post['property_manager_id'] = $_REQUEST['mid'];
 	$post['property_id'] = $_REQUEST['pid'];
	//$post['docPath'] = $_REQUEST['path']."/".$_FILES['file']['name'];
	$post['docPath'] = $_REQUEST['path'].$_FILES['file']['name']; //modified by lalitha
 	$post['docTitle'] = $_FILES['file']['name'];
	$post['parent'] = $_REQUEST['parentid'];	
	$model = $this->getModel('documents');
	//echo "<pre>"; print_r($post); exit;
	$res = $model->store3($post);
	echo "New file uploaded successfully";
	} else{
	
	}
exit;
}
////////////////////////////////////////Shared docs////////////////////////////////////
	function sfiles(){
//print_r($_REQUEST['spid']); exit;
	$model = $this->getModel('documents');
	$sfiles = $model->getsfiles();
	parent::display();
	}


	function saddfolder(){

	JRequest::getVar( 'view','documents');
	$model = $this->getModel('documents');
	$scategoriess = $model->getscategories();
	
 	parent::display();
	}
	
	
	function ssavefolder(){
	/*echo "<pre>";
	print_r($_REQUEST);exit*/;
//	echo $_REQUEST['smid']; exit;
//	echo "In control"; exit;
	$post = JRequest::get('post');
	$cat_id = JRequest::getVar( 'cat_id','' );
	$sdocTitle = JRequest::getVar( 'sdocTitle','' );	
//	print_r($_REQUEST['spath']);  echo "<br><br>"; 
	if($_REQUEST['spath']=='components/com_camassistant/doc/'){
	//echo "In if"; 
	$path1 = "components/com_camassistant/doc/".$docFoldername;	
	$path = "components/com_camassistant/doc/".$docFoldername.$sdocTitle;
	}
	else {
	$path1 = $_REQUEST['spath'];	
	$path = $_REQUEST['spath']."/".$sdocTitle;
	}
//print_r($path1);echo "<br>";print_r($path); exit;
	if(!is_dir($path1))
	mkdir($path1,0777);
	if(is_dir($path))
	{
	$post['docPath'] = $path1;
	echo "This folder name is already existing please try again";
	exit;
	}
	else {
	mkdir($path,0777);
	$post['docPath'] = $path;
	$post['property_manager_id'] = $_REQUEST['smid'];
	$post['property_id'] = $_REQUEST['spid'];
	
	$model = $this->getModel('documents');
	$success = $model->sstore($post);
	$db =& JFactory::getDBO();
	$query = "SELECT property_name FROM #__cam_property where id =".$cat_id;
	$db->setQuery($query);
    $catname=$db->loadResult();
	$post['cat_name'] = $catname; 
	$success = $model->store1($post);
	if($success){
	echo "New Folder added Successfully";
	}
	else{
	echo "Please add one more time";
	}
exit;
}
}
	function saddfile(){
	//echo "iam ehre<pre>";
	//print_r($_REQUEST);exit;
	JRequest::getVar( 'view','documents');
 	parent::display();
	}

	
	function ssavefile(){
	$post = JRequest::get('post');
	$dest = JRequest::getVar( 'spath','');
	jimport('joomla.filesystem.file');
	$model = $this->getModel('documents');
	$check = $model->getcheck();
// For checking extension...///	
	$dest = $dest."/";
	$copied = copy($_FILES["file"]["tmp_name"],$dest.$_FILES['file']['name']);
	if($copied){
 	$post['property_manager_id'] = $_REQUEST['smid'];
 	$post['property_id'] = $_REQUEST['spid'];
	$post['docPath'] = $_REQUEST['spath']."/".$_FILES['file']['name'];
 	$post['sdocTitle'] = $_FILES['file']['name'];	
	$post['parent'] = $_REQUEST['parentid'];	
	$model = $this->getModel('documents');
	$res = $model->store3($post);
	echo "<font color='red'>File has been uploaded successfully</font>";
	echo '<script language="javascript">window.parent.location.reload();window.parent.document.getElementById( "sbox-window" ).close();</script>';
	?>
	<?php  } else{
	echo "<font color='red'>File uploading was failed</font>";
	}
	exit(0);
}

	function sopenfiles(){
	JRequest::getVar('view','documents');
	parent::display();
	}

	function delete(){
//	echo "This is delete function"; exit;
	$model = $this->getModel('documents');
	$res = $model->getdelete($post);
	parent::display();
	}
	//code added by lalitha on April 08th
	function vendor_delete(){
//	echo "This is delete folder function"; exit;
	$model = $this->getModel('documents');
	$Itemid = JRequest::getVar('Itemid','');
	$res = $model->getvendor_delete($post);
	$link = 'index.php?option=com_camassistant&controller=documents&task=vendor_docs&Itemid='.$Itemid;
	$msg="Deleted Successfully";
	$this->setRedirect( $link,$msg );
	//parent::display();
	}
	
	
	// Vendor 08-04-11
	function vendor_deletefile(){
//	echo "This is delete file function"; exit;
	$model = $this->getModel('documents');
	$Itemid = JRequest::getVar('Itemid','');
	$res = $model->getvendor_deletefile($post);
	$link = 'index.php?option=com_camassistant&controller=documents&task=vendor_docs&Itemid='.$Itemid;
	$msg="Deleted Successfully";
	$this->setRedirect( $link,$msg );
	//parent::display();
	}
	
		//  Vendor 08-04-11 completed
		
		
		
		function deletefile(){
//	echo "This is delete function"; exit;
	$model = $this->getModel('documents');
	$res = $model->getdeletefile($post);
	parent::display();
	}

	
	function open(){
	$model = $this->getModel('documents');
	$open = $model->getopen($post);
	parent::display();
	
	}

////////////////////////////////////////Shared docs Completed////////////////////////////////////
}
?>