<?php
/**
 * @version		1.0.0 cam assistant $
 * @package		cam_assistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport( 'joomla.application.component.view' );

class assignedboardmembersViewAssignedboardmembers extends Jview
{

	function display($tpl = null){
	global $mainframe, $context;
	$filter_order		= $mainframe->getUserStateFromRequest( 'filter_order',		'filter_order',		'property_name',	'cmd' );
		
    $model	=& $this->getModel();
	$details = $model->getData();
	$pagination = & $this->get( 'Pagination' );
		
    $filter_order_Dir	= $mainframe->getUserStateFromRequest( 'filter_order_Dir',	'filter_order_Dir',	'asc','word' );
	$lists['order_Dir']	= $filter_order_Dir;
		
	$lists['order']		= $filter_order;
	JToolBarHelper::deleteList('','remove');
	
	$task=JRequest::getVar('task','');

	$propertynames = $this->get('propertynames');
	$this->assignRef('propertynames', $propertynames);
	
	if($task=='addmember')
	$this->setLayout('addmember');	

	$boardmembers = $this->get('boardmembers');
	$this->assignRef('boardmembers', $boardmembers);
	
	//$details = $this->get('details');
	$this->assignRef('details', $details);

	$pname = $this->get('editmembers');
	$this->assignRef('editmembers', $pname);
	
	$mname = $this->get('editmembers1');
	$this->assignRef('editmembers1', $mname);
	  $this->assignRef('lists',		$lists);    
 	$this->assignRef('pagination',	$pagination);

	
	if($task=='editmembers')
	$this->setLayout('editmember');	

		parent::display($tpl);
	}
		
}

?>