
<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

	
$Itemid = JRequest::getVar('Itemid',''); 
?>
<script type="text/javascript" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>
<script type="text/javascript">
G = jQuery.noConflict();
function validate_data2()
{
var frm = document.property_edit;
if(frm.property_name.value == '')
    {
    alert('Please enter property name');
    frm.property_name.focus();
    return ;
    }
 
    else if(frm.board_position.value == '')
    {
    alert('Please select your relation ship');
    frm.board_position.focus();
    return ;
    }
    else if(frm.streeaddress.value == '')
    {
    alert('Please enter property address');
    frm.streeaddress.focus();
    return ;
    }
	else if(frm.city.value == '')
    {
    alert('Please enter city');
    frm.city.focus();
    return ;
    }
    else if(frm.state.value == '0'||frm.state.value == '')
    {

    alert('Please select state');
    frm.state.focus();
    return ;
    }
    else if(frm.zipcode.value == '')
    {
    alert('Please enter zipcode');
    frm.zipcode.focus();
    return ;
    }
    
    else if(frm.divcounty.value == '0'||frm.divcounty.value == '')
    {

    alert('Please select County');
    frm.divcounty.focus();
    return ;
    }
    
	else{
	frm.submit();
	}
}
function county(){
var state = G("#stateid").val();
G.post("index2.php?option=com_camassistant&controller=addproperty&task=ajaxcounty", {State: ""+state+""}, function(data){
if(data.length >0) {
G("#divcounty").html(data);
}
});

}
function moveOnMax(field,nextFieldID){

  if(field.value.length >= field.maxLength){
    document.getElementById(nextFieldID).focus();
  }
}


	


function getpopuppics(){
el='<?php  echo Juri::base(); ?>index2.php?option=com_camassistant&controller=addproperty&task=uploadpropertypic';
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 500, y:350}}"))
SqueezeBox.fromElement(el,options);

}
function cancel()
{
window.location="index.php?option=com_camassistant&controller=addproperty&Itemid=75";
}
</script>

<script type="text/javascript">
L = jQuery.noConflict();
L(document).ready(function(){
L('#property_name').keyup(function(){
		if( L(this).val() == '' )
		L( this ).prev().removeClass( 'active' );
		else
		L( this ).prev().addClass( 'active' );
	});	
	
L('#board_position').change(function(){
		if( L(this).val() != '0' )
		L( this ).prev().addClass( 'active' );
		else
		L( this ).prev().removeClass( 'active' );
	});
	
L('#streeaddress').keyup(function(){
		if( L(this).val() == '' )
		L( this ).prev().removeClass( 'active' );
		else
		L( this ).prev().addClass( 'active' );
	});	
L('#city').keyup(function(){
		if( L(this).val() == '' )
		L( this ).prev().removeClass( 'active' );
		else
		L( this ).prev().addClass( 'active' );
	});		
L('#stateid').change(function(){
		if( L(this).val() != '0' )
		L( this ).prev().addClass( 'active' );
		else
		L( this ).prev().removeClass( 'active' );
	});
L('#zipcode').keyup(function(){
		if( L(this).val() == '' )
		L( this ).prev().removeClass( 'active' );
		else
		L( this ).prev().addClass( 'active' );
	});
L('#divcounty').change(function(){
		if( L(this).val() != '0' )
		L( this ).prev().addClass( 'active' );
		else
		L( this ).prev().removeClass( 'active' );
	});
L('#timezone').change(function(){
		if( L(this).val() != '0' )
		L( this ).prev().addClass( 'active' );
		else
		L( this ).prev().removeClass( 'active' );
	});
L('#units').keyup(function(){
		if( L(this).val() == '' )
		L( this ).prev().removeClass( 'active' );
		else
		L( this ).prev().addClass( 'active' );
	});
L('#phone1').keyup(function(){
		if( L(this).val() == '' )
		L( this ).prev().removeClass( 'active' );
		else
		L( this ).prev().addClass( 'active' );
	});			
	
					
	});
</script>

<div id="container_inner" class="property_status">

<div  style="margin-top:20px;">
 <div class="ttl1">Property Information</div>
 <div class="newtopborder"></div>
</div>
<form enctype="multipart/form-data"  method="post" name="property_edit" id="property_edit" >
<div class="clear"></div>
<?php //echo "<pre>"; print_r($this->details); ?>
<div id="signup-form">
<div class="signUp-left">
<div class="signup">
<span id="prop_list">
<input type="file" class="file_class" name ="property_image" value=""/>
<a id = "uplaod_pimage" href="javascript:void(0);" onclick="getpopuppics()"><span class="uploadimagetextes">Click here to upload an image of your property</span></a> 
</span>
</div>


</div>
<div class="signUp-right">
<div class="signup">
<label class="propertyownerredicons">Property Name:</label>
<input name="property_name" type="text"  id ="property_name" value=""/>

</div>

<div class="signup">
<label class="propertyownerredicons">Title (your relation to this property):</label>
<select name="board_position" id="board_position">
<option value="Owner" <?PHP if($property->board_position == 'Owner'){?> selected="selected" <?PHP } ?>>Owner</option>
<option value="President" <?PHP if($property->board_position == 'President'){?> selected="selected" <?PHP } ?>>President</option>
<option value="Vice President" <?PHP if($property->board_position == 'Vice President') {?> selected="selected" <?PHP } ?>>Vice President</option>
<option value="Treasurer" <?PHP if($property->board_position == 'Treasurer') { ?> selected="selected" <?PHP } ?>>Treasurer</option>
<option value="Secretary" <?PHP if($property->board_position == 'Secretary') { ?> selected="selected" <?PHP } ?>>Secretary</option>
<option value="Director" <?PHP if($property->board_position == 'Director') { ?> selected="selected" <?PHP } ?>>Director</option>

</select>
</div>

</div>

<div class="signup">
<label class="propertyownerredicons">Street Address: </label>
<input name="streeaddress" type="text"  id="streeaddress" value=""/>
</div>
<div class="signup">
<label class="propertyownerredicons">City: </label>
<input name="city" type="text"  id="city" value=""/>
</div>

<div class="signup col_2">
<div class="state">
<label class="propertyownerredicons">State: </label>
<select name="state"  id="stateid" onchange="javascript:county();" >
<option value="">Select State</option>
  <?php 

for ($i=0; $i<count($this->states); $i++){
$states = $this->states[$i];
?>

<option value="<?php echo $states->state_id?>" <?php if($states->state_id== $property->state) echo "selected";?>><?php echo $states->state_name?></option>
<?php } ?>
</select>
</div>
<div class="zip">
<label class="propertyownerredicons">Zip Code:</label>
<input name="zipcode" type="text" maxlength="5" id="zipcode" value="<?PHP echo $property->zip?>"/>
</div>
</div>
<div class="signup">

<label class="propertyownerredicons">County: </label>
<select name="divcounty" id="divcounty" >
<option value="">Select County</option>
</select>

</div>
<div class="signup">
<label class="propertyownerredicons">Time Zone:  </label>
<select  name="timezone"  id="timezone" >
<option <?php if( $property->timezone == 'eat'){ echo "selected='selected'"; } ?> value="est">(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima</option>
<option <?php if( $property->timezone == 'cen'){ echo "selected='selected'"; } ?> value="cen">(GMT -6:00) Central Time (US &amp; Canada), Mexico City</option>
<option <?php if( $property->timezone == 'mou'){ echo "selected='selected'"; } ?> value="mou">(GMT -7:00) Mountain Time (US &amp; Canada)</option>
<option <?php if( $property->timezone == 'pac'){ echo "selected='selected'"; } ?> value="pac">(GMT -8:00) Pacific Time (US &amp; Canada)</option>
<option <?php if( $property->timezone == 'ala'){ echo "selected='selected'"; } ?> value="ala">(GMT -9:00) Alaska</option>
<option <?php if( $property->timezone == 'haw'){ echo "selected='selected'"; } ?> value="haw">(GMT -10:00) Hawaii</option>
</select>
</div>
<div class="signup checkBox" >
<input type="checkbox" checked="checked" value="loc" name="location" id="location"> Location observes Daylight Savings
</div>
<div class="signup units">
<label class="propertyownerredicons">No. of Units (if applicable): </label>
<input name="units" type="text" id="units" value=""/>
</div>
<div class="signup">
<div class="cp">
<label class="propertyownerredicons">Phone: </label>
<input name="phone_1" type="text" class="sm-input" onclick="if(this.value == 'without spaces or dashes') this.value='';"  id= "phone1" maxlength="3" onkeyup="moveOnMax(this,'phone2')" value="<?PHP echo $phone[0]; ?>"  />
 <input  name="phone_2" type="text" onclick="if(this.value == 'without spaces or dashes') this.value='';"  id="phone2"  maxlength="3" onkeyup="moveOnMax(this,'phone3')" class="sm-input" value="<?PHP echo $phone[1]; ?>" ); "/> - 
 <input name="phone_3" type="text" onclick="if(this.value == 'without spaces or dashes') this.value='';"  id="phone3"  maxlength="4"  onkeyup="moveOnMax(this,'phone_ext')" class="sm-input" value="<?PHP echo $phone[2]; ?>" "/> |
</div>

<div class="ext">
<label style="margin-left:-45px; margin-top:-9px;">Ext:</label>
<input name="extension" id="phone_ext" type="text" maxlength="4"  class="sm-input" value=""  style=" margin-left:-45px;"  /></div>
<div class="clear"></div>
</div>																			
<div class="signup">
<div class="cp">
<label style="padding: 15px 0 3px 0px;">Alt. Phone: </label>
<input id="altphone_1" name="altphone_1" type="text" onclick="if(this.value == 'without spaces or dashes') this.value='';" maxlength="3" onkeyup="moveOnMax(this,'altphone_2')" class="sm-input" value="<?PHP echo $altphone[0]; ?>" />
 <input id="altphone_2" name="altphone_2" type="text" onclick="if(this.value == 'without spaces or dashes') this.value='';" maxlength="3" onkeyup="moveOnMax(this,'altphone_3')" class="sm-input" value="<?PHP echo $altphone[1]; ?>" "/> - 
 <input id="altphone_3" name="altphone_3" type="text"  onclick="if(this.value == 'without spaces or dashes') this.value='';" maxlength="4" onkeyup="moveOnMax(this,'altextension')" class="sm-input" value="<?PHP echo $altphone[2]; ?>"  "/> |
</div>

<div class="ext">
<label style="margin-left:-45px;">Ext:</label>
<input name="altextension" id="altextension" type="text" maxlength="4"  style=" margin-left:-45px;" class="sm-input" value=""  /></div>
<div class="clear"></div>
</div>																			
<div class="signup">

<label style="padding: 15px 0 3px 0px;">Fax:</label>
<input id="fax_1" name="fax_1" type="text" onclick="if(this.value == 'without spaces or dashes') this.value='';" maxlength="3" onkeyup="moveOnMax(this,'fax_2')" class="sm-input" value="<?PHP echo $fax[0]; ?>" />
 <input id="fax_2" name="fax_2" type="text" onclick="if(this.value == 'without spaces or dashes') this.value='';" maxlength="3" onkeyup="moveOnMax(this,'fax_3')" class="sm-input" value="<?PHP echo $fax[1]; ?>"  "/> - 
 <input id="fax_3" name="fax_3" type="text" onclick="if(this.value == 'without spaces or dashes') this.value='';" maxlength="4" class="sm-input" value="<?PHP echo $fax[2]; ?>"  "/>
</div>
<br/>
<div style="margin-top:20px;" id="topborder_row">
 </div>
<div class="">
<input type="hidden" name="user_id" value="<?PHP  echo $this->user_id; ?>" />
<a  href="javascript:void(0)" class="manager_cancel" onclick="cancel()"></a>
<a  href="javascript:void(0)" class="manager_submit" onclick="javascript: return validate_data2();"></a>
 </div>
</div>
<input type="hidden" value="com_camassistant" name="option" />
<input type="hidden" value="addproperty" name="controller" />
<input type="hidden" value="uplaod_pimage" id="uplaod_pimage" />
<input type="hidden" value="" id="image_name" name="image_name" />
<input type="hidden" value="savepropertydetails" name="task" />
<div class="clear"></div>
</div>

</form>
</div> 
<div class="clear"></div>
</div>
