<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport( 'joomla.application.component.view' );
class propertymanagerViewpropertymanager extends Jview
{
	function display($tpl = null)
	{
		//echo "iam hre"; exit;
		global $mainframe, $option;
		$task = JRequest::getVar("task",'');
				//Security questions///
			$model = $this->getModel('propertymanager');
			$questions = $model->getquestions();
			$row1[0] = new stdClass();
			$row1[0]->value = "";
			$row1[0]->text = "-Select Question-";
			$questions=array_merge($row1,$questions);
			//echo "<pre>"; print_r($questions);
			$this->assignRef('questions',$questions);
			///Completed/

     //sreenu
       

		if($task=='submit_licid')
		{
		$task = JRequest::getVar("task",'');
		$licno1 = JRequest::getVar('taxid1','');
		$licno2 = JRequest::getVar('taxid2','');
		$licno3 = JRequest::getVar('taxid3','');
		
		
		$licno = $licno1.'-'.$licno2;
		if($licno3){
		$licno = $licno . '-' . $licno3 ;  
		}
		else{
		$licno =  $licno ;
		}
		//echo '<pre>'; print_r($licno);
		$tax_id =JRequest::getVar('tax_id','');
		$model = $this->getModel('propertymanager');
		$result= $model->verifytaxid($licno,$tax_id);
		$rows = $model->getstates();
	      $row1[0] = new stdClass();
			$row1[0]->value = "";
			$row1[0]->text = " Select State ";
			$rows=array_merge($row1,$rows);

		//echo "123<pre>"; print_r($rows);exit;
		/*if (($licno!='')||($tax_id!='')){
		$model = $this->getModel('propertymanager');
		$result= $model->verifytaxid($licno,$tax_id);
		$this->setLayout('company_info');
		$this->assignRef('camfirm_license_no',	$result[0]->camfirm_license_no);
		$this->assignRef('tax_id',	$result[0]->tax_id);
		} else {
		$this->setLayout('company_info');
		$this->assignRef('camfirm_license_no', $licno);
		$this->assignRef('tax_id',	$tax_id);
		}*/
		if(count($result)>0 && ($task=='submit_licid')){

		//echo '<pre>'; print_r($result[0]);
		$this->setLayout('company_info');
		$this->assignRef('camfirm_license_no',	$licno);
		$this->assignRef('tax_id',	$result[0]->tax_id);
		$this->assignRef('states',$rows);
		} else {
		//Security questions///
			$model = $this->getModel('propertymanager');
			$questions = $model->getquestions();
			$row1[0] = new stdClass();
			$row1[0]->value = "";
			$row1[0]->text = "-Select Question-";
			$questions=array_merge($row1,$questions);
			//echo "<pre>"; print_r($questions);
			$this->assignRef('questions',$questions);
			///Completed/
		$this->setLayout('company_info');
		$this->assignRef('camfirm_license_no', $licno);
		$this->assignRef('tax_id',	$tax_id);
		$this->assignRef('states',$rows);

		//JFactory::getApplication()->enqueueMessage( 'pleae provide correct cam firm Licence or federal tax id' );
		}
		//echo "<pre>"; print_r($result[0]); exit;
		//$camfirm_license_no = $result[0]->camfirm_license_no;
//		$comp_name = $result[0]->comp_name;
//		$tax_id = $result[0]->tax_id;
//		$mailaddress = $result[0]->mailaddress;
//		$comp_city = $result[0]->comp_city;
//		$comp_state = $result[0]->comp_state;
//		$comp_zip = $result[0]->comp_zip;
//		$comp_phno = $result[0]->comp_phno;
//		$comp_extnno = $result[0]->comp_extnno;
//		$comp_alt_phno = $result[0]->comp_alt_phno;
//		$comp_alt_extnno = $result[0]->comp_alt_extnno;
//		$comp_website = $result[0]->comp_website;
//		$comp_logopath = $result[0]->comp_logopath;


		$this->assignRef('id',	$result[0]->id);
		$this->assignRef('comp_name',	$result[0]->comp_name);
		$this->assignRef('mailaddress',	$result[0]->mailaddress);
		$this->assignRef('comp_city',	$result[0]->comp_city);
		$this->assignRef('comp_state',	$result[0]->comp_state);
		$this->assignRef('comp_zip',	$result[0]->comp_zip);
		$this->assignRef('comp_phno',	$result[0]->comp_phno);
		$this->assignRef('comp_extnno',	$result[0]->comp_extnno);
		$this->assignRef('comp_alt_phno',	$result[0]->comp_alt_phno);
		$this->assignRef('comp_alt_extnno',	$result[0]->comp_alt_extnno);
		$this->assignRef('comp_website',	$result[0]->comp_website);
		$this->assignRef('comp_logopath',	$result[0]->comp_logopath);
		$this->assignRef('states',$rows);
		parent::display($tpl);
		} else if(!$task){

		parent::display($tpl);
		}

	if($task=='submit_companyinfo')
	  {


		$task = JRequest::getVar("task",'');
		
		//$licno1 = JRequest::getVar('taxid4','');
		//$licno2 = JRequest::getVar('taxid5','');
		//$licno3 = JRequest::getVar('taxid6','');
		$licno = JRequest::getVar('tax_id1','');
		$mfcompanyname = JRequest::getVar('comp_name','');
		$tax_id = JRequest::getVar('tax_id','');
		$mailaddress = JRequest::getVar('mailaddress','');
		$city = JRequest::getVar('city','');
		$state = JRequest::getVar('comp_state','');
		$zipcode = JRequest::getVar('zipcode','');
		$cphone1 = JRequest::getVar('cphone1','');
		if($cphone1==''){
		$cphone = JRequest::getVar('comp_phno','');
		} else {
		$cphone1 = JRequest::getVar('cphone1','');
		$cphone2 = JRequest::getVar('cphone2','');
		$cphone3 = JRequest::getVar('cphone3','');
		$cphone = $cphone1.'-'.$cphone2.'-'.$cphone3;
        }

		$cext = JRequest::getVar('cext','');
		$caphone1 = JRequest::getVar('caphone1','');
		if($caphone1==''){
		$caphone = JRequest::getVar('comp_alt_phno','');
		} else {
		$caphone1 = JRequest::getVar('caphone1','');
		$caphone2 = JRequest::getVar('caphone2','');
		$caphone3 = JRequest::getVar('caphone3','');
		$caphone = $caphone1.'-'.$caphone2.'-'.$caphone3;
		}
		$caext = JRequest::getVar('caext','');
		$website = JRequest::getVar('website','');
		$image = JRequest::getVar('image','');
		$email = JRequest::getVar('email','');
		$password = JRequest::getVar('password','');
		$password2 = JRequest::getVar('password2','');
		$salutation = JRequest::getVar('salutation','');
		$fname = JRequest::getVar('fname','');
		$lname = JRequest::getVar('lname','');
		$phone1 = JRequest::getVar('phone1','');
		$phone2 = JRequest::getVar('phone2','');
		$phone3 = JRequest::getVar('phone3','');
		$phone = $phone1.'-'.$phone2.'-'.$phone3;

		$ext = JRequest::getVar('ext','');
		$mphone1 = JRequest::getVar('mphone1','');
		$mphone2 = JRequest::getVar('mphone2','');
		$mphone3 = JRequest::getVar('mphone3','');
		$mphone = $mphone1.'-'.$mphone2.'-'.$mphone3;
		$id = JRequest::getVar('id',0);
		$question = JRequest::getVar('question','');
		$answer = JRequest::getVar('answer','');
		$hear = JRequest::getVar('hear','');


		$model = $this->getModel('propertymanager');
		$result = $model->verifytaxid($licno,$tax_id);
		$rows = $model->getstates();
		$this->assignRef('states',$rows);
		//print_r($_REQUEST); exit;
		$db =& JFactory::getDBO();
		$query_email="SELECT username FROM #__users WHERE username='".$email."'";
		$db->setQuery( $query_email );
		$result_email = $db->loadResult();
		if ($result_email){

		$msg="This username/password already in use. Please try another.";
		$comp_alt_phno = explode('-',$licno);
		$taxid2=$comp_alt_phno[0];
		$taxid1=$comp_alt_phno[1];
		$taxid3=$comp_alt_phno[2];
		if($taxid3){
		$taxid3 = "-".$taxid3;
		$thirdf = $taxid3  ;
		}
			$mainframe->redirect('index.php?option=com_camassistant&controller=propertymanager&view=propertymanager&task=submit_licid&Itemid=105&tax_id='.$tax_id.'&taxid1='.$taxid2.'&taxid2='.$taxid1. $thirdf .'&Itemid='.$_REQUEST['Itemid'],$msg);
		}
		//$details4 = $model->getcompname();
			//echo "<pre>"; print_r($result); exit;
		jimport('joomla.user.helper');
		$post	= JRequest::getVar("task",'');
		$user=clone(JFactory::getUser(0));
		$data['name']	=	$fname;
		$data['username']	=	$email;
		$data['password'] = $password ;
		$data['password2'] = $password2 ;
		$data['salutation'] = $salutation;
		$data['lastname'] = $lname ;
		$data['email'] = $email;
		$data['phone'] = $phone;
		$data['extension'] = $ext;
		$data['cellphone'] = $mphone;
		$data['question'] = $question;
		$data['answer'] = $answer;
		$data['hear'] = $hear;
        $date =& JFactory::getDate();
		$data['registerDate']	= $date->toMySQL();
		//echo "<pre>"; print_r($data); exit;
		//$usertype = $usersParams->get( 'new_usertype' );
		if (!$usertype) {
		$usertype = 'Registered';
		}

		if(count($result)>0 && ($task=='submit_companyinfo')){
		$data['user_type'] = '12';
		} else {
		$data['user_type'] = '13';
		}
		$data['gid']='18';

		//$useractivation = $usersParams->get( 'useractivation' ); // in this example, we load the config-setting
		// no we need no activation

  		 $data['block'] = 1; // don't block the user
 		// $data['activation'] = JUtility::getHash( JUserHelper::genRandomPassword() );

            jimport('joomla.filesystem.file');
			$files	=  JRequest::getVar( 'hidden_image', '', 'files', 'array' );
		//echo "<pre>"; print_r($user); exit;
		//echo "<pre>"; print_r($data); exit;
		//code to update users table
		if(!$user->bind($data)) {

		echo $user->getError();
		$this->setLayout('company_info');
		parent::display($tpl);
		}else {
		if (!$user->save()){
		echo $user->getError();
		$this->setLayout('company_info');
		parent::display($tpl);
		}
		}

	  
	  //save manager_code
	  
	 
			$len = 1;
			$min = 10000; // minimum
			$max = 99999; // maximum
			$range[] ='';
			foreach (range(0, $len - 1) as $i) {
			
			while(in_array($num = mt_rand($min, $max), $range));
			$range[] = $num;
			}
			$lastname = $lname;
			$manager_invitecode = $lastname.$range[1];
			
	       $sql1 = "UPDATE #__users SET manager_invitecode='".$manager_invitecode."' where id='".$user->id."'";
			$db->Setquery($sql1);
			$db->query();
	  //completed
	  
	  
	  //image upload code
		jimport('joomla.filesystem.file');
		 $files = JRequest::getVar( 'hidden_image', '', 'files', 'array' );

	    $base_Dir = JPATH_COMPONENT.DS.'assets'.DS.'images'.DS.'properymanager'.DS;
		if($files && $files['name'] != '')
		{
			$db =& JFactory::getDBO();
			$files1= str_replace(' ','_',$files['name']);
					$files1= str_replace('&','_',$files1);
					$files1= str_replace('#','_',$files1);
					$files1= str_replace('%','_',$files1);
			$filename =$user->id.'_'.$files1;
			$sql = "UPDATE #__cam_customer_companyinfo SET comp_logopath='".$filename."' where cust_id='".$user->id."'";
			$db->Setquery($sql);
			$db->query();
			//$filename =$files['name'];
						$filepath = $base_Dir . $filename;
						$post['image'] = $filename;
						if(file_exists($base_Dir . $filename))
						@unlink($base_Dir . $filename);
						move_uploaded_file($files['tmp_name'], $filepath);




    //code to move image to folderpath
			$model = $this->getModel('propertymanager');
			$pdf_resized = JPATH_COMPONENT.DS.'assets'.DS.'images'.DS.'properymanager'.DS.'pdf_resized';
			$resized = JPATH_COMPONENT.DS.'assets'.DS.'images'.DS.'properymanager'.DS.'resized';
			$img = $filepath;
			$dimensions = $model->get_thumbnail_dimensions();
			$img1=$resized;
			$img2 =$pdf_resized;
						if($dimensions[0]->vendor_logo_width == 0)
						$dimensions[0]->vendor_logo_width = 90;
						if($dimensions[0]->vendor_logo_height == 0)
						$dimensions[0]->vendor_logo_height = 90;
						//$thumb = $model->image_resize_to_max($img,$dimensions[0]->vendor_logo_width,$dimensions[0]->vendor_logo_height,$img1,$filename);
						$apath=getimagesize($img);
						$height_orig=$apath[1];
						$width_orig=$apath[0];
						$aspect_ratio = (float) $height_orig / $width_orig;
						$width =$dimensions[0]->vendor_logo_width;
						$height = round($width * $aspect_ratio);
						$thumb = $model->image_resize_to_max($img,$width,$height,$img1,$filename);
						$pdf_thumb = $model->image_resize_to_max($img,$width_orig,$height_orig,$img2,$filename);

            $ftmp =$filename;
            $oname = $filename;
            $fname = $pdf_resized.'/'.$filename;

            $sizes = getimagesize($fname);
			//print_r( $files); exit;
            $width	=	$sizes[0];
            $height	=	$sizes[1];

            $extenssion = strstr($oname, ".");

            $prod_img		= $fname;
            $prod_img_thumb =  $pdf_resized.'/'.$oname;
             move_uploaded_file($ftmp, $prod_img);
             $original_filesize = (filesize($prod_img)/1024);
             $sizes = getimagesize($prod_img);

            $expected_max_width		=	120;
            $expected_max_height	=	50;
            $originalw	=	$sizes[0];
            $originalh	=	$sizes[1];

            if ($originalh<$expected_max_height) {
                if ($originalw<$expected_max_width) {
                    $imgwidth	=	$originalw;
                    $imgheight	=	$originalh;
                } else {
                    $imgheight	=	($expected_max_width * $originalh)/ $originalw;
                    $imgwidth	=	$expected_max_width;
                }
            } else {
                 $new_height		=	$expected_max_height;
                 $new_width		=	($expected_max_height * $originalw)/ $originalh;

                if ($new_width>$expected_max_width) {
                    $new_height	=	($expected_max_width * $expected_max_height) / $new_width;
                    $new_width	=	$expected_max_width;
                }

                $imgwidth	=	$new_width;
                $imgheight	=	$new_height;
            }

            $new_h	=	$imgheight;
            $new_w	=	$imgwidth;
			$new_w_im='136';
			$new_h_im='68';
			$offsetwidth=$new_w_im-$new_w;
			$offsetw=$offsetwidth/2;
			$offsetheight=$new_h_im-$new_h;
			$offseth=$offsetheight/2;
  //  echo $extenssion;
           $dest = imagecreatetruecolor ($new_w_im,$new_h_im);
           $bg = imagecolorallocate ( $dest, 255, 255, 255 );
		//   print_r( $dest); echo "<br>"; print_r( $imgheight); exit;
           imagefill ( $dest, 0, 0, $bg );

		   $extenssion= str_replace('.jpg.jpg','.jpg',$extenssion);
		 $extenssion= str_replace('.jpeg.jpeg','.jpeg',$extenssion);
		 $extenssion= str_replace('.gif.gif','.gif',$extenssion);
		 $extenssion= str_replace('.png.png','.png',$extenssion);

			if($extenssion=='.jpg' || $extenssion=='.JPG'){
            	$src = imagecreatefromjpeg($prod_img)
                or die('Problem In opening Source JPG Image');
			}elseif($extenssion=='.jpeg' || $extenssion=='.JPEG'){
				 $src = imagecreatefromjpeg($prod_img)
                 or die('Problem In opening Source JPEG Image');
			}elseif($extenssion=='.gif' || $extenssion=='.GIF'){
				 $src = imagecreatefromgif($prod_img)
                 or die('Problem In opening Source GIF Image');
			}elseif($extenssion=='.png' || $extenssion=='.PNG'){
			   $src = imagecreatefrompng($prod_img)
                or die('Problem In opening Source PNG Image');
			}elseif($extenssion=='.bmp' || $extenssion=='.BMP'){
			    $src = imagecreatefrombmp($prod_img)
                or die('Problem In opening Source BMP Image');
			}

            if(function_exists('imagecopyresampled'))
            {
                imagecopyresampled($dest,$src,$offsetw,$offseth,0,0,$new_w,$new_h,imagesx($src),imagesy($src))
                or die('Problem In resizing');
            }else{
                Imagecopyresized($dest,$src,$offsetw,$offseth,0,0,$new_w,$new_h,imagesx($src),imagesy($src))
                or die('Problem In resizing');
            }

            imagejpeg($dest,$prod_img_thumb,72)
                or die('Problem In saving');
            imagedestroy($dest);
            @ob_flush();
            $new_filesize = (filesize($prod_img)/1024);


		}


	if(count($result)>0 && ($task=='submit_companyinfo')){
			$comp_extnno = JRequest::getVar('comp_extnno','');
			$comp_logopath = JRequest::getVar('image','');

			$compid = $model->getcompid($licno,$tax_id);
		  	$propertymanager['id'] = $id;
		    $propertymanager['cust_id'] = $user->id;
		    $propertymanager['comp_id'] = $compid;
			$propertymanager['camfirm_license_no'] = $licno;
			$propertymanager['comp_name'] = $mfcompanyname;
			$propertymanager['tax_id'] = $tax_id ;
			$propertymanager['mailaddress'] = $mailaddress;
			$propertymanager['comp_city'] = $city;
			$propertymanager['comp_state'] = $state;
			$propertymanager['comp_zip'] = $zipcode;
			$propertymanager['comp_phno'] = $cphone;
			$propertymanager['comp_extnno'] = $comp_extnno;
			$propertymanager['comp_alt_phno'] = $caphone;
			$propertymanager['comp_alt_extnno'] = $caext;
			$propertymanager['comp_website'] = $website;
			$propertymanager['comp_logopath'] = $comp_logopath;
			$propertymanager['is_providing_proposals'] = '0';
			$propertymanager['is_manage_cproperties'] = '0';
			$propertymanager['status'] = 'inactive';
			$propertymanager['activation'] = JUtility::getHash( JUserHelper::genRandomPassword() );
			$propertymanager['published'] = '0';

			$model = $this->getModel('propertymanager');
		    $query1 = "select cust_id FROM #__cam_camfirminfo where id ='$compid'";
			$db->setQuery($query1);
			$cust_id_ad = $db->loadResult();

			$query2 = "select id FROM #__cam_invitemanagers where reciever ='$email'";
			$db->setQuery($query2);
			$invite_ad = $db->loadResult();
			
			
		if($invite_ad=='' && $user->id){

			$date =  date('Y-m-d H:i:s');
			$insert_sql = "insert into #__cam_invitemanagers values ('','".$cust_id_ad."','".$email."','".$user->id."','0','".$date."','".$licno."','1')";
			$db->SetQuery($insert_sql);
			$db->query();
			//echo "<pre>"; print_r($post); exit;
		//$success = $model->invitestore($post);
		}
			if($user->id)
			{
			if($model->store($propertymanager)) {



				///$mailfrom = 'support@camassistant.com';
				$mailfrom= 'support@myvendorcenter.com';
				$fromname = 'MyVendorCenter Team';
				$cc = 'manageremails@myvendorcenter.com';
				$assignuseremail = $data['username'];
				$siteURL		= JURI::base();
				$useractivation = $siteURL."index.php?option=com_camassistant&controller=propertymanager&task=useractivation&useractivation=".$propertymanager['activation']."&Itemid=".$_REQUEST['Itemid'];

				$mailsubject = 'Registration Verification';
				$mail_sending= "SELECT introtext  FROM #__content where id='148' ";
				$db->Setquery($mail_sending);
				$content = $db->loadResult();
				$link = '<a href="'.$useractivation.'">CLICK HERE</a>';
				$customer_name = $data['name'].' '.$data['lastname'] ;
				$body = str_replace('{customer name}',$customer_name,$content) ;
				$body = str_replace('{CLICK HERE}',$link,$body) ;
				$body = str_replace('{LINK}',$useractivation,$body) ;

			//exit;
			//echo $body; exit;
				JUtility::sendMail($mailfrom, $fromname, $assignuseremail, $mailsubject, $body, $mode = 1);
				JUtility::sendMail($mailfrom, $fromname, $cc, $mailsubject, $body, $mode = 1);
				
				$cc_rize = 'rize.cama@gmail.com';
				JUtility::sendMail($mailfrom, $fromname, $cc_rize, $mailsubject, $body, $mode = 1);
				//$this->setLayout('property_thanks');
				$this->setLayout('property_thanks');
				parent::display($tpl);
				} else {
			$msg = JText::_( 'Error Saving propertymanager' );
			$this->setLayout('company_info');
			}
				//parent::display($tpl);
			} else {
				$msg = JText::_( 'Error Saving propertymanager' );
				$this->setLayout('company_info');
		parent::display($tpl);
			}
		} else {
			$camfirm['id'] = $id;
			$camfirm['cust_id']= $user->id;
			$camfirm['camfirm_license_no']= $licno;
			$camfirm['comp_name']= $mfcompanyname;
			$camfirm['tax_id']= $tax_id ;
			$model = $this->getModel('propertymanager');
			//print_r($model); exit;
           
            
			if($model->store_camfirm($camfirm)) {

			$this->setLayout('property_thanks');
			//parent::display($tpl);
			}
			//$hash1 = md5($password);
			$msg = JText::_( 'propertymanager Saved' );
			$propertymanager['id'] = $id;
		    $propertymanager['cust_id'] = $user->id;
			$propertymanager['camfirm_license_no'] = $licno;
			$propertymanager['comp_name'] = $mfcompanyname;
			$propertymanager['tax_id'] = $tax_id ;
			$propertymanager['mailaddress'] = $mailaddress;
			$propertymanager['comp_city'] = $city;
			$propertymanager['comp_state'] = $state;
			$propertymanager['comp_zip'] = $zipcode;
			$propertymanager['comp_phno'] = $cphone;
			$propertymanager['comp_extnno'] = $cext;
			$propertymanager['comp_alt_phno'] = $caphone;
			$propertymanager['comp_alt_extnno'] = $caext;
			$propertymanager['comp_website'] = $website;
			$propertymanager['comp_logopath'] = $filename;
			$propertymanager['is_providing_proposals'] = '0';
			$propertymanager['is_manage_cproperties'] = '0';
			$propertymanager['status'] = 'inactive';
			$propertymanager['activation'] = JUtility::getHash( JUserHelper::genRandomPassword() );
			$propertymanager['published'] = '1';
			$model = $this->getModel('propertymanager');
			//echo "<pre>"; print_r($propertymanager); exit;
			if($user->id)
			{
				if($model->store($propertymanager)) {
				$mailfrom = 'support@myvendorcenter.com';
			$fromname = 'MyVendorCenter Team';
			$assignuseremail = $data['username'];
			//$cc = 'vipin3485@gmail.com';
			
			$siteURL		= JURI::base();
			$useractivation = $siteURL."index.php?option=com_camassistant&controller=propertymanager&task=useractivation&useractivation=".$propertymanager['activation']."&Itemid=".$_REQUEST['Itemid'];
///To send activation link to the customer, modified by sateesh on 21-07-11
			$mailsubject = 'Registration Verification';
			$mail_sending= "SELECT introtext  FROM #__content where id='148' ";
			$db->Setquery($mail_sending);
			$content = $db->loadResult();
			$link = '<a href="'.$useractivation.'index.php">CLICK HERE</a>';
			$customer_name = $data['name'].' '.$data['lastname'] ;
			$body = str_replace('{customer name}',$customer_name,$content) ;
			$body = str_replace('{CLICK HERE}',$link,$body) ;
			$body = str_replace('{LINK}',$useractivation,$body) ;

			//echo $body; exit;
			
			JUtility::sendMail($mailfrom, $fromname, $assignuseremail, $mailsubject, $body, $mode = 1);
			$to_support = 'manageremails@myvendorcenter.com';
			$from = 'MyVendorCenter';
			$mailfrom = 'support@myvendorcenter.com';
			$subject = 'Registration Verification';
			JUtility::sendMail($mailfrom, $from, $to_support, $subject, $body, $mode=1);
			$to_sateesh = 'rize.cama@gmail.com';
			JUtility::sendMail($mailfrom, $from, $to_sateesh, $subject, $body, $mode=1);
			//$this->setLayout('property_thanks');
					$this->setLayout('property_thanks');
					parent::display($tpl);
				} else {

					$msg = JText::_( 'Error Saving propertymanager' );
					$this->setLayout('company_info');
					parent::display($tpl);
				}

			}
			//code to send mail to user
			//$mailfrom = 'support@camassistant.com';

///To send activation link to the customer modified by sateesh on 21-07-11 completed

		}
		
		/* $query11 = "select property_name FROM #__cam_board_mem where email ='".$email."'";
		 $db->setQuery($query11);
		 $propertyid = $db->loadResult();
		 
		 
         if($propertyid)
		 {
		    $query12 = "select boardposition FROM #__cam_property where id ='".$propertyid."'";
		    $db->setQuery($query12);
		    $board_position = $db->loadResult();
		    
			$update_property = "UPDATE #__cam_property  SET property_manager_id='".$user->id."',property_manager='".$user->id."',property_link=1 where id=".$propertyid."";
		    $db->setQuery($update_property);
		    $db->query();
			 
			$update_bordmem = "UPDATE #__cam_board_mem  SET user_id='".$user->id."',board_position='".$board_position."' where property_name=".$propertyid."";
		    $db->setQuery($update_bordmem);
		    $db->query(); 
		  
		  }*/
	}

	  //code to update jos_cam_customer_companyinfo table
		  // signup process 3
		/*else
		{
		if($task=='submit_companyinfo'){
		$model = $this->getModel('propertymanager');
		$this->setLayout('company_info');//signup process 1
		parent::display($tpl);
		}
		if($task=='submit_customerinfo'){
		$model = $this->getModel('propertymanager');
		$this->setLayout('customer_info');//signup process 1
		parent::display($tpl);
		}
		}*/
//	} }
	// }
	 if($task=='customer_edit_form')
		{
			global $mainframe;
			$pmanager_id = JRequest::getVar("pmanager_id",0);
			$comp_id = JRequest::getVar("comp_id",0);
			$model = $this->getModel('propertymanager');
			$user = JFactory::getUser();
			if($pmanager_id)
			{
				$cust_id=$pmanager_id;

				$questions = $model->getquestions();
				$this->assignRef('questions',$questions);
				
				$dms = $model->getalldistrictmanagers();
				$this->assignRef('dms',$dms);
				
				$this->setLayout('customer_edit_form');
				$properties = $model->getCAMFIRM_Viewall($comp_id);
				//$pagination = & $this->get( 'Pagination' );
				$this->assignRef('comp_id',$comp_id);
				$this->assignRef('properties',$properties);
				//$this->assignRef('pagination',$pagination);
			} else {
				$cust_id=$user->id;
				$this->setLayout('camadmin_edit_form');
			}
			$details = $model->getuserinfo($cust_id);
			$this->assignRef('user_id',$user->id);
			$this->assignRef('details',$details[0]);
			$this->setLayout('customer_edit_form');
			parent::display($tpl);
		}
	   if($task=='company_edit_form')
		{
			$model = $this->getModel('propertymanager');
			$details1 = $model->getcompanyinfo();
			$rows = $model->getstates();
			//$row1[0] = new stdClass();
			//$row1[0]->value = "";
			//$row1[0]->text = "Select Propety";
			//$rows=array_merge($row1,$rows);
			$user = JFactory::getUser();
			/*echo "<pre>";
			print_r($rows);exit;*/
			$this->assignRef('user_id',$user->id);
			$this->assignRef('states',$rows);
			$this->assignRef('details1',$details1[0]);
			
			$details = $model->getuserinfo($user->id);
			$this->assignRef('details',$details[0]);
			
			$this->setLayout('company_edit_form');
			parent::display($tpl);
		}
		if($task=='useractivation')
		{
			$this->setLayout('property_active');
			parent::display();
		}
		if($task=='activation')
		{
		$this->setLayout('propertyowneractivation');
		parent::display();
		}
		//
		if($task=='manage_properties')
		{
			//$model = $this->getModel('propertymanager');
			// Get URL

			$uri=& JFactory::getURI();
			$user = JFactory::getUser();

			if($user->id)
			{
			$model=& $this->getModel();
			$comp_id = $model->getCompanyId($user->id);
			$pmanagers = $model->getCAMFIRM_Viewall($comp_id);
			/*echo "<pre>";
			print_r($pmanagers);*/
			$pagination = & $this->get( 'Pagination' );
			}
			if($user->user_type == '13' && $user->accounttype == 'master' ){
				$admins = $model->getadminscount();
				$this->assignRef('admins',$admins);
			}
			$this->assignRef('comp_id',$comp_id);
			$this->assignRef('pmanagers',$pmanagers);
			$this->assignRef('pagination',$pagination);
			$this->assignRef('request_url',	$uri->toString());
			$this->setLayout('manageproperties');
			parent::display($tpl);
		}
		//
		if($task=='edit_vendor_mails')
		{
			//$model = $this->getModel('propertymanager');

			$user = JFactory::getUser();
			$model=& $this->getModel();
			/*echo "<pre>";
			print_r($user);*/
			//echo $user->id;exit;
			$comp_id = $model->getCompanyId($user->id);
			$detail = $model->getCamfirmadmin_emailsInfo($comp_id);
			//echo "123<pre>"; print_r($detail); exit;
			$this->assignRef('detail',$detail);
			$this->assignRef('camfirmadmin',$user->id);
			$this->assignRef('comp_id',$comp_id);
			$this->setLayout('vendormailsform');
			parent::display($tpl);
		}
		if($task=='invitemanager')
		{
			$model=& $this->getModel();
			$cams = $model->getcamfirms();
			$this->assignRef('cams',$cams);
			$invitations = $model->getallinvitations();
			$this->assignRef('invitations',$invitations);
			$this->setLayout('invitemanager');
			parent::display($tpl);
		}
		//
		if($task == 'getuploadpopup'){
		$this->setLayout('logouploadbox');
		parent::display($tpl);
		}
		if($task=='cam_managers_viewall')
		{
			//$model = $this->getModel('propertymanager');
			$user = JFactory::getUser();
			/*if($user->id)
			{*/
				$model=& $this->getModel();
				$comp_id = JRequest::getVar("comp_id",0);
				$pmanagers = $model->getCAMFIRM_Viewall($comp_id);
				$pagination = & $this->get( 'Pagination' );
				/*echo "<pre>";
				print_r($pagination);
				echo $user->id;exit;*/
			//}
			$this->assignRef('comp_id',$comp_id);
			$this->assignRef('pmanagers',$pmanagers);
			$this->assignRef('pagination',$pagination);
			$this->setLayout('allpmanagers');
			parent::display($tpl);
		}
		//
		if($task=='properties_viewall')
		{
			//$model = $this->getModel('propertymanager');
			$user = JFactory::getUser();
			if($user->id)
			{
				$model=& $this->getModel();
				$comp_id = JRequest::getVar("comp_id",0);

				$properties = $model->getCAMFIRM_Viewall($comp_id);
				$pagination = & $this->get( 'Pagination' );
				/*echo "<pre>";
				print_r($pmanagers);
				echo $user->id;exit;*/
			}
			$this->assignRef('comp_id',$comp_id);
			$this->assignRef('properties',$properties);
			$this->assignRef('pagination',$pagination);
			$this->setLayout('allproperties');
			parent::display($tpl);
		}
		//To get the edit form of a property
		if($task=='property_edit_form')
		{
			global $mainframe;
			$itemid=JRequest::getVar('Itemid',0);
			$property_id=JRequest::getVar('property_id',0);
			$model	=& $this->getModel();
			$pdetails=$model->getPropertyDetails($property_id);
			$this->assignRef('pdetails',$pdetails);
			$this->setLayout('property_edit_form');
			parent::display($tpl);
		}
		//
		if($task=='property_details')
		{
			//$model = $this->getModel('propertymanager');
			$user = JFactory::getUser();
			if($user->id)
			{
			$model=& $this->getModel();
			$property_id=JRequest::getVar('property_id',0);
			$pdetails = $model->getPropertyDetails($property_id);
			/*echo "<pre>";
			print_r($pdetails);exit;*/
			}
			$this->assignRef('pdetails',$pdetails);
			$this->setLayout('propertydetails');
			parent::display($tpl);
		}

		//
		if($task=='pmanager_details')
		{
			global $mainframe;
			$pmanager_id = JRequest::getVar("pmanager_id",0);
			$model = $this->getModel('propertymanager');
			$user = JFactory::getUser();

			$details = $model->getuserinfo($pmanager_id);

			$this->assignRef('user_id',$user->id);
			$this->assignRef('details',$details[0]);
			$this->setLayout('pmdetails');
			parent::display($tpl);
		}
		if($task == 'chagetodm'){

			$user = JFactory::getUser();
			if($user->id)
			{
				$model=& $this->getModel();
				$comp_id = $model->getCompanyId($user->id);
				$pmanagersall = $model->getmanagersalltopopup($comp_id);
				$this->assignRef('mans',$pmanagersall);
				$mananagers = $model->getmanaagers();
				$this->assignRef('existmanagers',$mananagers);
			}
			$this->setLayout('districtmanager');
			parent::display($tpl);
		}
		if($task == 'propertieslist'){
		$this->setLayout('propertiesdetails');
		$propertydetails = $model->getpropertieslist();
		$this->assignRef('propertynames',$propertydetails);
	parent::display($tpl);
		//echo "<pre>"; print_r($propertydetails); exit;
		}
		if( $task =='deletemgr' ){
			$managerid = JRequest::getVar('id','');
			$managerslist = $model->getallmanagers($managerid);
			$this->assignRef('managerslist',$managerslist);
			$this->setLayout('deletemanager');
			parent::display($tpl);
		}
		if( $task == 'getcompanymanagersall' ){
			$managerid = JRequest::getVar('userid','');
			$managerslist = $model->getallmanagers_company($managerid);
			$this->assignRef('managerslist',$managerslist);
			$dms = $model->getalldistrictmanagers();
			$this->assignRef('dms',$dms);
			$this->setLayout('managerslist_company');
			parent::display($tpl);
		}
		if( $task == 'propertyowner_1' ){
			$this->setLayout('propertyowner_1');
			parent::display($tpl);
		}
		//sreenu
		if($task=='submit_email')
		{
		$task = JRequest::getVar("task",'');
		$email = JRequest::getVar('email','');
		$model = $this->getModel('propertymanager');
		$states = & $this->get( 'statess' );
		$this->assignRef('states',	$states);
		$getmanagerpropertyinfo = $model->getmanagerpropertyinfo($email);
		$this->assignRef('getmanagerpropertyinfo',$getmanagerpropertyinfo);
		$this->setLayout('manager_property_info');
		parent::display($tpl);
		}
		
		if($task=='propertyowner_last')
		{
		
		$this->setLayout('propertyowner_thanks');
		parent::display($tpl);
		}
	 /* else if($task=='submit_customerinfo')
	  {

	  	$task = JRequest::getVar("task",'');
		$mfcompanyname = JRequest::getVar('mfcompanyname','');
		$email = JRequest::getVar('email','');
		$password = JRequest::getVar('password','');
		$password2 = JRequest::getVar('password2','');
		$salutation = JRequest::getVar('salutation','');
		$fname = JRequest::getVar('fname','');
		$lname = JRequest::getVar('lname','');
		$phone1 = JRequest::getVar('phone1','');
		$phone2 = JRequest::getVar('phone2','');
		$phone3 = JRequest::getVar('phone3','');
		$phone = $phone1.$phone2.$phone3;
		$ext = JRequest::getVar('ext','');
		$mphone1 = JRequest::getVar('mphone1','');
		$mphone2 = JRequest::getVar('mphone2','');
		$mphone3 = JRequest::getVar('mphone3','');
		$mphone = $mphone1.$mphone2.$mphone3;

		$this->assignRef('mfcompanyname',$mfcompanyname);

		jimport('joomla.user.helper');
		$post	= JRequest::getVar("task",'');
		$user=clone(JFactory::getUser(0));
		$data['name']	=	$fname;
		$data['username']	= $email;
		$data['password'] = $password ;
		$data['password2'] = $password2 ;
		$data['salutation'] = $salutation;
		$data['lastname'] = $lname;
		$data['email'] = $email;
		$data['phone'] = $phone;
		$data['extension'] = $ext;
		$data['cellphone'] = $mphone;
		$data['usertype'] = 'Registered';
		$data['user_type'] = '13';
		$data['gid']='18';

		//code to update users table
		if(!$user->bind($data)) {
		echo $user->getError();
		}else {
		if (!$user->save()){
		echo $user->getError();

		}
	  }
	 }*/
	 //parent::display($tpl);
	//}

}
}

//}
?>