<?php $user =& JFactory::getUser(); //echo "<pre>"; print_r($user); echo $user->id; exit;
/**
 * @version		1.0.0 cam assistant $
 * @package		cam_assistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here


?>
<link href="<?php echo JURI::root(); ?>administrator/templates/khepri/css/popup.css" rel="stylesheet" type="text/css"/>

<script type="text/javascript">
function fun(){
frm=document.mailform;
var inhouse=frm.inhouse.value;
var inhousevendors=frm.inhousevendors.value;
var subject=frm.subject.value;
var inhousetext=frm.inhousetext1.value;
//frm.submit();
window.parent.location.href = 'index.php?option=com_camassistant&task=inhousevendors&inhouse='+inhouse+'&inhousevendors='+inhousevendors+'&subject='+subject+'&inhousetext='+inhousetext+'&vendortype=<?php echo $_REQUEST['id']; ?>&userid=<?php echo $user->id; ?>&Itemid=<?php echo $_REQUEST['Itemid']; ?>&email=<?php echo $user->email; ?>';
window.close();
}
</script>
<script type="text/javascript" src="<?php echo JURI::root(); ?>administrator/components/com_camassistant/editor/ed.js"></script>  
<div id="l_box">
<div id="l_box_topcurve">
  <div id="l_box_close"></div>
  <?php if($_REQUEST['id'] == 'preferred') { ?>
  <p>Invite a Vendor to be an “Preferred” Vendor</p>
<?php } else {?>
  <p>Invite a Vendor to be an “In-house” Vendor</p> <?php } ?>
</div>

<form style="padding:0px; margin:0px;" action="<?php echo JRoute::_( 'index.php' ); ?>" method="post" name="mailform" >
<div id="l_box_midbg">
<div class="form_row"><div class="form_text">To:</div><label></label><input type="text" name="inhouse" style="width:390px;"/><div class="clear"></div></div>
<div class="form_row"><div class="form_text">BCC:</div><label></label><input  value="support@camassistant.com" type="text" name="inhousevendors" style="width:390px;"/><div class="clear"></div></div>
<div class="form_row"><div class="form_text">Subject:</div><label></label><input type="text" name="subject" style="width:390px;"/><div class="clear"></div></div>
<div class="form_row_button">
<div class="form_text">&nbsp;</div>
<div id="txt_box">
<div id="txt_box_topcurve"></div>
<div id="txt_box_midbg"><!--<h1>Enter your text here:</h1>-->
<script>edToolbar('mytxtarea'); </script>
<div class="clear"></div>
<textarea name="inhousetext" id="mytxtarea" class="ed" style=" width:361px;"  ><?php echo $this->data; ?></textarea>
<div class="clear"></div>
<textarea name="inhousetext1" id="mytxtarea1"  type="hidden"  style=" display:none; width:361px;"  ><?php echo $this->tdata; ?></textarea>
<div class="clear"></div>
<img src="images/submit_text.png" alt="Submit Text" vspace="10" border="0" onclick="javascript:fun();" />
<input type="hidden" name="option" value="com_cam_assistant" />
<input type="hidden" name="task" value="inhousevendors" />
<input type="hidden" name="vendortype" value="<?php echo $_REQUEST['id']; ?>" />
<?php echo JHTML::_( 'form.token' ); ?>
</div>
<div id="txt_box_botomcurve"></div>
</div>
<div class="clear"></div></div>
<div class="form_row">
<div id="txt_box"></div>
<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
</form>
<div id="l_box_botomcurve"></div>
</div>
<?php exit; ?>
</div>
</body>
</html>
