<?php

/**
 * @version		1.0.0 cam assistant $
 * @package		cam_assistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
$Itemid = JRequest::getVar('Itemid','');
// Your custom code here
JHTML::_('behavior.modal');
error_reporting(0);
?>
<?php 
$user =& JFactory::getUser(); 
if($user->user_type != 11)
{ ?>
<div align="center" style="color:#0066FF; font-size:15px"> You are not authorized to view this page.</div>
<?php } else { ?>
<!-- sof bedcrumb -->
<div id="bedcrumb" style="display:none">
<ul>
<li class="home"><a href="index.php?option=com_camassistant&controller=vendors&task=vendor_dashboard&Itemid=112">Home  </a></li>
<li>My Company Documents</li>
</ul>
</div>
<!-- eof bedcrumb -->
<!-- sof dotshead -->
<p style="height:12px;"></p>
<div id="dotshead_line2" style="margin-top:7px; background:none">
<p>Here is where you can store company documents that you do NOT wish to display on your Profile Page. Any documents uploaded here will be available to attach to your online proposal forms.</p><br />
<p><strong>IMPORTANT</strong>: This is NOT where you upload your compliance documents for review by MyVendorCenter and your clients.  These should be uploaded to the <a href="index.php?option=com_camassistant&amp;controller=vendors&amp;task=vendor_compliance_docs&amp;Itemid=115" class="hoverinvitevendors">My Compliance Documents</a> section of your account.</p><br />
  <div class="clear"></div>
 </div>




<div id="i_bar">
<div id="i_bar_txt">
<span><strong>DOCUMENTS</strong> </span></div>
<div id="i_icon"><?php 
 $user = JFactory::getUser();  
if ($user->user_type=='12') { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=89&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" /> </a>
<?php } else { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=110&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" /> </a>
<?php } ?></div>
</div>
<?php /*?> <link rel="stylesheet" href="<? echo juri::base(); ?>templates/camassistant_inner/css/style.css" type="text/css" /><?php */?>
<!-- sof table pan -->
<div class="table_pannel">
<div class="table_panneldiv">
<form name="docform" action="index.php">
<input type="hidden" name="option" value="" />
<input type="hidden" name="controller" value="" />
<input type="hidden" name="task" value="" />
<input type="hidden" name="spid" value="" />
<input type="hidden" name="smid" value="" />
<input type="hidden" name="spath" value="" />
<input type="hidden" name="doc_title" value="" />

<table width="100%" cellpadding="0" cellspacing="4" class="vendortable">
  <tr class="vendorfirsttr">
    <td width="102" align="center" valign="middle">SELECT</td>
    <td width="456" align="left" valign="middle">NAME</td>
    <td width="141" align="center" valign="middle">OPTIONS</td>
    </tr>
  
  <?php 

  if(count($this->vendor_files)>0){
//  print_r($this->vendor_files);
for ($i=0; $i<count($this->vendor_files); $i++){
$vendor_files = $this->vendor_files[$i]; 
$ext = end(explode('.', $vendor_files->docTitle));
$file = substr($vendor_files->docTitle,-4,-3);
if($file!='.') {
if(strlen($ext) !=4){
?>

<tr class="table_blue_rowdots2">
    <td align="center" valign="bottom" style="padding:15px 5px 15px 1px"><img src="images/folder_icon.png"  alt="folder" /></td>
    <td align="left" valign="middle" style="padding:15px 5px 15px 1px"><?php echo str_replace('_',' ',$vendor_files->docTitle); ?>
</td>
<td align="center" style="padding:15px 5px 15px 1px">

<!--  //Functio to verify taxid by sateesh on 03-08-11-->
<a href="index.php?option=com_camassistant&controller=documents&task=openfiles&pid=<?php print_r($vendor_files->property_id); ?>&mid=<?php print_r($vendor_files->property_manager_id); ?>&path=<?php print_r($vendor_files->docPath); ?>&Itemid=<?PHP echo $Itemid; ?>&folder_name=<?PHP print_r($vendor_files->docTitle); ?>&fileplace=<?PHP print_r($vendor_files->docTitle); ?>&taxid=<?php echo $this->taxid[0]->tax_id; ?>">OPEN</a>
<!--  //Functio to verify taxid by sateesh on 03-08-11 completed-->
<?PHP $db =& JFactory::getDBO(); $user =&JFactory::getUser();
//echo "<per>";print_r($user);; exit;
 if($user->user_type == '11'){ ?> | 
<script type="text/javascript">
function folderdelete(){
var result = confirm('Are you sure you want to delete this folder <?php print_r($vendor_files->docTitle); ?> and the internal files?');

	if(result == true)
	{
	var frm = document.docform;
	frm.option.value='com_camassistant';
	frm.controller.value='documents';
	frm.task.value='vendor_delete';
	frm.spid.value=<?php echo $vendor_files->property_id; ?>;
	frm.smid.value=<?php echo $vendor_files->property_manager_id; ?>;
	frm.spath.value='<?php print_r($vendor_files->docPath); ?>';
	frm.doc_title.value='<?php print_r($vendor_files->docTitle); ?>';
	frm.submit();
	}
	else 
	{
		//alert('No action taken');
		return false;
	}
}
</script>
<!--<a href="index.php?option=com_camassistant&controller=documents&Itemid=<?PHP //echo $Itemid; ?>&controller=documents&task=vendor_delete&spid=<?php //echo $vendor_files->property_id; ?>&smid=<?php //echo $vendor_files->property_manager_id; ?>&spath=<?php //print_r($vendor_files->docPath); ?>&title=<?php //print_r($vendor_files->docTitle); ?>">DELETE</a>
-->
 <a  href="javascript:void(0);" onclick="javascript:folderdelete();">DELETE</a>
 
  <?PHP } ?>
</td>
</tr>
<?php } } } ?>
<?php
if(count($this->vendor_files)>0) {
for ($i=0; $i<count($this->vendor_files); $i++){
$vendor_files = $this->vendor_files[$i]; 
//echo "<pre>"; print_r($vendor_files);
$ext = end(explode('.', $vendor_files->docTitle));
$file = substr($vendor_files->docTitle,-4,-3);
if($file=='.'|| strlen($ext)==4 ) {
$img_icon = substr(strrchr($vendor_files->docTitle, "."), 1);
$ext = end(explode('.', $vendor_files->docTitle));
/*if(strlen($img_icon)== 3 || strlen($img_icon) == 4)
$img = 'bmp.png';
else
$img = 'folder_icon.png';*/
?>


<tr class="table_blue_rowdots2">
    <td align="center" valign="bottom" style="padding:15px 5px 15px 1px"><img src="templates/camassistant_inner/images/images_<?PHP echo $ext; ?>.png"  alt="folder" /></td>
    <td align="left" valign="middle" style="padding:15px 5px 15px 1px"><?php echo str_replace('_',' ',$vendor_files->docTitle); ?>
</td>
<!--<td><a href="<?php //print_r($vendor_files->docPath);?>">OPEN</a></td>-->
<td align="center" style="padding:15px 5px 15px 1px"><a href="index.php?option=com_camassistant&controller=documents&task=open&doc_title=<?php print_r($vendor_files->docTitle); ?>&path=<?php print_r($vendor_files->docPath); ?> ">OPEN</a><?PHP $db =& JFactory::getDBO(); $user =&JFactory::getUser(); if($user->user_type == '11'){ ?> |  
<script type="text/javascript">
function filedelete(file){
var result = confirm('Are you sure you want to delete this file'+file+' ?');

	if(result == true)
	{
		var from = document.docform;
		from.option.value='com_camassistant';
		from.controller.value='documents';
		from.task.value='vendor_deletefile';
		from.spid.value=<?php echo $vendor_files->property_id; ?>;
		from.smid.value=<?php echo $vendor_files->property_manager_id; ?>;
		from.spath.value='<?php print_r($vendor_files->docPath); ?>';
		from.doc_title.value=file;

		from.submit();
	}
	else 
	{
		//alert('No action taken');
		return false;
	}
}
</script>
<!-- <a id="delete"  href="index.php?option=com_camassistant&controller=documents&task=vendor_deletefile&spid=<?php //echo $vendor_files->property_id; ?>&smid=<?php //echo $vendor_files->property_manager_id; ?>&doc_title=<?php //print_r($vendor_files->docTitle); ?>&spath=<?php //print_r($vendor_files->docPath); ?> " onclick="javascript:filedelete();">DELETE</a>-->
<a href="javascript:void(0);" onclick="javascript:filedelete('<?php echo $vendor_files->docTitle?>');">DELETE</a>
<?PHP } ?></td>
</tr>
<?php } } 
} // end -ifif(count($this->vendor_files)>0)
?>
<?php 
}
 else { ?>
<tr class="table_blue_rowdots2">
    <td align="center" valign="bottom" style="padding-top:12px; padding-bottom:12px;"><img src="images/folder_icon.png"  alt="folder" /></td>
    <td align="left" valign="middle" style="padding-top:12px; padding-bottom:12px;"><?php echo "No files in this folder"; ?></td>
	<td align="left" valign="middle" style="padding-top:12px; padding-bottom:12px;"></td>
</tr>
<?php } ?>
 <tr class="table_blue_rowdot">
   <td align="center" valign="bottom">&nbsp;</td>
   <td align="left" valign="top">&nbsp;</td>
   <td align="left" valign="top">&nbsp;</td>
   </tr>

</table>
</form>
<?php $val = 'components/com_camassistant/doc/'; 
if($vendor_files->property_id ==''){
$vendor_files->property_id = $_REQUEST['pid'];
}
if($vendor_files->property_manager_id ==''){
$vendor_files->property_manager_id = $user->id;
}
$db =& JFactory::getDBO(); $user =&JFactory::getUser();
$vendor_files->property_manager_id = $user->id;
?>
<p style="height:50px;"></p>
<div class="table_bottomlinks2">
<ul>
<li  style=" background:none;">
<a class="modal" id="links1"  title="Add Folder"  href="index.php?option=com_camassistant&controller=documents&task=addfolder&parentid=0&pid=<?php print_r($vendor_files->property_id); ?>&mid=<?php print_r($vendor_files->property_manager_id); ?>&path=<?php echo $val.$this->taxid[0]->tax_id; ?>" rel="{handler: 'iframe', size: {x: 400, y: 200}}" >
<img src="images/new_folder.png" alt="add a new folder" width="45" height="39" align="absmiddle" />
+Add a new Folder  </a></li>

<li><a class="modal" id="links1"  title="Upload File"  href="index.php?option=com_camassistant&controller=documents&task=addfile&parentid=0&pid=<?php print_r($vendor_files->property_id); ?>&mid=<?php print_r($vendor_files->property_manager_id); ?>&path=<?php echo $val.$this->taxid[0]->tax_id; ?>" rel="{handler: 'iframe', size: {x: 500, y: 250}}" > <img src="images/upload_folder.png" alt="Upload a file to this folder" width="37" height="36" align="middle" />+Upload a file to this folder </a></li> 
</ul>
</div>
</div></div>
<?php } ?>

