<?php
/**
 * @version		1.0.0 camsignup $
 * @package		camsignup
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		anand kumar
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here

//echo "<pre>"; print_r($this->pagination);

?>
<script type="text/javascript" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>

<script type="text/javascript">
G = jQuery.noConflict();
function openpopup(total) {
window.location="index.php?option=com_camassistant&controller=rfpcenter&task=awardjob&rid="+total+"&Itemid=125";
/*var el ='index.php?option=com_camassistant&controller=rfpcenter&task=proposalawarding&Itemid=<?php echo $_REQUEST['Itemid']; ?>&rid='+total;
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 700, y:550}}"))
SqueezeBox.fromElement(el,options);*/
}
G = jQuery.noConflict();
function popup_proposal_summary()
{

	var chk = document.getElementsByName('chk1[]');
	var j = 0;
	for(var i=0; i < chk.length; i++){
	if(chk[i].checked){
	j++;
	rfp_id =chk[i].value;
	}
	}
	if(j==0 || j>1){
  alert("Please select one property");
	}
	else {
	window.location.href='zipdownloads/RFP'+rfp_id+'.zip';
	}
}
function popup_proposal_summary1(rfp_id)
{
	window.open('index.php?option=com_camassistant&controller=vendors&task=vendor_proposals_summary&rfp_id='+rfp_id,'_blank');
}

function rebid(rfp_id,basic)
{

	window.location.href ="index.php?option=com_camassistant&controller=rfp&task=editrfp&rfpid="+rfp_id+"&job="+basic+"&Itemid=<?php echo $_REQUEST['Itemid']; ?>";
}
function popup_proposal_summary34(rfp_id,bid)
{
	var chk = document.getElementsByName('cid[]');
	var rfp_id=rfp_id;
	var bid=bid;
	if(bid!=0){
	G.post("index2.php?option=com_camassistant&controller=rfp&task=keypath&tmpl=component", {rfpid: ""+rfp_id+""}, function(data){

if(data.length >0) {
window.location.href='<?php echo Juri::root(); ?>ziptest.php?directtozip='+data+'&rfpid='+rfp_id+'';
}
});
} else {
alert('There are no Proposals submitted for this RFP.\n We are unable to generate the Zip File.');
}
}
function draft(rfp_id)
{
	window.location.href ="index.php?option=com_camassistant&controller=rfpcenter&task=copydraft&rfpid="+rfp_id+"&Itemid=<?php echo $_REQUEST['Itemid']; ?>";
}
</script>
<script type="text/javascript">
G = jQuery.noConflict();
G(document).ready( function(){
G(".rfp_<?php echo $_REQUEST['type']; ?>").addClass('active');

G('.proposal_opener').click(function(){
//G('#proposaldetails_'+rfpid).addClass('loader');
rfpdata=G(this).attr('data').split('|');
if(!G(this).hasClass("active")){
getclosedproposals(rfpdata[0],rfpdata[1]);
G('.proposal_opener').removeClass('active');
G(this).addClass('active');
}else{
getproposalshide(rfpdata[0]);
G(this).removeClass('active');

}
//G('#proposaldetails_'+rfpid).removeClass('loader');

});
});

function getclosedproposals(rfpid,rfpname){
G = jQuery.noConflict();
G('#proposaldetails_'+rfpid).addClass('loader');
G.post("index2.php?option=com_camassistant&controller=rfpcenter&task=getclosedproposals", {rfpid: ""+rfpid+"", rfpname: ""+rfpname+""}, function(data){
if(data) {
G('#proposaldetails_'+rfpid).removeClass('loader');
G('.prop_details').slideUp();
G('.table_blue_rowdots_submitted').removeClass('active');
G('#table_blue_rowdots'+rfpid).addClass('active');
G('#proposaldetails_'+rfpid).html(data).slideDown('slow');
//G('#getproposals_'+rfpid).hide();
//G('#getproposalshide_'+rfpid).show();
G('#proposaldetails_'+rfpid).show();
}
else{
G('#proposaldetails_'+rfpid).removeClass('loader');
G('#proposaldetails_'+rfpid).html("No proposals for this RFP");
//G('#getproposals_'+rfpid).hide();
//G('#getproposalshide_'+rfpid).show();
}
		});
}

function getproposalshide(rfpid){
//G('#getproposalshide_'+rfpid).hide();
//G('#getproposals_'+rfpid).show();
G('#proposaldetails_'+rfpid).slideUp('slow').html('');
G('.table_blue_rowdots_submitted').removeClass('active');
//G('#table_blue_rowdots'+rfpid).css('color','#636363');
}


function contactsupport(rfpname){
		G('body,html').animate({
		scrollTop: 250
		},800);
		G('#submitteremail').val(rfpname);
		var maskHeight = K(document).height();
		var maskWidth = K(window).width();
		G('#maskfb').css({'width':maskWidth,'height':maskHeight});
		G('#maskfb').fadeIn(100);
		G('#maskfb').fadeTo("slow",0.8);
		var winH = G(window).height();
		var winW = G(window).width();
		G("#submitfb").css('top',  winH/2-G("#submitfb").height()/2);
		G("#submitfb").css('left', winW/2-G("#submitfb").width()/2);
		G("#submitfb").fadeIn(2000);
		G('.windowfb #donefb').click(function (e) {
		G('#contactsupportform').submit();
		e.preventDefault();
		G('#maskfb').hide();
		G('.windowfb').hide();
		});
	 	G('.windowfb #closefb').click(function (e) {
		e.preventDefault();
		G('#maskfb').hide();
		G('.windowfb').hide();
		});
}

function reopenrfp(rfpid){
G('body,html').animate({
		scrollTop: 250
		},800);
		G('#rfpidtoopen').val(rfpid);
		var maskHeight = K(document).height();
		var maskWidth = K(window).width();
		G('#maskre').css({'width':maskWidth,'height':maskHeight});
		G('#maskre').fadeIn(100);
		G('#maskre').fadeTo("slow",0.8);
		var winH = G(window).height();
		var winW = G(window).width();
		G("#submitre").css('top',  winH/2-G("#submitre").height()/2);
		G("#submitre").css('left', winW/2-G("#submitre").width()/2);
		G("#submitre").fadeIn(2000);
		G('.windowre #donere').click(function (e) {
		G('#rebidrfpform').submit();
		e.preventDefault();
		G('#maskre').hide();
		G('.windowre').hide();
		});
		G('.windowre #closere').click(function (e) {
		e.preventDefault();
		G('#maskre').hide();
		G('.windowre').hide();
		});
}

function reopenclosedrfp(rfpid){
G('body,html').animate({
		scrollTop: 250
		},800);
		G('#rfpidtoreopen').val(rfpid);
		var maskHeight = K(document).height();
		var maskWidth = K(window).width();
		G('#maskreopen').css({'width':maskWidth,'height':maskHeight});
		G('#maskreopen').fadeIn(100);
		G('#maskreopen').fadeTo("slow",0.8);
		var winH = G(window).height();
		var winW = G(window).width();
		G("#submitreopen").css('top',  winH/2-G("#submitreopen").height()/2);
		G("#submitreopen").css('left', winW/2-G("#submitreopen").width()/2);
		G("#submitreopen").fadeIn(2000);
		G('.windowreopen #donereopen').click(function (e) {
		G('#openedrfpform').submit();
		e.preventDefault();
		G('#maskreopen').hide();
		G('.windowreopen').hide();
		});
		G('.windowreopen #closereopen').click(function (e) {
		e.preventDefault();
		G('#maskreopen').hide();
		G('.windowreopen').hide();
		});
}

function getcompliancestate(rfpid,vendorid,custid,status){
el='<?php  echo Juri::base(); ?>index.php?option=com_camassistant&controller=rfp&task=getcompliance_active&from=active&rfpid='+rfpid+'&custid='+custid+'&vendorid='+vendorid+'&status='+status+'';
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 650, y:700}}"))
SqueezeBox.fromElement(el,options);
G("#sbox-window").addClass("newclasssate");	
}

function getcompliancestate_null(rfpid,vendorid,custid){
el='<?php  echo Juri::base(); ?>index.php?option=com_camassistant&controller=rfpcenter&task=getcompliance_null&rfpid='+rfpid+'&custid='+custid+'&vendorid='+vendorid+'';
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 650, y:210}}"))
SqueezeBox.fromElement(el,options);
}

function getbasiccompliance(vendorid,status){
var el ='index.php?option=com_camassistant&controller=vendorscenter&task=preferredcompliance&vendorid=&vendorid='+vendorid+'&status='+status+'';
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 650, y:700}}"))
SqueezeBox.fromElement(el,options);
G("#sbox-window").addClass("newclasssate");	
}

function getbasiccompliance_null(vendorid){
el='<?php  echo Juri::base(); ?>index.php?option=com_camassistant&controller=rfpcenter&task=getcompliance_null&vendorid='+vendorid+'';
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 650, y:210}}"))
SqueezeBox.fromElement(el,options);
}

function unverified(vendorid,type){
if(type == 'unverified')
var height = '290';
else
var height = '230';
var el ='index.php?option=com_camassistant&controller=rfpcenter&task=vendortype&vendorid='+vendorid+'&type='+type;
var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 650, y:"+height+"}}"))
SqueezeBox.fromElement(el,options);
}
function rejectallproposals(rfpid){
	el='<?php  echo Juri::base(); ?>index.php?option=com_camassistant&controller=rfpcenter&task=unawardingjob&rid='+rfpid+'&Itemid=<?php echo $_REQUEST['Itemid']; ?>';
	var options = $merge(options || {}, Json.evaluate("{handler: 'iframe', size: {x: 672, y:420}}"))
	SqueezeBox.fromElement(el,options);
}
</script>
<style>
#maskreopen {  position:absolute;  left:0;  top:0;  z-index:9000;  background-color:#000;  display:none;}
#boxesreopen .windowreopen {  position:absolute;  left:0;  top:0;  width:350px;  height:150px;  display:none;  z-index:9999;  padding:20px;}
#boxesreopen #submitreopen {  width:426px;  height:103px;  padding:10px;  background-color:#ffffff;}
#boxesreopen #submitreopen a{ text-decoration:none; color:#000000; font-weight:bold; font-size:20px;}
#donereopen {border:0 none;cursor:pointer;height:30px;margin-left:90px;padding:0;float:left;}
#closereopen {border:0 none;cursor:pointer;height:30px;margin-right:90px;padding:0; color:#000000; font-weight:bold; font-size:20px; float:right}
</style>
<style>
#maskfb {
  position:absolute;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}

#boxesfb .windowfb {
  position:absolute;
  left:0;
  top:0;
  width:350px;
  height:150px;
  display:none;
  z-index:9999;
  padding:20px;
}


#boxesfb #submitfb {
  width:426px;
  height:320px;
  padding:10px;
  background-color:#ffffff;
}
#boxesfb #submitfb a{
 text-decoration:none;
 color:#000000;
 font-weight:bold;
 font-size:20px;
}
#donefb {
border:0 none;
cursor:pointer;
height:30px;
margin-left:80px;
padding:0;
float:left;
}
#closefb {
border:0 none;
cursor:pointer;
height:30px;
margin-right:65px;
padding:0;
 color:#000000;
 font-weight:bold;
 font-size:20px;
}

</style>
<style>
#maskre {
  position:absolute;
  left:0;
  top:0;
  z-index:9000;
  background-color:#000;
  display:none;
}

#boxesre .windowre {
  position:absolute;
  left:0;
  top:0;
  width:350px;
  height:150px;
  display:none;
  z-index:9999;
  padding:20px;
}


#boxesre #submitre {
  width:426px;
  height:140px;
  padding:10px;
  background-color:#ffffff;
}
#boxesre #submitre a{
 text-decoration:none;
 color:#000000;
 font-weight:bold;
 font-size:20px;
}
#donere {
 border: 0 none;
    cursor: pointer;
    float: right;
    height: 30px;
    margin-right: 40px;
    padding: 0;
}
#closere {
border:0 none;
cursor:pointer;
height:30px;
margin:0;
padding:0;
 color:#000000;
 font-weight:bold;
 font-size:20px;
 float:left;
 width:207px;
}

</style>
<div id="boxesfb" style="top:576px; left:582px;">
<div id="submitfb" class="windowfb" style="top:300px; left:582px; position:fixed; border:4px solid #8FD800;">
	<form method="post" name="contactsupportform" id="contactsupportform">
	<div style="padding-top:10px; text-align:left">
	<dl>
	<dt><label for="submitter_name">Subject</label></dt>
	<dd><input type="text" value="" id="submitteremail" name="subject" style="width:250px" readonly="readonly" /> </dd>
	<dt><label for="feedback">Your Request</label></dt>
	<dd><textarea name="supportbody" id="supportbody" style="height:150px; width:350px"></textarea></dd>
	</dl>
	</div>
	<div style="padding-top:20px; text-align:center;">
	<input type="hidden" value="com_camassistant" name="option">
	<input type="hidden" value="rfpcenter" name="controller">
	<input type="hidden" value="sendrequest" name="task">
	<div id="donefb" name="donefb" value="Ok"><img src="templates/camassistant/images/send-request.gif" class="yesimage" /></div>
	<div id="closefb" name="closefb" value="Cancel"><img src="templates/camassistant/images/No.gif" class="yesimage" /></div>
	</form>
</div>
</div>
  <div id="maskfb"></div>
</div>
<?php
$user = JFactory::getUser();
if($user->user_type == 11)
{ ?>
<div align="center" style="color:#0066FF; font-size:15px"> You are not authorized to view this page.</div>
<?php } else { ?>
<div id="bedcrumb"	 style="display:none">
<ul>
<li class="home"><a href="index.php">Home </a></li><li>Closed RFPs </li>
</ul>
</div>
<ul class="addednum_bread">
<li class="first"><a href="index.php?option=com_camassistant&controller=rfpcenter&task=unsubmittedrfp&Itemid=88">DRAFTS</a></li>
<li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=submitedrfp&type=rfp&Itemid=87" class="rfp_rfp">ACTIVE</a></li>
<li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=closedrfp&Itemid=89" class="active">ENDED</a></li>
<li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=awardrfp&Itemid=123">AWARDED</a></li>
<li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=awardrfp&rated=yes&Itemid=123">AWARDED & RATED</a></li>
<li><a href="index.php?option=com_camassistant&controller=rfpcenter&task=unawardrfp&Itemid=124" class="rfp_cancel">CANCELED</a></li>
</ul>
<p class="topalign"></p>
<div id="i_bar">
<div id="i_icon"><?php
 $user = JFactory::getUser();
if ($user->user_type=='12') { ?>

<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=131&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" /> </a>
<?php } else { ?>
<a style="text-decoration: none;" title="Click here" class="modal" rel="{handler: 'iframe', size: {x: 680, y: 530}}" href="index2.php?option=com_content&amp;view=article&amp;id=130&amp;Itemid=113"><img src="templates/camassistant_left/images/info_icon2.png" /> </a>
<?php } ?></div>
<div id="i_bar_txt">
<span><font style="font-weight:bold; ">&nbsp;&nbsp;STEP 3 of 5: BIDDING ENDED </font>(Closed)  </span>
</div></div>


<div class="table_pannel">
<div class="table_panneldiv">
<form action="" method="post" name="adminform"  >
<table width="100%" cellpadding="0" cellspacing="4" class="titleheadings">
  <tr class="table_green_row">
    <td width="80"  valign="middle" align="center" colspan="1" class="firsttd">RFP#</td>
    <td width="222" valign="middle" align="center">PROPERTY NAME</td>
    <td width="270" valign="middle" align="center">PROJECT NAME</td>
    <td width="160"  valign="middle" align="center"><span style="padding-left:17px;">CLOSED</span></td>
  </tr>
</table>
    <?php if($this->details2){ ?>
<table cellpadding="0" cellspacing="0" width="99%" style="margin:0px 4px">

  	<?php
	$k = 0;
	foreach ($this->details2 as $row) : ?>
			<?php	global $mainframe;
			$db = JFactory::getDBO();
			$count="SELECT id FROM #__cam_vendor_proposals WHERE proposaltype='Submit' and rfpno=".$row->id;
			$db->setQuery( $count );
			$count = $db->loadObjectlist();

			$rfp_id = $row->id;
			$newrfp_id = 'RFP'.$rfp_id;
			//echo $rfp_id.'<br />'.$newrfp_id.'<br />';


			$property_id="SELECT property_id FROM #__cam_rfpinfo where id=".$rfp_id;
			$db->Setquery($property_id);
			$property_id = $db->loadResult();
			//echo '<pre>'; print_r($property_id);

			$property_name ="SELECT property_name FROM #__cam_property where id=".$property_id;
			$db->Setquery($property_name);
			$property_name = $db->loadResult();
			$property_name = str_replace(" ", "_", $property_name);
			//echo '<pre>'; print_r($property_name);

			$key = JPATH_BASE .DS.'PropertyDocuments'.DS.$property_name.DS.'Proposal Reports'.DS.$newrfp_id.DS;
		//$key = '\\\192.168.1.46\www\camassistant_new\PropertyDocuments'.DS.$property_name.DS.'Proposal Reports'.DS.$newrfp_id.DS;
			// echo $key; exit;
			?>
	<?php
	if( $row->jobtype == 'yes' )
		$job = 'basic';
	else
		$job = '';	
	?>
		  <tr class="table_blue_rowdots_submitted" id="table_blue_rowdots<?php echo $row->id; ?>" >

			<td width="15" valign="middle" align="center">
			<a id="getproposals_<?php echo $row->id; ?>" class="proposal_opener" data="<?php echo $row->id; ?>|<?php echo $row->projectName; ?>" href="javascript:void(0);"></a>
			</td>
	 		<td valign="middle" align="center" valign="middle" width="15"><?php echo $row->id; ?></td>
	 		<td align="center" valign="middle" width="222"><span style="margin-left: 11px;"><?php echo str_replace('_',' ',$row->property_name); ?></span></td>
			<td align="center" valign="middle" width="270">
			<a class="joblinkhomepage" href="index.php?option=com_camassistant&controller=rfp&task=reviewrfp&rfpid=<?php echo $row->id; ?>&var=view&job=<?php echo $job; ?>&Itemid=87"><?php echo $row->projectName; ?></a></td>
	   		<td align="center" valign="middle" width="160">
			<?php 
			$datetime = explode(' ',$row->biddingcloseddate) ;
			echo $datetime[0].'<br />';
			echo date("h:i A", strtotime($datetime[1])).'&nbsp;';
			 ?> 
			 <?php 
			if( $row->timezone == '' || $row->timezone == 'est' ) echo 'EST';
			else if( $row->timezone == 'cen' ) echo 'CEN';
			else if( $row->timezone == 'mou' ) echo 'MOU';
			else if( $row->timezone == 'pac' ) echo 'PAC';
			else if( $row->timezone == 'ala' ) echo 'ALA';
			else if( $row->timezone == 'haw' ) echo 'HAW';
			else if( $row->timezone == 'eni' ) echo 'ENI';
			else if( $row->timezone == 'midw' ) echo 'MIDW';
			else if( $row->timezone == 'car' ) echo 'CAR';
			else if( $row->timezone == 'atl' ) echo 'ATL';
			else if( $row->timezone == 'new' ) echo 'NEW';
			else if( $row->timezone == 'bra' ) echo 'BRA';
			else if( $row->timezone == 'mid' ) echo 'MID';
			else if( $row->timezone == 'azo' ) echo 'AZO';
			else if( $row->timezone == 'wes' ) echo 'WES';
			else if( $row->timezone == 'bru' ) echo 'BRU';
			else if( $row->timezone == 'kal' ) echo 'KAL';
			else if( $row->timezone == 'bag' ) echo 'BAG';
			else if( $row->timezone == 'teh' ) echo 'TEH';
			else if( $row->timezone == 'abu' ) echo 'ABU';
			else if( $row->timezone == 'kab' ) echo 'KAB';
			else if( $row->timezone == 'eka' ) echo 'EKA';
			else if( $row->timezone == 'mum' ) echo 'MUM';
			else if( $row->timezone == 'kath' ) echo 'KATH';
			else if( $row->timezone == 'alm' ) echo 'ALM';
			else if( $row->timezone == 'yan' ) echo 'YAN';
			else if( $row->timezone == 'ban' ) echo 'BAN';
			else if( $row->timezone == 'bei' ) echo 'BEI';
			else if( $row->timezone == 'tok' ) echo 'TOK';
			else if( $row->timezone == 'ade' ) echo 'ADE';
			else if( $row->timezone == 'eas' ) echo 'EAS';
			else if( $row->timezone == 'mag' ) echo 'MAG';
			else if( $row->timezone == 'auk' ) echo 'AUK';
			?>
			 </td>
			</tr>
			<tr><td colspan="6"><div id="proposaldetails_<?php echo $row->id; ?>" class="prop_details" ></div></td></tr>
		<?php
		$k = 1 - $k;
		endforeach;

	//}
	?>


</table>
<?php JHTML::_('behavior.modal'); ?>
<div class="table_bottomlinks">
<ul style="display:none">
<?php /*?><li style=" background:none;"><a title="Industries" class="modal" rel="{handler: 'iframe', size: {x: 1000, y: 850}}" href="index.php?option=com_camassistant&amp;controller=vendors&amp;task=vendor_proposals_summary&amp;rfp_id=<?php echo $row->id;  ?>&amp;Prp_id=<?PHP echo $row->property_id; ?>" onclick="javascript: alert('hi'); document.adminform.submit();">View Proposals</a></li>
<?php */?>
<li style=" background:none;"><a href="javascript:popup_proposal_summary1();">View Proposals</a></li>
<li><a href="javascript:popup_proposal_summary();">Download Proposals</a></li>
<li><a href="#" onclick="openpopup();" >Award Job</a></li>
<li><a href="#" onclick="draft();">Copy As A New (Draft) RFP</a> </li>
<li><a href="#" onclick="rebid();" >Modify and Resubmit RFP</a></li></ul>
</div>

<div class="clear"></div>

<?php } else { ?>
<div align="center" style="margin-top:10px; font-weight:bold;">You don't have any closed rfp's</div>
</div>
</div>
<?php } ?>
<?php if(count($this->details2) >= $this->pagination2->limit) { ?>
<?php if($this->details2){ ?>
<?php if($_REQUEST['viewall']!='all'){ ?>
<div class="viewallbuttons_loc"><a href="index.php?option=com_camassistant&controller=rfpcenter&task=closedrfp&viewall=all&Itemid=<?php echo $_REQUEST['Itemid'];?>" ><img src="templates/camassistant_left/images/view_all.gif" border="0"/></a></div>
<?php } ?>
<?php if ($_REQUEST['viewall']=='all') { ?>
<div class="viewallbuttons_loc"><a href="index.php?option=com_camassistant&controller=rfpcenter&task=closedrfp&Itemid=<?php echo $_REQUEST['Itemid'];?>" ><img src="templates/camassistant_left/images/back1.gif" border="0" /></a></div>
<?php } } } ?>
<div style="float:right;">
<?php //echo $this->pagination2->getPagesLinks( ); ?>
	<?php //echo $this->pagination2->getLimitBox( ); ?>
	<?php //echo $this->pagination2->getResultsCounter(); ?>
	</div>

	<input type="hidden" name="option" value="com_camassistant" />
<!--<input type="hidden" name="controller" value="rfpcenter" />
<input type="hidden" name="task" value="awardjob" />-->
<input type="hidden" name="Itemid" value="<?php echo $_REQUEST['Itemid']; ?>" />

	</form>
</div></div><br/>
<?php  if ($_REQUEST['viewall']=='all') { ?>
 <div class="alink0215dash"> <?php } else { ?>
<div class="alink0215dash" > <?php } ?>
<a style="margin-left:300px;" target="_blank" href="http://get.adobe.com/reader/" ><img align="middle" src="https://www.adobe.com/images/shared/download_buttons/get_adobe_reader.gif" /></a><br />
<a style="margin-left:176px;" target="_blank" href="http://get.adobe.com/reader/" >Download or update Adobe Reader to view your Proposal Reports</a></div>
	</div>
<?php } ?>
<div id="boxesreopen" style="top:576px; left:582px;">
<div id="submitreopen" class="windowreopen" style="top:300px; left:582px; border:4px solid rgb(143, 216, 0); position:fixed">

<div style="padding-top:10px; text-align:center"><font color="gray">Are you sure you want to Re-Open this Project?</font>
</div>
<div style="padding-top:20px; text-align:center;">
<form name="openedrfpform" id="openedrfpform" method="post">
<div id="closereopen" name="closereopen" value="Cancel"><img src="templates/camassistant/images/No.gif" class="yesimage" /></div>
<div id="donereopen" name="donereopen" value="Ok"><img src="templates/camassistant/images/yes.gif" class="yesimage" /></div>
<input type="hidden" value="com_camassistant" name="option">
<input type="hidden" value="rfpcenter" name="controller">
<input type="hidden" value="reopenedclosedrfp" name="task">
<input type="hidden" value="" id="rfpidtoreopen" name="rfpid" />
</form>
</div>
</div>
  <div id="maskreopen"></div>
</div>

<div id="boxesre" style="top:576px; left:582px;">
<div id="submitre" class="windowre" style="top:300px; left:582px; border:4px solid #8FD800; position:fixed">
<div style="padding-top:10px; text-align:center"><font color="gray">Do you want to convert this RFP to OPEN Bidding so you can see the prices?
NOTE: This is irreversible and will be annotated on the Proposal Report</font>
</div>
<div style="padding-top:20px; text-align:center;">
<form name="rebidrfpform" id="rebidrfpform" method="post">
<div id="closere" name="closere" value="Cancel"><img src="templates/camassistant/images/no-goback.gif" class="yesimage" /></div>
<div id="donere" name="donere" value="Ok"><img src="templates/camassistant/images/yes-breakseal.gif" class="yesimage" /></div>
<input type="hidden" value="com_camassistant" name="option" />
<input type="hidden" value="rfpcenter" name="controller" />
<input type="hidden" value="reopenrfp" name="task" />
<input type="hidden" value="" id="rfpidtoopen" name="rfpid" />
</form>
</div>
</div>
  <div id="maskre"></div>
</div>