<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */
// no direct access
	defined('_JEXEC') or die('Restricted access');
	require_once('libraries/tcpdf/config/lang/eng.php');
	require_once('libraries/tcpdf/tcpdf.php');
	
	class MYPDF extends TCPDF {
	
	// Page footer
	public function Footer() {
		// Position at 1.5 cm from bottom
		$this->SetY(-15);
		// Page number
		$this->SetFontSize(8);
		$this->Cell(210, 0, 'Proposal Report Page '.$this->getAliasNumPage().' of '.$this->getAliasNbPages(), 0, 2, 'C');
		$this->SetFontSize(7);
		$this->Cell(0, 5, 'Copyright 2011 CAMassistant', 0, 0, 'C');
	}
}
	$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
	$pdf->SetCreator(PDF_CREATOR);
	// set default header data
	$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
	
	// set header and footer fonts
	$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
	$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
	
	// set default monospaced font
	$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
	
	//set margins
	$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
	$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
	$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
	//set auto page breaks
	$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

	//set image scale factor
	$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO); 
	//set some language-dependent strings
	$pdf->setLanguageArray($l); 
	
	$pdf->SetFont('dejavusans', '', 10);// set font
	$pdf->AddPage(); // add a page
	// Your custom code here
	JHTML::_('behavior.modal');
	$from = JRequest::getVar('from','');
	$document =& JFactory::getDocument();
	$document->addStyleSheet('templates/camassistant_left/css/style.css');
	$RFP_info = $this->RFPinfo;
	$RFP_info->id = sprintf('%06d', $RFP_info->id);
	//echo '<pre>'; print_r($RFP_info->id); exit;
	$BID_info = $this->BIDinfo;
	$BID_Vendors_info = $this->BiddedVendorsInfo;
	//calculation to no of pages iteration in pdf
	$remainder = count($BID_Vendors_info)%4;
	$quotient = intval(count($BID_Vendors_info)/4);
	$total = count($BID_Vendors_info);
//	$remainder = 8%4; 
//	$quotient = intval(8/4);
	
	if($remainder == 0)
	$loop_iterator = $quotient;
	else
	$loop_iterator = $quotient+1;
	
	
	//code to max, min bid values of propsal
	$Max_bid = number_format($BID_info->Max_Bid, 2, '.', '');
	$Min_bid = number_format($BID_info->Min_Bid, 2, '.', '');
	$Avg_bid = number_format($BID_info->Average_Bid, 2, '.', '');
	//echo "<pre>"; print_r($BID_Vendors_info);  exit;
	$com_phone = explode('-',$RFP_info->comp_phno) ;
	// create new PDF document
	$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
	// set font
	$pdf->SetFont('dejavusans', '', 12);
	// add a page
	$pdf->AddPage();
	$pat = JPATH_SITE.DS.'components'.DS.'com_camassistant'.DS.'assets'.DS.'images'.DS;
	//$tem = JPATH_SITE.DS.'templates'.DS.'camassistant_left'.DS.'images'.DS;
	//$pdf->Image($tem."mc_headicons.jpg", 186, 10, 20, 4, '', '', '', true, 150);
	//$pdf->Image(imagepath, x, y, width, height, 'type', 'link', 'align', resize=true, dpi=150);
?>
<!--<link rel="stylesheet" type="text/css" href="templates/camassistant_left/css/style.css">-->
<?PHP 
    if(count($BID_Vendors_info)>0)
	{
	// for($loop_start=0, $loop_stop=1; $loop_start<$loop_iterator; $loop_start++,$loop_stop)
     for($loop_start=0, $loop_stop=1; $loop_start<$loop_iterator; $loop_start++,$loop_stop++)
    {
		if($RFP_info->comp_logopath == '')
		$RFP_info->comp_logopath = 'noimage2.gif';
		$htmlcontent = '<table width="550px" border="0" cellspacing="0" cellpadding="0" align="center" style="padding-top:40px">'.
						$pdf->Image($pat.'properymanager/'.$RFP_info->comp_logopath, 10, 10, "70", "20", "", "", "", true, 150);
		$htmlcontent = '<tr><td width="235px" height="50" align="left" ></td>
							<td width="315px" align="right" style="text-align: right; font-size:21px;"><img width="50" height="12" src="templates/camassistant_left/images/mc_headicons.jpg" /><br/><strong><br/>'.$RFP_info->comp_name.'</strong><br />
		'.$RFP_info->mailaddress.'<br />'.$RFP_info->comp_city.','.$RFP_info->comp_state.$RFP_info->comp_zip.'<br /><strong>P</strong>: ('.$com_phone[0].')'.$com_phone[1].'-'.$com_phone[2].'</td></tr>
		
						<tr style="font-size:21px;">
							<td colspan="2" width="275px" align="left"><strong><br />PROPOSAL REPORT FOR:</strong><br />
							'.$RFP_info->property_name.'<br />'
							.$RFP_info->street.'<br />'
							.$RFP_info->city.','.$RFP_info->state.$RFP_info->zip.'</td>
						 </tr>
						
						<tr style="font-size:21px;">';
						$htmlcontent .='<td width="340px" align="left" style="width:500px; float:left;"><strong><br />Summary Details For RFP No. '.$RFP_info->id.':</strong><br />'.$RFP_info->projectName.'<br />Industry Solicited<br />RFP Close Date & Time: '.$RFP_info->proposalDueDate.$RFP_info->proposalDueTime.'<br />'.$RFP_info->work_perform.'<br />Frequency: '.$RFP_info->frequency.'							</td>
							<td style="width:300px; font-size:21px; text-align:left;"><strong><br />Proposal Overview Details:</strong><br />Proposals Submitted:  <strong>'.$BID_info->Submitted.'</strong><br />Proposals Rejected:  <strong>'.$BID_info->Rejected.'</strong><br />High Bid: <strong>$'.$Max_bid.'</strong><br />Low Bid: <strong>$'.$Min_bid.'</strong><br />Average Bid: <strong>$'.$Avg_bid.'</strong><br />
							</td>
						</tr>
						<tr style="height:5px;"><td align="left" colspan="2" style="font-size:5px;"><hr /></td></tr>
						';
		/***eof table pan****/
		
		/**** sof table pan****/
			$htmlcontent .= '<tr><td colspan="2"><table width="100%" border="0" cellpadding="0" cellspacing="0"><tr>';
							  $cnt=count($BID_Vendors_info);
							  if($cnt>0)
							  {
							
							  for($v=(4*$loop_start); $v<(4*$loop_stop); $v++) {
							  if($v<$total){
							  $full = $total-$remainder;
							  if( $v < $full){
			$htmlcontent .=  '<td width="100%" align="left" valign="middle">';
								} else if($remainder == 1){
			$htmlcontent .=  '<td width="25%" align="left" valign="middle">';								
								}
								else if($remainder == 2){
			$htmlcontent .=  '<td width="50%" align="left" valign="middle">';								
								}
								else if($remainder == 3){
			$htmlcontent .=  '<td width="75%" align="left" valign="middle">';								
								}
								else if($remainder == 0){
			$htmlcontent .=  '<td width="100%" align="left" valign="middle">';								
								}
			$htmlcontent .=   '<table width="100%" border="1" cellspacing="0" cellpadding="3">';
							  if($v%2 == 0)
							  $class = "#21314d";  
							  else 
							  $class = "#7ab800";
							  $vid = $v+1;
							   
							  if($BID_Vendors_info[$v]->company_name == '')
							  $BID_Vendors_info[$v]->company_name = '---';
			$htmlcontent .= '<tr align="center"><td bgcolor="'.$class.'" style="color:#FFF; font-weight:bold; font-family:ArialBlack; font-size:21px; height:15px;">VENDOR '.$vid.'</td></tr>';
							if($BID_Vendors_info[$v]->image != '') $image = $BID_Vendors_info[$v]->image; else $image = 'noimage1.gif'; 
			$htmlcontent .= '<tr><td><img src="components/com_camassistant/assets/images/vendors/pdf_resized/'.$image.'" width="128" height="53"/> </td></tr>
							 <tr><td height="15" align="center" style="font-size:19px ; text-align: center; ">'.$BID_Vendors_info[$v]->company_name.'</td></tr>';
			$htmlcontent .= '<tr class="plaintd"><td style=" border:0px;font-size:19px ;text-align: center;"><img src="templates/camassistant_left/images/rating.gif" width="50" height="10" /></td></tr>
							<tr><td height="15" style="font-size:19px ; text-align: center; ">'.$BID_Vendors_info[$v]->company_address.'</td>  </tr>
							<tr><td height="15" style="font-size:19px ; text-align: center; ">In-House Vendor? <strong>'. $BID_Vendors_info[$v]->in_house_vendor.'</strong></td></tr>
							<tr><td height="15" style="font-size:19px ; text-align: center; ">'. $BID_Vendors_info[$v]->company_phone.'</td>  </tr>';
							 if($BID_Vendors_info[$v]->phone_ext != '') $phone_ext = $BID_Vendors_info[$v]->phone_ext; else $phone_ext = '---'; 
			 $htmlcontent .= '<tr><td height="15" style="font-size:19px ; text-align: center; ">'.$phone_ext.'</td></tr>';
							if($BID_Vendors_info[$v]->alt_phone != '') $alt_ext = $BID_Vendors_info[$v]->alt_phone; else $alt_ext = '---';
			 $htmlcontent .= '<tr><td height="15" style="font-size:19px ; text-align: center; ">'.$alt_ext.'</td></tr>';
							 if($BID_Vendors_info[$v]->alt_phone_ext != '') $alt_phone_ext = $BID_Vendors_info[$v]->alt_phone_ext; else $alt_phone_ext = '---';
			 $htmlcontent .= '<tr><td  height="15" style="font-size:19px ; text-align: center; ">'.$alt_phone_ext.'</td></tr>
							 <tr><td height="15" style="font-size:19px ; text-align: center;">'.$BID_Vendors_info[$v]->established_year.'</td>
		  </tr>
							<tr><td height="15" style="font-size:19px ;text-align: center; ">'.$BID_Vendors_info[$v]->name.$BID_Vendors_info[$v]->lastname.'</td></tr>
							<tr><td height="15" style="font-size:19px ;text-align: center; ">'.$BID_Vendors_info[$v]->phone.'</td></tr>';		
							if($BID_Vendors_info[$v]->extension != '') $extension = $BID_Vendors_info[$v]->extension; else $extension = '---';
			  $htmlcontent .= '<tr><td height="15" style="font-size:19px ;text-align: center; ">'.$extension.'</td></tr>';
							if($BID_Vendors_info[$v]->cellphone != '') $cellphone = $BID_Vendors_info[$v]->cellphone; else $cellphone = '---';
			 $htmlcontent .= '<tr><td height="15" style="font-size:19px ;text-align: center; ">'.$cellphone.'</td></tr>';
							if($v%2 == 0) $class = "#7ab800";  else $class = "#21314d";
		   $htmlcontent .= '<tr><td height="15" bgcolor="'.$class.'" style="color:#FFF; font-size:21px; font-weight:bold; font-family:ArialBlack; text-align: center; ">TOTAL AMOUNT PROPOSED</td></tr>';
							if($v%2 == 0) 
							$class = "color:#21314d; font-size:21px; font-weight:bold; font-family:ArialBlack; text-align: center; ";
							else $class = "color:#7ab800; font-size:19px; font-weight:bold;  font-family:ArialBlack;text-align:center";
		  $htmlcontent .= '<tr><td height="15" style="'.$class.'">$'.$BID_Vendors_info[$v]->proposal_total_price.'</td></tr>
						<tr><td height="15" style="font-size:19px ;text-align: center;">Alternate Proposal Provided?</td></tr>';
							$db = JFactory::getDBO();
							$sql = "SELECT proposal_total_price FROM #__cam_vendor_proposals where Alt_bid = 'yes' AND proposedvendorid 	=".$BID_Vendors_info[$v]->proposedvendorid;
							$db->Setquery($sql);
							$Alt_Price = $db->loadResult(); if($Alt_Price != '') 
							{$res = 'Yes'; } else $res = 'No';
			$htmlcontent .=  '<tr><td height="15" style="font-size:19px ;text-align: center; color:#464646; font-weight:bold;  font-family:ArialBlack;">'.$res.'</td></tr>';
			if($Alt_Price != '') $Alt_Price = '$'.$Alt_Price; else $Alt_Price = '--';
			$htmlcontent .= '<tr><td height="15" style="font-size:19px ; text-align: center; color:#464646; font-weight:bold; font-family:ArialBlack;">'.$Alt_Price.'</td>
		  </tr>';				 
			$htmlcontent .= '</table></td>';
								}//inner if loop
							  }//end for loop 
							 }//if loop 
			$htmlcontent .= '</tr></table></td></tr><tr><td style="font-size:17px; align:left;"><font color="red">* </font>Designates exception for 1 or more line items. 	Please see vendor notes for details.</td></tr></table>';
			
			$style = array('color' => array(220, 220, 220));
			$style7 = array('width' => 0.1, 'color' => array(220, 220, 220));
			$pdf->SetLineStyle($style7);
		$pdf->writeHTML($htmlcontent, true, 0, true, 0);
		// add a page
		$pdf->AddPage();
		
			/************************************************************End 1st & 2nd Page TASKS SUMMARY****************************************************************/
	
			 /***********************************************3rd Page TASKS SUMMARY*************************************************************/
		
		//echo "<pre>"; print_r($DOCS_summary); exit;
		$TASKS_summary = $this->TASKS_summary;
		$DOCS_summary = $this->DOCS_summary;
		$NOTES_summary = $this->NOTES_summary;
		$EXCEPTION_summary = $this->EXCEPTION_summary;
		$RFP_NOTES_summary = $this->RFP_NOTES_summary;
		//echo '<pre>'; print_r($NOTES_summary); exit;
		$SPL_REQ_DETAILS = $this->SPLRequirements_details;
		$vendors_cnt = $this->vendors_cnt;
		$cat = $this->SPLReq_Category;
		$COM = $this->COM_docs_summary;
		$main = $SPL_REQ_DETAILS['main'];
		$sub = $SPL_REQ_DETAILS['sub'];
		$child = $SPL_REQ_DETAILS['child'];
		$price = $SPL_REQ_DETAILS['price'];
		//echo "<pre>"; print_r($NOTES_summary); print_r($EXCEPTION_summary);
			$htmlcontent3 = '<table width="550px" border="0" cellspacing="0" cellpadding="3" align="center" style="padding-top:40px">';
			$pdf->Image($pat.'properymanager/'.$RFP_info->comp_logopath, 10, 10, "70", "20", "", "#", "", true, 100);
			$htmlcontent3 .='<tr><td width="205px" height="50" align="left" ></td>
							<td width="345px" style="text-align: left; font-size:21px;"><img width="50" height="12" src="templates/camassistant_left/images/mc_headicons.jpg" /><br/><strong><br/>'.$RFP_info->comp_name.'</strong><br />
		'.$RFP_info->mailaddress.'<br />'.$RFP_info->comp_city.','.$RFP_info->comp_state.$RFP_info->comp_zip.'<br /><strong>P</strong>: ('.$com_phone[0].')'.$com_phone[1].'-'.$com_phone[2].'</td>
			</tr>';
		
			$htmlcontent3 .='<tr><td colspan="2" height="15" bgcolor="#7ab800" style="color:#FFF; font-weight:bold; font-family:ArialBlack; font-size:21px ; text-align: center; ">RFP TASKS REQUESTED</td></tr>';
			
			$htmlcontent3 .= '<tr><td colspan="2">';
							 $cnt=count($BID_Vendors_info);
							 if($cnt>0)
							 {
							 $rfptask=count($RFP_NOTES_summary); 
							 if($rfptask>0)
							 for($li=($rfptask*$loop_start); $li<($rfptask*$loop_stop); $li++)
							 {
							 $ldesc = 0;
							 $lid = $li+1;
			$htmlcontent3 .='<tr><td colspan="2" style="font-size:20px; text-align: left; font-weight:bold;">LINE ITEM #'.$lid.': '.$RFP_NOTES_summary[$ldesc]->task_desc.'</td></tr>';
			
							 for($v=($cnt*$loop_start); $v<($cnt*$loop_stop); $v++)
							 //for($v=0; $v<6; $v++)
							 {
							 $x = 0;
							 if($v%2 == 0)
							 $class = "#7ab800";  
							  else 
							  $class = "#21314d";
							 $vid = $v+1;
			$htmlcontent3 .='<table width="100%" border="1" cellpadding="3">';
			$htmlcontent3 .='<tr><td height="15" width="63"  bgcolor="'.$class.'" style="color:#FFF; font-weight:bold; font-family:ArialBlack; font-size:21px ; text-align: center; ">VENDOR '.$vid.'</td></tr>';	
							$cnt_tasks=count($NOTES_summary); 
							if($cnt_tasks>0)
							{
							$flag = 0;
							$htmlcontent3 .= '<tr><td height="15" style="font-size:19px ;text-align: left; ">';
								 for($T=0; $T<$cnt_tasks; $T++)
								 {
									 $cnt_notes = count($NOTES_summary[$T]->task_notes); 
									 //echo "<pre>"; print_r($NOTES_summary[$T]->task_notes); 
									 for($N=0; $N<$cnt_notes; $N++)
									 {
									  if($NOTES_summary[$T]->task_notes[$N]->add_notes != '')
									  {
										  if($NOTES_summary[$T]->task_notes[$N]->vendor_id == $BID_Vendors_info[$v]->proposedvendorid  )
										  {
										  $y = $x+1;
										  $htmlcontent3 .= '<b>LINE ITEM #'.$y.'</b><p>'.$NOTES_summary[$T]->task_notes[$N]->add_notes.'</p><p style="color:#FF0000"><b>EXCEPTION(S) FOR LINE ITEM #'.$y.'</b>&nbsp;'.$EXCEPTION_summary[$T]->task_exception[$N]->add_exception.'</p>';		
									if($DOCS_summary[$D]->is_req_docvendors == '1')
								  { 
								   $htmlcontent3 .= '<p style="color:#FF0000"><b>PRICE FOR LINE ITEM #'.$y.'</b>&nbsp; $'.$DOCS_summary[$D]->doc_price[$N]->item_price;
								   }			
										  $x++;
										  $flag = 1;
										  }
									  }
									 } 
								 } 
								  
								if($flag == 0)
								{
								$htmlcontent3 .='NOTES: None<br />EXCEPTIONS: None<br />PRICE: $1,100.00<br />Attachments: None';
								}
								$htmlcontent3 .='</td></tr>';
							}
							$htmlcontent3 .= '</table>';
							}//end inner for loop 
							$ldesc = $ldesc+1;
							}//end main for loop 
							}//if loop 
		    $htmlcontent3 .= '</td></tr>';
			$htmlcontent3 .= '</table>'; /* comment this if you uncomment the below code  anil */
			// commented by anil
			/*$htmlcontent3 .='<tr><td colspan="2" height="15" bgcolor="#21314d" style="color:#FFF; font-weight:bold; font-family:ArialBlack; font-size:21px ; text-align: center; ">SPECIAL REQUIREMENTS — Vendors meet the following requirements:</td></tr>';
			$htmlcontent3 .='<tr><td colspan="2"><table border="1" width="100%"><tr><td style="font-size:19px; text-align: left; margin:10px; ">';		
		
							$count=count($vendors_cnt);
							if($count>0){ for($v=(4*$loop_start); $v<(4*$loop_stop); $v++) { 
							$cnt = $v+1;
							 if($v%2 == 0)
							 $class = "#7ab800";  
							  else 
							  $class = "#21314d";
							  if($v != 0)
							$htmlcontent3 .= '<p></p>';
							$htmlcontent3 .=  '<span style="color:'.$class.'; font-weight:bold; font-family:ArialBlack; font-size:21px ;">VENDOR'.$cnt.':</span>';
							for($c=0; $c<count($cat); $c++)
							{
							
								 for($m=0; $m<count($main); $m++)
								 {
									$exist_arr[] = '';
									$vendor_arr[] = '';
										if(($cat[$c]->req_id == $main[$m]->main_id) || !in_array($vendors_cnt[$v]->proposedvendorid,$vendor_arr) )
										{
											$htmlcontent3 .=  $main[$m]->main_title.',&nbsp;';  
											$exist_arr[] = $main[$m]->main_title;
											$vendor_arr[] = $vendors_cnt[$v]->proposedvendorid;
										}
								if(($cat[$c]->req_id == $main[$m]->main_id) && count($sub)>0)
								{
									for($s=0; $s<count($sub); $s++)
								   {
										for($ch=0; $ch<count($child); $ch++)
										{
											if($cat[$c]->req_id == $main[$m]->main_id && $cat[$c]->req_id == $sub[$s]->main_id &&  $sub[$s]->sub_id == $child[$ch]->sub_id) {
											
											if($child[$ch]->child_id != 8 && $child[$ch]->child_id != 9 &&  $child[$ch]->child_id != 10)
											$htmlcontent3 .= '('.$child[$ch]->child_title.')';
											if($child[$ch]->child_id == 8 || $child[$ch]->child_id == 9)
											{
											 $db = JFactory::getDBO();
											 $sql = "SELECT amount FROM  #__cam_rfpsow_splreq_price WHERE req_id = ".$child[$ch]->child_id." AND rfp_id = ".$RFP_info->id." AND vendor_id=".$vendors_cnt[$v]->proposedvendorid;
												  $db->Setquery($sql);
												  $amount = $db->loadResult();
											 $htmlcontent3 .= '('.$sub[$s]->sub_title.'&nbsp;'; 
											 if($amount != '')
											 {
											 $htmlcontent3 .= '-$ '.$amount.')' ;
											 if($COM[$v]['GLI'] != '')
											 $htmlcontent3 .= '&nbsp;GLI_'.$COM[$v]['GLI'];
											 if($COM[$v]['W9'] != '')
											 $htmlcontent3 .= '&nbsp;,&nbsp;W9_'.$COM[$v]['W9']; 
											  }
											 else
											 {
											 $htmlcontent3 .= '- $0)' ;
											 if($COM[$v]['GLI'] != '')
											 $htmlcontent3 .= '&nbsp;GLI_'.$COM[$v]['GLI'];
											 if($COM[$v]['W9'] != '')
											 $htmlcontent3 .= '&nbsp;,&nbsp;W9_'.$COM[$v]['W9']; 
											  }
											 } break; }
										}
									}
									 }
								  }
							 } 
							 }
							 }
			$htmlcontent3 .='</td></tr></table>'; 
			
			
			$htmlcontent3 .='</td></tr></table>';*/
			// commented by anil
			
		//echo $htmlcontent3; exit;
		$pdf->writeHTML($htmlcontent3, true, 0, true, 0);	
		// add a page
		//$pdf->AddPage();				 
		/************************************************************End 3rd Page TASKS SUMMARY****************************************************************/
		
		/************************************************************4th Page TASKS SUMMARY********************************************************************/
		
		//echo "<pre>"; print_r($cat);  print_r($main); print_r($sub);  print_r($child); 
		/* 05-08-2011 */
		/*error_reporting('E_WARNING)');
		
			$htmlcontent4 = '<table width="550px" border="0" cellspacing="0" cellpadding="3" align="center" style="padding-top:40px">';
						$pdf->Image($pat.'properymanager/'.$RFP_info->comp_logopath, 10, 10, "70", "20", "", "#", "", true, 100);
			$htmlcontent4 .= '<tr><td width="235px" height="50" align="left" ></td>
							<td width="310px" style="text-align: left; font-size:21px;"><img width="50" height="12" src="templates/camassistant_left/images/mc_headicons.jpg" /><br/><strong><br/>'.$RFP_info->comp_name.'</strong><br />
		'.$RFP_info->mailaddress.'<br />'.$RFP_info->comp_city.','.$RFP_info->comp_state.$RFP_info->comp_zip.'<br /><strong>P</strong>: ('.$com_phone[0].')'.$com_phone[1].'-'.$com_phone[2].'</td></tr>';
						
		//$htmlcontent4 .='<tr style="height:5px;"><td align="left" colspan="2" style="font-size:5px;"><hr /></td></tr>';
								
			$htmlcontent4 .='<tr><td colspan="2" height="15" bgcolor="#21314d" style="color:#FFF; font-weight:bold; font-family:ArialBlack; font-size:21px ; text-align: center; ">SPECIAL REQUIREMENTS - Vendors meet the following requirements:</td></tr>';
			$htmlcontent4 .='<tr><td colspan="2"><table border="1" width="100%"><tr><td style="font-size:19px; text-align: left; margin:10px; ">';		
		
							$count=count($vendors_cnt);
							if($count>0){ for($v=(4*$loop_start); $v<(4*$loop_stop); $v++) { 
							$cnt = $v+1;
							 if($v%2 == 0)
							 $class = "#7ab800";  
							  else 
							  $class = "#21314d";
							  if($v != 0)
							$htmlcontent4 .= '<p></p>';
							$htmlcontent4 .=  '<span style="color:'.$class.'; font-weight:bold; font-family:ArialBlack; font-size:21px ;">VENDOR'.$cnt.':</span>';
							for($c=0; $c<count($cat); $c++)
							{
							
								 for($m=0; $m<count($main); $m++)
								 {
									$exist_arr[] = '';
									$vendor_arr[] = '';
										if(($cat[$c]->req_id == $main[$m]->main_id) || !in_array($vendors_cnt[$v]->proposedvendorid,$vendor_arr) )
										{
											$htmlcontent4 .=  $main[$m]->main_title.',&nbsp;';  
											$exist_arr[] = $main[$m]->main_title;
											$vendor_arr[] = $vendors_cnt[$v]->proposedvendorid;
										}
								if(($cat[$c]->req_id == $main[$m]->main_id) && count($sub)>0)
								{
									for($s=0; $s<count($sub); $s++)
								   {
										for($ch=0; $ch<count($child); $ch++)
										{
											if($cat[$c]->req_id == $main[$m]->main_id && $cat[$c]->req_id == $sub[$s]->main_id &&  $sub[$s]->sub_id == $child[$ch]->sub_id) {
											if($child[$ch]->child_id != 8 && $child[$ch]->child_id != 9 &&  $child[$ch]->child_id != 10)
											$htmlcontent4 .= '('.$child[$ch]->child_title.')';
											if($child[$ch]->child_id == 8 || $child[$ch]->child_id == 9)
											{
											 $db = JFactory::getDBO();
											 $sql = "SELECT amount FROM  #__cam_rfpsow_splreq_price WHERE req_id = ".$child[$ch]->child_id." AND rfp_id = ".$RFP_info->id." AND vendor_id=".$vendors_cnt[$v]->proposedvendorid;
												  $db->Setquery($sql);
												  $amount = $db->loadResult();
											 $htmlcontent4 .= '('.$sub[$s]->sub_title.'&nbsp;'; 
											 if($amount != '')
											 {
											 $htmlcontent4 .= '-$ '.$amount.')' ;
											 if($COM[$v]['GLI'] != '')
											 $htmlcontent4 .= '&nbsp;GLI_'.$COM[$v]['GLI'];
											 if($COM[$v]['W9'] != '')
											 $htmlcontent4 .= '&nbsp;,&nbsp;W9_'.$COM[$v]['W9']; 
											  }
											 else
											 {
											 $htmlcontent4 .= '- $0)' ;
											 if($COM[$v]['GLI'] != '')
											 $htmlcontent4 .= '&nbsp;GLI_'.$COM[$v]['GLI'];
											 if($COM[$v]['W9'] != '')
											 $htmlcontent4 .= '&nbsp;,&nbsp;W9_'.$COM[$v]['W9']; 
											  }
											 } break; }
										}
									}
									 }
								  }
							 } 
							 }
							 }
			$htmlcontent4 .='</td></tr></table>'; 
							
		   $htmlcontent4 .= '</td></tr></table>';	
		
		$pdf->writeHTML($htmlcontent4, true, 0, true, 0);*/
		/* 05-08-2011 
		
		// add a page
		if($loop_start < $loop_iterator-1){
		$pdf->AddPage();
		}
		/************************************************************End of 4th Page TASKS SUMMARY*************************************************************/
     }//end - for($loop_start=0, $loop_stop=1; $loop_start<count($BID_Vendors_info); $loop_start++,$loop_stop++)
	} //end - if(count($BID_Vendors_info)>0)
	else
	{
	$htmlcontent = "<font>No Records Found</font>";
	$pdf->writeHTML($htmlcontent, true, 0, true, 0);
	}
	/******* eof table pan********/
	
	
	$pdf->lastPage();
	$title= $RFP_info->comp_name.'.pdf'; //set title
	$pdf->SetTitle($title);//set title
	ob_end_clean();
	//$upl_file_name=$pdf->Output($title, 'I');
	$upl_file_name=$pdf->Output($title, 'D');
	//$upl_file_name=$pdf->Output($title, 'I');
	//exit;
 ?>
