<?php
/**
 * @version		1.0.0 camassistant $
 * @package		camassistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
$Itemid = JRequest::getVar('Itemid',''); 
?>
<script type="text/javascript" src="<?php echo Juri::base(); ?>components/com_camassistant/skin/js/jquery-1.4.4.min.js"></script>
<script type="text/javascript">
G = jQuery.noConflict();
function validate_data2(e)
{
 e.preventDefault();
 var frm = document.VendorForm2;

  if(frm.property_name.value == '')
 {
 alert('Please Select Property');
 frm.property_name.focus();
 return false;
 } else if(frm.property_name.value == 'Select Propety')
 {
 alert('Please Select Property');
 frm.property_name.focus();
 return false;
 }
  else if(frm.firstname.value == '')
 {
 alert('Please enter client first name');
 frm.firstname.focus();
 return false;
 }  
 else if(frm.lastname.value == '')
 {
 alert('Please enter client last name');
 frm.lastname.focus();
 return false;
 }
 else if(frm.email.value == '')
 {
 alert('Please enter client email');
 frm.email.focus();
 return false;
 }
 else if(frm.email.value !== '')
 {
 
var emails= frm.email.value;

G.post("index2.php?option=com_camassistant&controller=vendorscenter&task=checktoallemails", {mailid: ""+emails+""}, function(data){
		if(data == 1){
		alert("Already user exists with this email");
		return false;
		}
		else if(frm.email.value == '')
 {
 alert('Please enter your email ID');
 frm.email.focus();
 return false;
 }
 var mail=/\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/;
 if(mail.test(frm.email.value)==false)
 {
 alert("Please enter the valid email");
frm.email.focus();
 return false;
 } else if(frm.user_email.value != '')
 {
 alert(frm.user_email.value);
 frm.email.focus();
  return false;
 }

 else	
 document.getElementById('VendorForm2').submit();

 });
 } 
  
 return;
}
 function moveOnMax(field,nextFieldID){
  if(field.value.length >= field.maxLength){
    document.getElementById(nextFieldID).focus();
  }
}
function cancel()
{
window.location="index.php?option=com_camassistant&controller=boardmembers&task=listboardmembers&Itemid=151";
}
</script>
<script type="text/javascript">
G = jQuery.noConflict();
G('document').ready(function(){
G('#property_name').change(function(){
if(G(this).val() != '0' )
G( this ).prev().addClass( 'active' );
else
G( this ).prev().removeClass( 'active' );
	});
	
G('#firstname').keyup(function(){
		if( G(this).val() == '' )
		G( this ).prev().removeClass( 'active' );
		else
		G( this ).prev().addClass( 'active' );
	});
G('#lastname').keyup(function(){
	if( G(this).val() == '' )
	G( this ).prev().removeClass( 'active' );
	else
	G( this ).prev().addClass( 'active' );
});	
G('#email').keyup(function(){
	if( G(this).val() == '' )
	G( this ).prev().removeClass( 'active' );
	else
	G( this ).prev().addClass( 'active' );
});	

G('#email').bind('input',function(){ 
    if( G(this).val() == '' )
	G( this ).prev().removeClass( 'active' );
	else
	G( this ).prev().addClass( 'active' );          
    });
    G('#firstname').bind('input',function(){ 
    if( G(this).val() == '' )
	G( this ).prev().removeClass( 'active' );
	else
	G( this ).prev().addClass( 'active' );          
    });
    G('#lastname').bind('input',function(){ 
    if( G(this).val() == '' )
	G( this ).prev().removeClass( 'active' );
	else
	G( this ).prev().addClass( 'active' );          
    });
		
});
</script>




<div id="container_inner">
<div class = "addnewboardmem" >
 <div class="ttl1">Client Information</div>
 <div class="newtopborder1"></div>
</div>
<div class="clear"></div>
<?php //echo "<pre>"; print_r($this->details); ?>
<form enctype="multipart/form-data" action="index.php?option=com_camassistant&amp;controller=boardmembers&amp;Itemid=<?PHP echo $Itemid; ?>&amp;task=save_boardmember" method="post" name="VendorForm2" id="VendorForm2">
<div id="signup-form" style="margin-top:10px;">

<div class="signup">

<label class="selecte_propertyadd" style="margin-top:-12px;">Select Property:</label>
<?php 
$properties = $this->propertyList;?>
<select id="property_name"  name="property_name" >

	<?php
		for( $p=0; $p<count($properties); $p++ ){ ?>
		<option value="<?php echo $properties[$p]->value; ?>"><?php echo str_replace('_',' ',$properties[$p]->text); ?></option>
		<?php }
	?>
	</select>

</div>
<div class="signup">
<label>Title:</label>
<select name="board_position" id="board_position">
<option value="Owner">Owner</option>
<option value="President">President</option>
<option value="Vice President">Vice President</option>
<option value="Treasurer">Treasurer</option>
<option value="Secretary">Secretary</option>
<option value="Director">Director</option>

</select>
</div>
<div class="signup">
<label>Salutation:</label>
<select name="salutation" >
<option >Mr.</option>
<option >Mrs.</option>
<option>Ms.</option>
</select>
</div>

<div class="signup col_2">
<div class="state">
<label class="addfirstname">First Name: </label>
<input name="firstname" id="firstname" type="text" value=""/>
</div>
<div class="zip">
<label class="addlastname">Last Name: </label>
<input name="lastname"  id="lastname" type="text"  value=""/>
</div>
</div>
<div class="signup">
<label>Street Address:  </label>
<input name="streeaddress" type="text" value=""/>
</div>
<div class="signup col_2">
<div class="state">
<label>State: </label>
<select name="state" id="stateid" onchange="javascript:county();" >
<option value="">Please Select State</option>
  <?php 

for ($i=0; $i<count($this->states); $i++){
$states = $this->states[$i];
?>

<option value="<?php echo $states->state_id?>" <?php if($states->state_id== $this->details->state) echo "selected";?>><?php echo $states->state_name?></option>
<?php } ?>
</select>
</div>
<div class="zip">
<label>Zip Code:</label>
<input name="zipcode" type="text" maxlength="5" onkeydown="if(isNaN(this.value)) alert('Please enter valid number');" value=""/>
</div>
</div>

<div class="signup">
<label class="selecte_propertyadd ">Email: </label>

<input name="email" type="text" id="email"  value="<?PHP echo $this->details->email ?>" onkeydown="if((this.value)!='<?php echo $this->details->email ?>'){ javascript: verifyuser('<?php echo $this->details->email ?>');}" onmousedown="if((this.value)!='<?php echo $this->details->email ?>'){ javascript: verifyuser('<?php echo $this->details->email ?>');}" onblur="if((this.value)!='<?php echo $this->details->email ?>'){ javascript: verifyuser('<?php echo $this->details->email ?>');}"/>
<input style="color:#FF0000;display:none; background:#ffffff; border-color:#ffffff; padding-top:22px;" type="hidden" name="user_email" id="user_email" value="" readonly=""/>

</div>
<div class="signup">
<label>Alt. Email:  </label>

<input name="altemail" type="text" id="altemail" value="" />

</div>

<div class="signup">
<div class="cp">
<label>Phone: </label>
<input class="sm-input" id="phone_1" name="phone_1" type="text"  value="" maxLength="3" onkeyup="moveOnMax(this,'phone_2')" onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); " />
 <input id="phone_2" class="sm-input" name="phone_2" type="text"  value="" maxLength="3"  onkeyup="moveOnMax(this,'phone_3')" onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); "/> - 
 <input id="phone_3" name="phone_3" class="sm-input" type="text"  value="" maxLength="4" onkeyup="moveOnMax(this,'extension')"  onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); "/>
</div>

<div class="ext">
<label>Ext:</label>
<input name="extension" type="text" id="extension" class="sm-input" maxlength="4"  value=""  onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); " /></div>
<div class="clear"></div>
</div>																			
<div class="signup">
<div class="cp">
<label>Alt. Phone: </label>
<input id="altphone_1" name="altphone_1" type="text" class="sm-input" value="" maxLength="3" onkeyup="moveOnMax(this,'altphone_2')" onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); " />
 <input id="altphone_2" name="altphone_2" type="text" class="sm-input" value="" maxLength="3"  onkeyup="moveOnMax(this,'altphone_3')" onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); "/> - 
 <input id="altphone_3" name="altphone_3" type="text" class="sm-input" value="" maxLength="4" onkeyup="moveOnMax(this,'altextension')"  onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); "/>
</div>

<div class="ext">
<label>Ext:</label>
<input name="altextension" id ="altextension" type="text" maxlength="4" class="sm-input" value=""  onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); " /></div>
<div class="clear"></div>
</div>																			
<div class="signup">

<label>Fax:</label>
<input id="fax_1" name="fax_1" type="text" class="sm-input" value="" maxLength="3" onkeyup="moveOnMax(this,'fax_2')" onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); " />
 <input id="fax_2" name="fax_2" type="text" class="sm-input" value="" maxLength="3"  onkeyup="moveOnMax(this,'fax_3')" onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); "/> - 
 <input id="fax_3" name="fax_3" type="text" class="sm-input" value="" maxLength="4" onkeyup="moveOnMax(this,'')"  onkeydown="if(isNaN(this.value)) alert('Please enter valid number'); "/>
</div>


<div class="clear"></div>
<div class="client_permissions">
<div class="inner_client-heading">
        <div class="ttl1">Client Permissions</div>
		<div class="newtopborderper"></div>
      </div><!-- inner_client-heading -->
      <div class="permsssionhide">
 
          <div class="client_permission_block">
            <div><strong>Copied on Vendor proposals?</strong></div>
            <div >When you end a request, your client will receive an automatic email notification with a link to download a copy of the proposal report, which will contain every Vendor's submitted proposal.</div>
            <div><input type="radio" name="radio1" onclick="return false;"> <label>Yes</label> 
            <input type="radio" name="radio1" checked="checked" > <label>No</label></div>
          </div><br/><!-- client_permission_block -->
          
          <div class="client_permission_block">
            <div><strong>Access to "My Vendor" list?</strong></div>
            <div >Your client will have "read-only" access to your "My Vendors" list or "Corporate Preferred Vendors" list (Master Account holders only). This allows them the ability to view contact information, compliance statuses, and more.  Note:  They will not be able to remove, add, or edit your list.</div>
            <div><input type="radio" name="radio2" onclick="return false;"> <label>Yes</label> 
            <input type="radio" name="radio2" checked="checked"> <label>No</label></div><br/>
          </div><!-- client_permission_block -->
          
          <div class="client_permission_block">
            <div><strong>Ability to invite Vendors to requests?</strong></div>
            <div >Your Client will be able to invite Vendors to participate in requests that you submitted for this property only.  Note: They will not be able to uninvite vendors, send reminders, or end bidding.</div>
            <div><input type="radio" name="radio3" onclick="return false;"> <label>Yes</label> 
            <input type="radio" name="radio3" checked="checked"> <label>No</label></div><br/>
          </div><!-- client_permission_block -->
          
          <div class="client_permission_block">
            <div><strong>Requires approval before submitting requests?</strong></div>
            <div>Your Client will be required to approve the submission of a request before it is delivered to Vendors. If a project is not approved, the Client will be able to submit feedback so your request may be revised and then resubmitted for approval.</div>
            <div><input type="radio" name="radio4" onclick="return false;"> <label>Yes</label> 
            <input type="radio" name="radio4" checked="checked"> <label>No</label></div><br/>
          </div><!-- client_permission_block -->
          
          <div class="client_permission_block">
            <div><strong>Requires approval before awarding requests?</strong></div>
            <div >Your Client will be required to approve the awarding of a request to a Vendor before notifications are delivered to all participating Vendors.  If an award is not approved, the Client will be able to submit feedback so the awarding may be revised and then resubmitted for approval.</div>
            <div><input type="radio" name="radio5" onclick="return false;"> <label>Yes</label> 
            <input type="radio" name="radio5" checked="checked" > <label>No</label></div><br/>
          </div><!-- client_permission_block -->
  </div>

<div align="right" id="topborder_row1"></div>
<div class="checktextdetails" style="margin-left:0px;">
<input type="hidden" name="user_id" value="<?PHP  echo $this->user_id; ?>" />
<a  href="javascript:void(0)" class="manager_cancel" onclick="cancel()"></a>
<a  href="javascript:void(0)" class="manager_submit" onclick="javascript: return validate_data2(event);"></a>
 </div>
</div>




<div class="clear"></div>
</div>

<input type="hidden" name="id" value="<?PHP echo $this->details->id; ?>"  />
<input type="hidden" name="accept" value="<?PHP echo $_REQUEST['accept'] ?>"  />
</form>
</div> 
<div class="clear"></div>
</div>



