<?php
/**
 * @version		1.0.0 cam assistant $
 * @package		cam_assistant
 * @copyright	Copyright © 2010 - All rights reserved.
 * @license		GNU/GPL
 * @author		
 * @author mail	nobody@nobody.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport( 'joomla.application.component.view' );

class invitationsViewInvitations extends Jview
{
	function display($tpl = null){

			$pending = $this->get('pending');
            $masterPending = $this->get('masterPending');
			//echo "<pre>"; print_r($pending); exit;
			$this->assignRef('pending', $pending);
            $this->assignRef('masterpending', $masterPending);
			$task = JRequest::getVar("task",'');
			$model = $this->getModel('invitations');
			if($task == 'gettermspopup'){
			$managerid = JRequest::getVar("managerid",'');
			$terms = $model->getterms($managerid);
			$this->assignRef('terms', $terms);
			$this->setLayout('termspopup');
			parent::display($tpl);
			}
			else if($task == 'vliststatus'){
			$masterPending = $this->get('masterPending_clients');
			
			$pending = $this->get('pending');
			$this->assignRef('pending_cc', $pending);
			
			$this->assignRef('masterpending', $masterPending);
			$preferredmans = $model->getpreferredmanagers();
			$this->assignRef('preferredmans', $preferredmans);
			$this->setLayout('vliststatus');
			parent::display($tpl);
			}
			else if( $task == 'preferredcodes' ){
			$purchased_codes = $model->purchasedocde();
			$this->assignRef('purchased_codes', $purchased_codes);
			$this->setLayout('preferredcodes');
			parent::display($tpl);
			}
			else if( $task == 'newcode' ){
			$purchased_codes = $model->purchasedocde();
			$this->assignRef('purchased_codes', $purchased_codes);
			
			$cancelled_codes = $model->purchasedocde_cancelled();
			$this->assignRef('cancelled_codes', $cancelled_codes);
			$this->setLayout('newcode_purchase');
			parent::display($tpl);
			}
			else if( $task == 'vendortext' ){
			$this->setLayout('vendor_text');
			parent::display($tpl);
			}
			else{
			parent::display($tpl);
			}		
			}
		

	}
?>